import { Logger } from '../../../shared/logger';
import { ObjectId } from 'mongodb';
import { MongoService } from './mongo.service';
import { MetadataCacheService } from '../../cache/services/metadata-cache.service';
import { QueryBuilderService } from '../../query-builder/query-builder.service';
import { MongoMigrationJournalService } from './mongo-migration-journal.service';
import { MongoSchemaDiffService } from './mongo-schema-diff.service';
type BsonType =
  | 'string'
  | 'int'
  | 'long'
  | 'double'
  | 'bool'
  | 'date'
  | 'objectId'
  | 'object'
  | 'array';
export class MongoSchemaMigrationService {
  private readonly logger = new Logger(MongoSchemaMigrationService.name);
  private readonly mongoService: MongoService;
  private readonly metadataCacheService: MetadataCacheService;
  private readonly queryBuilderService: QueryBuilderService;
  private readonly migrationJournalService: MongoMigrationJournalService;
  private readonly schemaDiffService: MongoSchemaDiffService;
  constructor(deps: {
    mongoService: MongoService;
    metadataCacheService: MetadataCacheService;
    queryBuilderService: QueryBuilderService;
    mongoMigrationJournalService: MongoMigrationJournalService;
    mongoSchemaDiffService: MongoSchemaDiffService;
  }) {
    this.mongoService = deps.mongoService;
    this.metadataCacheService = deps.metadataCacheService;
    this.queryBuilderService = deps.queryBuilderService;
    this.migrationJournalService = deps.mongoMigrationJournalService;
    this.schemaDiffService = deps.mongoSchemaDiffService;
  }
  private sqlTypeToBsonType(type: string): BsonType {
    const typeMap: Record<string, BsonType> = {
      string: 'string',
      text: 'string',
      varchar: 'string',
      char: 'string',
      uuid: 'string',
      richtext: 'string',
      int: 'int',
      integer: 'int',
      smallint: 'int',
      tinyint: 'int',
      bigint: 'long',
      float: 'double',
      double: 'double',
      decimal: 'double',
      numeric: 'double',
      real: 'double',
      boolean: 'bool',
      bool: 'bool',
      date: 'date',
      datetime: 'date',
      timestamp: 'date',
      json: 'object',
      'simple-json': 'object',
      array: 'array',
      enum: 'string',
    };
    return typeMap[type] || 'string';
  }
  private createValidationSchema(columns: any[]): any {
    const properties: any = {};
    const required: string[] = [];
    for (const col of columns) {
      if (
        col.name === '_id' ||
        col.name === 'createdAt' ||
        col.name === 'updatedAt'
      ) {
        continue;
      }
      const bsonType = this.sqlTypeToBsonType(col.type);
      properties[col.name] = {
        bsonType: col.isNullable ? [bsonType, 'null'] : bsonType,
        description: col.description || col.name,
      };
      if (!col.isNullable && !col.defaultValue && !col.isGenerated) {
        required.push(col.name);
      }
    }
    const schema: any = {
      bsonType: 'object',
      properties,
    };
    if (required.length > 0) {
      schema.required = required;
    }
    return schema;
  }
  private createPartialFilterForUnique(fields: string[]): any {
    const filter: any = {};
    for (const field of fields) {
      filter[field] = { $exists: true, $ne: null };
    }
    return filter;
  }
  async createCollection(tableMetadata: any): Promise<void> {
    const db = this.mongoService.getDb();
    const collectionName = tableMetadata.name;
    try {
      const collections = await db
        .listCollections({ name: collectionName })
        .toArray();
      if (collections.length > 0) {
        this.logger.warn(
          ` Collection ${collectionName} already exists, skipping creation`,
        );
        return;
      }
      const validationSchema = this.createValidationSchema(
        tableMetadata.columns || [],
      );
      await db.createCollection(collectionName, {
        validator: { $jsonSchema: validationSchema },
        validationLevel: 'moderate',
        validationAction: 'error',
      });
      const autoGeneratedIndexes = await this.createIndexes(
        collectionName,
        tableMetadata.columns || [],
        tableMetadata.uniques || [],
        tableMetadata.indexes || [],
        tableMetadata.relations || [],
      );
      await this.schemaDiffService.updateMetadataIndexes(
        collectionName,
        tableMetadata.indexes || [],
        autoGeneratedIndexes,
      );
    } catch (error) {
      this.logger.error(
        `Failed to create collection ${collectionName}: ${error.message}`,
      );
      throw error;
    }
  }
  async updateCollection(
    collectionName: string,
    oldMetadata: any,
    newMetadata: any,
    rawBeforeSnapshot?: any,
  ): Promise<void> {
    try {
      const diff = this.schemaDiffService.generateMongoSchemaDiff(
        oldMetadata,
        newMetadata,
      );
      const downDiff = this.schemaDiffService.generateMongoSchemaDiff(
        newMetadata,
        oldMetadata,
      );
      this.logger.log(
        `Diff for ${collectionName}: ` +
          `columns(+${diff.columns.create.length}/-${diff.columns.delete.length}/~${diff.columns.update.length}/ren:${diff.columns.rename.length}), ` +
          `validation=${diff.validation.changed}, ` +
          `indexes(+${diff.indexes.create.length}/-${diff.indexes.delete.length}/=${diff.indexes.unchanged.length}), ` +
          `junctions(+${diff.junctionCollections.create.length}/-${diff.junctionCollections.drop.length}/ren:${diff.junctionCollections.rename.length})`,
      );
      let journalUuid: string | undefined;
      try {
        journalUuid = await this.migrationJournalService.record({
          tableName: collectionName,
          operation: 'update',
          upDiff: diff,
          downDiff,
          beforeSnapshot: oldMetadata,
          rawBeforeSnapshot: rawBeforeSnapshot || null,
        });
        await this.migrationJournalService.markRunning(journalUuid);
      } catch (journalErr: any) {
        this.logger.warn(
          `Journal record failed (non-fatal): ${journalErr.message}`,
        );
      }
      try {
        await this.schemaDiffService.executeMongoSchemaDiff(
          collectionName,
          diff,
          oldMetadata,
          newMetadata,
        );
        if (journalUuid) {
          await this.migrationJournalService
            .markCompleted(journalUuid)
            .catch(() => {});
        }
      } catch (execError) {
        if (journalUuid) {
          this.logger.warn(
            `Migration failed, executing rollback for ${journalUuid}`,
          );
          await this.migrationJournalService
            .executeRolldown(journalUuid, (downDiffInner) =>
              this.schemaDiffService.executeMongoSchemaDiff(
                collectionName,
                downDiffInner,
                newMetadata,
                oldMetadata,
              ),
            )
            .catch(() => {});
        }
        throw execError;
      }
    } catch (error) {
      this.logger.error(
        `Failed to update collection ${collectionName}: ${error.message}`,
      );
      throw error;
    }
  }
  private async handleMetadataUpdates(
    collectionName: string,
    oldMetadata: any,
    newMetadata: any,
  ): Promise<void> {
    const columnRenames: Map<string, string> = new Map();
    const propertyNameRenames: Map<string, string> = new Map();
    const oldColMap = new Map<number, any>(
      (oldMetadata.columns || []).map((c: any) => [c.id, c]),
    );
    const newColMap = new Map<number, any>(
      (newMetadata.columns || []).map((c: any) => [c.id, c]),
    );
    for (const [colId, newCol] of newColMap) {
      const oldCol = oldColMap.get(colId as number);
      if (oldCol && oldCol.name !== newCol.name) {
        columnRenames.set(oldCol.name, newCol.name);
      }
    }
    const oldRelMap = new Map<number, any>(
      (oldMetadata.relations || []).map((r: any) => [r.id, r]),
    );
    const newRelMap = new Map<number, any>(
      (newMetadata.relations || []).map((r: any) => [r.id, r]),
    );
    for (const [relId, newRel] of newRelMap) {
      const oldRel = oldRelMap.get(relId as number);
      if (oldRel && oldRel.propertyName !== newRel.propertyName) {
        propertyNameRenames.set(oldRel.propertyName, newRel.propertyName);
      }
    }
    if (columnRenames.size > 0 || propertyNameRenames.size > 0) {
      let updatedUniques = this.schemaDiffService.updateConstraintColumns(
        oldMetadata.uniques || [],
        columnRenames,
      );
      updatedUniques = this.schemaDiffService.updateConstraintColumns(
        updatedUniques,
        propertyNameRenames,
      );
      let updatedIndexes = this.schemaDiffService.updateConstraintColumns(
        oldMetadata.indexes || [],
        columnRenames,
      );
      updatedIndexes = this.schemaDiffService.updateConstraintColumns(
        updatedIndexes,
        propertyNameRenames,
      );
      const metadataUpdate: any = {};
      if (
        JSON.stringify(updatedUniques) !==
        JSON.stringify(oldMetadata.uniques || [])
      ) {
        metadataUpdate.uniques = updatedUniques;
      }
      if (
        JSON.stringify(updatedIndexes) !==
        JSON.stringify(oldMetadata.indexes || [])
      ) {
        metadataUpdate.indexes = updatedIndexes;
      }
      if (Object.keys(metadataUpdate).length > 0) {
        await this.persistMetadataUpdates(collectionName, metadataUpdate);
      }
    }
  }
  private async persistMetadataUpdates(
    collectionName: string,
    updates: any,
  ): Promise<void> {
    try {
      const updateData: any = {};
      if (updates.uniques !== undefined) {
        updateData.uniques = updates.uniques;
      }
      if (updates.indexes !== undefined) {
        updateData.indexes = updates.indexes;
      }
      if (Object.keys(updateData).length === 0) return;
      await this.queryBuilderService.update(
        'table_definition',
        { where: [{ field: 'name', operator: '=', value: collectionName }] },
        updateData,
      );
    } catch (error) {
      this.logger.error(
        `  Failed to update metadata for ${collectionName}: ${error.message}`,
      );
    }
  }
  async dropCollection(collectionName: string): Promise<void> {
    const db = this.mongoService.getDb();
    try {
      const collections = await db
        .listCollections({ name: collectionName })
        .toArray();
      if (collections.length === 0) {
        this.logger.warn(
          ` Collection ${collectionName} does not exist, skipping drop`,
        );
        return;
      }
      await db.collection(collectionName).drop();
    } catch (error) {
      this.logger.error(
        `Failed to drop collection ${collectionName}: ${error.message}`,
      );
      throw error;
    }
  }
  async ensureJunctionCollection(
    junctionName: string,
    sourceColumn: string,
    targetColumn: string,
  ): Promise<void> {
    return this.schemaDiffService.ensureJunctionCollection(
      junctionName,
      sourceColumn,
      targetColumn,
    );
  }
  async dropJunctionCollection(junctionName: string): Promise<void> {
    return this.schemaDiffService.dropJunctionCollection(junctionName);
  }
  async renameJunctionCollection(
    oldName: string,
    newName: string,
  ): Promise<void> {
    return this.schemaDiffService.renameJunctionCollection(oldName, newName);
  }
  private async createIndexes(
    collectionName: string,
    columns: any[],
    uniques: any[] = [],
    indexes: any[] = [],
    relations: any[] = [],
  ): Promise<string[][]> {
    const db = this.mongoService.getDb();
    const collection = db.collection(collectionName);
    const autoGeneratedIndexes: string[][] = [];
    const indexedFields = new Set<string>();
    for (const index of indexes) {
      for (const field of index) {
        indexedFields.add(field);
      }
    }
    try {
      for (const col of columns) {
        if (col.name === '_id') {
          continue;
        }
        if (col.isPrimary || col.name === 'id') {
          await collection.createIndex(
            { [col.name]: 1 },
            {
              unique: true,
              name: `${collectionName}_${col.name}_unique`,
            },
          );
        }
      }
      for (const unique of uniques) {
        const indexSpec: any = {};
        for (const field of unique) {
          indexSpec[field] = 1;
        }
        await collection.createIndex(indexSpec, {
          unique: true,
          name: `${collectionName}_${unique.join('_')}_unique`,
          partialFilterExpression: this.createPartialFilterForUnique(unique),
        });
        if (unique.length > 0) {
          indexedFields.add(unique[0]);
        }
      }
      for (const index of indexes) {
        const indexSpec: any = {};
        for (const field of index) {
          indexSpec[field] = 1;
        }
        await collection.createIndex(indexSpec, {
          name: `${collectionName}_${index.join('_')}_idx`,
        });
      }
      for (const relation of relations) {
        if (relation.type === 'many-to-one' || relation.type === 'one-to-one') {
          const fieldName = relation.propertyName;
          if (!indexedFields.has(fieldName)) {
            await collection.createIndex(
              { [fieldName]: 1 },
              { name: `${collectionName}_${fieldName}_fk_idx` },
            );
            autoGeneratedIndexes.push([fieldName]);
            indexedFields.add(fieldName);
          }
        }
      }
      if (!indexedFields.has('createdAt')) {
        await collection.createIndex(
          { createdAt: -1 },
          { name: `${collectionName}_createdAt_idx` },
        );
        autoGeneratedIndexes.push(['createdAt']);
        indexedFields.add('createdAt');
      }
      if (!indexedFields.has('updatedAt')) {
        await collection.createIndex(
          { updatedAt: -1 },
          { name: `${collectionName}_updatedAt_idx` },
        );
        autoGeneratedIndexes.push(['updatedAt']);
        indexedFields.add('updatedAt');
      }
      const timestampFields = columns.filter(
        (col) =>
          col.type === 'datetime' ||
          col.type === 'timestamp' ||
          col.type === 'date',
      );
      for (const field of timestampFields) {
        if (!indexedFields.has(field.name)) {
          await collection.createIndex(
            { [field.name]: -1 },
            { name: `${collectionName}_${field.name}_idx` },
          );
          autoGeneratedIndexes.push([field.name]);
          indexedFields.add(field.name);
        }
      }
    } catch (error) {
      this.logger.warn(
        `Failed to create some indexes for ${collectionName}: ${error.message}`,
      );
    }
    return autoGeneratedIndexes;
  }
  async restoreMetadataFromRawSnapshot(entry: any): Promise<void> {
    const snapshot = entry.rawBeforeSnapshot;
    if (!snapshot || !snapshot.table) {
      this.logger.warn(
        `No rawBeforeSnapshot in journal ${entry.uuid}, skipping metadata restore`,
      );
      return;
    }
    const db = this.mongoService.getDb();
    const tableId = snapshot.table._id;
    const oid = typeof tableId === 'string' ? new ObjectId(tableId) : tableId;
    this.logger.warn(
      `Restoring metadata from raw snapshot for table ${snapshot.table.name} (${oid})`,
    );
    await db
      .collection('table_definition')
      .replaceOne({ _id: oid }, snapshot.table, { upsert: true });
    await db.collection('column_definition').deleteMany({ table: oid });
    if (snapshot.columns && snapshot.columns.length > 0) {
      await db.collection('column_definition').insertMany(snapshot.columns);
    }
    await db.collection('relation_definition').deleteMany({ sourceTable: oid });
    if (snapshot.relations && snapshot.relations.length > 0) {
      await db.collection('relation_definition').insertMany(snapshot.relations);
    }
    const currentSourceRels = await db
      .collection('relation_definition')
      .find({ sourceTable: oid })
      .toArray();
    const owningRelIds = currentSourceRels
      .filter((r: any) => !r.mappedBy)
      .map((r: any) => r._id);
    if (owningRelIds.length > 0) {
      const currentInverse = await db
        .collection('relation_definition')
        .find({ mappedBy: { $in: owningRelIds } })
        .toArray();
      const snapshotInverseIds = new Set<string>(
        (snapshot.inverseRelations || []).map((r: any) => String(r._id)),
      );
      for (const inv of currentInverse) {
        if (!snapshotInverseIds.has(String(inv._id))) {
          await db
            .collection('relation_definition')
            .deleteOne({ _id: inv._id });
        }
      }
    }
    for (const invRel of snapshot.inverseRelations || []) {
      const exists = await db
        .collection('relation_definition')
        .findOne({ _id: invRel._id });
      if (!exists) {
        await db.collection('relation_definition').insertOne(invRel);
      }
    }
    this.logger.warn(
      `Metadata restore completed for table ${snapshot.table.name}`,
    );
  }
}
