import { Injectable, Logger } from '@nestjs/common';
import { MongoService } from './mongo.service';
import { QueryBuilderService } from '../../query-builder/query-builder.service';

@Injectable()
export class MongoSchemaDiffService {
  private readonly logger = new Logger(MongoSchemaDiffService.name);

  constructor(
    private readonly mongoService: MongoService,
    private readonly queryBuilderService: QueryBuilderService,
  ) {}

  private sqlTypeToBsonType(type: string): any {
    const typeMap: Record<string, any> = {
      string: 'string',
      text: 'string',
      varchar: 'string',
      char: 'string',
      uuid: 'string',
      richtext: 'string',
      int: 'int',
      integer: 'int',
      smallint: 'int',
      tinyint: 'int',
      bigint: 'long',
      float: 'double',
      double: 'double',
      decimal: 'double',
      numeric: 'double',
      real: 'double',
      boolean: 'bool',
      bool: 'bool',
      date: 'date',
      datetime: 'date',
      timestamp: 'date',
      json: 'object',
      'simple-json': 'object',
      array: 'array',
      enum: 'string',
    };
    return typeMap[type] || 'string';
  }

  private createValidationSchema(columns: any[]): any {
    const properties: any = {};
    const required: string[] = [];
    for (const col of columns) {
      if (
        col.name === '_id' ||
        col.name === 'createdAt' ||
        col.name === 'updatedAt'
      ) {
        continue;
      }
      const bsonType = this.sqlTypeToBsonType(col.type);
      properties[col.name] = {
        bsonType: col.isNullable ? [bsonType, 'null'] : bsonType,
        description: col.description || col.name,
      };
      if (!col.isNullable && !col.defaultValue && !col.isGenerated) {
        required.push(col.name);
      }
    }
    const schema: any = {
      bsonType: 'object',
      properties,
    };
    if (required.length > 0) {
      schema.required = required;
    }
    return schema;
  }

  private createPartialFilterForUnique(fields: string[]): any {
    const filter: any = {};
    for (const field of fields) {
      filter[field] = { $exists: true, $ne: null };
    }
    return filter;
  }

  indexKey(index: string[]): string {
    return [...index].sort().join(',');
  }

  async updateMetadataIndexes(
    collectionName: string,
    userDefinedIndexes: string[][],
    autoGeneratedIndexes: string[][],
  ): Promise<void> {
    if (autoGeneratedIndexes.length === 0) return;

    const existingIndexKeys = new Set(
      userDefinedIndexes.map((idx) => this.indexKey(idx)),
    );

    const newIndexes: string[][] = [];
    for (const autoIdx of autoGeneratedIndexes) {
      if (!existingIndexKeys.has(this.indexKey(autoIdx))) {
        newIndexes.push(autoIdx);
      }
    }

    if (newIndexes.length === 0) return;

    const mergedIndexes = [...userDefinedIndexes, ...newIndexes];

    try {
      await this.queryBuilderService.update(
        'table_definition',
        { where: [{ field: 'name', operator: '=', value: collectionName }] },
        { indexes: mergedIndexes },
      );
    } catch (error) {
      this.logger.error(
        `  Failed to update indexes metadata for ${collectionName}: ${error.message}`,
      );
    }
  }

  updateConstraintColumns(
    constraints: any[],
    renames: Map<string, string>,
  ): any[] {
    if (!constraints || constraints.length === 0 || renames.size === 0)
      return constraints;

    return constraints.map((constraint) => {
      if (Array.isArray(constraint)) {
        return constraint.map((col) => renames.get(col) || col);
      }
      return constraint;
    });
  }

  buildFullIndexSpecs(
    collectionName: string,
    columns: any[],
    uniques: any[] = [],
    indexes: any[] = [],
    relations: any[] = [],
  ): { keys: Record<string, number>; options: any; name: string }[] {
    const specs: {
      keys: Record<string, number>;
      options: any;
      name: string;
    }[] = [];
    const indexedFields = new Set<string>();

    for (const index of indexes) {
      for (const field of index) {
        indexedFields.add(field);
      }
    }

    for (const col of columns) {
      if (col.name === '_id') continue;
      if (col.isPrimary || col.name === 'id') {
        specs.push({
          keys: { [col.name]: 1 },
          options: {
            unique: true,
            name: `${collectionName}_${col.name}_unique`,
          },
          name: `${collectionName}_${col.name}_unique`,
        });
      }
    }

    for (const unique of uniques) {
      const indexSpec: Record<string, number> = {};
      for (const field of unique) {
        indexSpec[field] = 1;
      }
      specs.push({
        keys: indexSpec,
        options: {
          unique: true,
          name: `${collectionName}_${unique.join('_')}_unique`,
          partialFilterExpression: this.createPartialFilterForUnique(unique),
        },
        name: `${collectionName}_${unique.join('_')}_unique`,
      });
      if (unique.length > 0) indexedFields.add(unique[0]);
    }

    for (const index of indexes) {
      const indexSpec: Record<string, number> = {};
      for (const field of index) {
        indexSpec[field] = 1;
      }
      specs.push({
        keys: indexSpec,
        options: { name: `${collectionName}_${index.join('_')}_idx` },
        name: `${collectionName}_${index.join('_')}_idx`,
      });
    }

    for (const relation of relations) {
      if (relation.type === 'many-to-one' || relation.type === 'one-to-one') {
        const fieldName = relation.propertyName;
        if (!indexedFields.has(fieldName)) {
          specs.push({
            keys: { [fieldName]: 1 },
            options: { name: `${collectionName}_${fieldName}_fk_idx` },
            name: `${collectionName}_${fieldName}_fk_idx`,
          });
          indexedFields.add(fieldName);
        }
      }
    }

    if (!indexedFields.has('createdAt')) {
      specs.push({
        keys: { createdAt: -1 },
        options: { name: `${collectionName}_createdAt_idx` },
        name: `${collectionName}_createdAt_idx`,
      });
    }
    if (!indexedFields.has('updatedAt')) {
      specs.push({
        keys: { updatedAt: -1 },
        options: { name: `${collectionName}_updatedAt_idx` },
        name: `${collectionName}_updatedAt_idx`,
      });
    }

    const timestampFields = columns.filter(
      (col) =>
        col.type === 'datetime' ||
        col.type === 'timestamp' ||
        col.type === 'date',
    );
    for (const field of timestampFields) {
      if (!indexedFields.has(field.name)) {
        specs.push({
          keys: { [field.name]: -1 },
          options: { name: `${collectionName}_${field.name}_idx` },
          name: `${collectionName}_${field.name}_idx`,
        });
        indexedFields.add(field.name);
      }
    }

    return specs;
  }

  analyzeMongoColumnChanges(
    oldColumns: any[],
    newColumns: any[],
  ): {
    create: any[];
    delete: any[];
    rename: { oldName: string; newName: string; column: any }[];
    update: { oldColumn: any; newColumn: any }[];
  } {
    const result = {
      create: [] as any[],
      delete: [] as any[],
      rename: [] as { oldName: string; newName: string; column: any }[],
      update: [] as { oldColumn: any; newColumn: any }[],
    };

    const oldColMap = new Map(
      oldColumns.filter((c) => c.id != null).map((c) => [c.id, c]),
    );
    const newColMap = new Map(
      newColumns.filter((c) => c.id != null).map((c) => [c.id, c]),
    );
    const oldColNameMap = new Map(oldColumns.map((c) => [c.name, c]));

    for (const newCol of newColumns) {
      if (newCol.id == null) {
        if (!oldColNameMap.has(newCol.name)) {
          result.create.push(newCol);
        }
        continue;
      }
      const oldCol = oldColMap.get(newCol.id);
      if (!oldCol) {
        if (oldColNameMap.has(newCol.name)) continue;
        result.create.push(newCol);
      }
    }

    for (const oldCol of oldColumns) {
      if (oldCol.id == null) continue;
      const newCol = newColMap.get(oldCol.id);
      if (!newCol) {
        if (['id', 'createdAt', 'updatedAt', '_id'].includes(oldCol.name)) {
        } else {
          result.delete.push(oldCol);
        }
      } else {
        if (oldCol.name !== newCol.name) {
          result.rename.push({
            oldName: oldCol.name,
            newName: newCol.name,
            column: newCol,
          });
        } else if (this.hasMongoColumnChanged(oldCol, newCol)) {
          result.update.push({ oldColumn: oldCol, newColumn: newCol });
        }
      }
    }

    return result;
  }

  hasMongoColumnChanged(oldCol: any, newCol: any): boolean {
    return (
      oldCol.type !== newCol.type ||
      oldCol.isNullable !== newCol.isNullable ||
      oldCol.isGenerated !== newCol.isGenerated ||
      JSON.stringify(oldCol.defaultValue) !==
        JSON.stringify(newCol.defaultValue)
    );
  }

  analyzeMongoIndexChanges(
    oldMetadata: any,
    newMetadata: any,
  ): {
    create: { keys: Record<string, number>; options: any; name: string }[];
    delete: string[];
    unchanged: string[];
  } {
    const oldSpecs = this.buildFullIndexSpecs(
      oldMetadata.name,
      oldMetadata.columns || [],
      oldMetadata.uniques || [],
      oldMetadata.indexes || [],
      oldMetadata.relations || [],
    );
    const newSpecs = this.buildFullIndexSpecs(
      newMetadata.name,
      newMetadata.columns || [],
      newMetadata.uniques || [],
      newMetadata.indexes || [],
      newMetadata.relations || [],
    );

    const oldIndexNames = new Map(oldSpecs.map((s) => [s.name, s]));
    const newIndexNames = new Map(newSpecs.map((s) => [s.name, s]));

    const toCreate = newSpecs.filter((s) => !oldIndexNames.has(s.name));
    const toDelete = oldSpecs
      .filter((s) => !newIndexNames.has(s.name))
      .map((s) => s.name);
    const unchanged = newSpecs
      .filter((s) => oldIndexNames.has(s.name))
      .map((s) => s.name);

    return { create: toCreate, delete: toDelete, unchanged };
  }

  generateMongoSchemaDiff(
    oldMetadata: any,
    newMetadata: any,
  ): {
    columns: {
      create: any[];
      delete: any[];
      rename: { oldName: string; newName: string; column: any }[];
      update: { oldColumn: any; newColumn: any }[];
    };
    validation: { changed: boolean; newSchema: any };
    indexes: {
      create: { keys: Record<string, number>; options: any; name: string }[];
      delete: string[];
      unchanged: string[];
    };
    junctionCollections: {
      create: { name: string; sourceColumn: string; targetColumn: string }[];
      drop: string[];
      rename: { oldName: string; newName: string }[];
    };
  } {
    const columnDiff = this.analyzeMongoColumnChanges(
      oldMetadata.columns || [],
      newMetadata.columns || [],
    );

    const oldSchema = this.createValidationSchema(oldMetadata.columns || []);
    const newSchema = this.createValidationSchema(newMetadata.columns || []);
    const validationChanged =
      JSON.stringify(oldSchema) !== JSON.stringify(newSchema);

    const indexDiff = this.analyzeMongoIndexChanges(oldMetadata, newMetadata);

    const junctionDiff = {
      create: [] as {
        name: string;
        sourceColumn: string;
        targetColumn: string;
      }[],
      drop: [] as string[],
      rename: [] as { oldName: string; newName: string }[],
    };

    const oldM2m = new Map<string, any>(
      (oldMetadata.relations || [])
        .filter((r: any) => r.type === 'many-to-many' && r.junctionTableName)
        .map((r: any) => [r.junctionTableName, r] as [string, any]),
    );
    const newM2m = new Map<string, any>(
      (newMetadata.relations || [])
        .filter((r: any) => r.type === 'many-to-many' && r.junctionTableName)
        .map((r: any) => [r.junctionTableName, r] as [string, any]),
    );

    for (const [name, rel] of newM2m) {
      if (!oldM2m.has(name)) {
        const oldRel = (oldMetadata.relations || []).find(
          (r: any) => r.id === rel.id && r.type === 'many-to-many',
        );
        if (oldRel?.junctionTableName && oldRel.junctionTableName !== name) {
          junctionDiff.rename.push({
            oldName: oldRel.junctionTableName,
            newName: name,
          });
        } else {
          junctionDiff.create.push({
            name,
            sourceColumn: rel.junctionSourceColumn,
            targetColumn: rel.junctionTargetColumn,
          });
        }
      }
    }
    for (const [name] of oldM2m) {
      if (!newM2m.has(name)) {
        const alreadyRenamed = junctionDiff.rename.some(
          (r) => r.oldName === name,
        );
        if (!alreadyRenamed) {
          junctionDiff.drop.push(name);
        }
      }
    }

    return {
      columns: columnDiff,
      validation: { changed: validationChanged, newSchema },
      indexes: indexDiff,
      junctionCollections: junctionDiff,
    };
  }

  async executeMongoSchemaDiff(
    collectionName: string,
    diff: ReturnType<typeof this.generateMongoSchemaDiff>,
    oldMetadata: any,
    newMetadata: any,
  ): Promise<void> {
    const db = this.mongoService.getDb();

    for (const { oldName, newName } of diff.junctionCollections.rename) {
      this.logger.log(`Renaming junction collection: ${oldName} → ${newName}`);
      await this.renameJunctionCollection(oldName, newName);
    }

    for (const name of diff.junctionCollections.drop) {
      this.logger.log(`Dropping junction collection: ${name}`);
      await this.dropJunctionCollection(name);
    }

    for (const { name, sourceColumn, targetColumn } of diff.junctionCollections
      .create) {
      this.logger.log(`Creating junction collection: ${name}`);
      await this.ensureJunctionCollection(name, sourceColumn, targetColumn);
    }

    if (diff.columns.rename.length > 0) {
      this.logger.log(
        `Renaming fields in ${collectionName}: ${diff.columns.rename.map((r) => `${r.oldName}→${r.newName}`).join(', ')}`,
      );
      await this.renameFieldsInDocuments(collectionName, diff.columns.rename);
    }

    if (diff.indexes.delete.length > 0) {
      const collection = db.collection(collectionName);
      for (const indexName of diff.indexes.delete) {
        this.logger.log(`Dropping index: ${indexName}`);
        try {
          await collection.dropIndex(indexName);
        } catch (error: any) {
          this.logger.warn(
            `Failed to drop index ${indexName}: ${error.message}`,
          );
        }
      }
    }

    if (
      diff.validation.changed ||
      diff.columns.create.length > 0 ||
      diff.columns.delete.length > 0 ||
      diff.columns.update.length > 0
    ) {
      this.logger.log(`Updating validation schema for ${collectionName}`);
      try {
        await db.command({
          collMod: collectionName,
          validator: { $jsonSchema: diff.validation.newSchema },
          validationLevel: 'moderate',
          validationAction: 'error',
        });
      } catch (error: any) {
        this.logger.warn(
          `Failed to update validation for ${collectionName}: ${error.message}`,
        );
      }
    }

    if (diff.indexes.create.length > 0) {
      const collection = db.collection(collectionName);
      for (const spec of diff.indexes.create) {
        this.logger.log(`Creating index: ${spec.name}`);
        try {
          await collection.createIndex(spec.keys, spec.options);
        } catch (error: any) {
          this.logger.warn(
            `Failed to create index ${spec.name}: ${error.message}`,
          );
        }
      }
    }

    const autoGeneratedIndexNames = diff.indexes.create.map((s) => {
      const keyArr = Object.keys(s.keys);
      return keyArr;
    });
    if (autoGeneratedIndexNames.length > 0) {
      await this.updateMetadataIndexes(
        collectionName,
        newMetadata.indexes || [],
        autoGeneratedIndexNames,
      );
    }
  }

  async renameFieldsInDocuments(
    collectionName: string,
    renames: { oldName: string; newName: string }[],
  ): Promise<void> {
    if (renames.length === 0) return;
    const collection = this.mongoService.getDb().collection(collectionName);
    const renameMap: Record<string, string> = {};
    for (const { oldName, newName } of renames) {
      renameMap[oldName] = newName;
    }
    try {
      await collection.updateMany({}, { $rename: renameMap });
    } catch (error: any) {
      this.logger.warn(
        `Failed to rename fields in ${collectionName}: ${error.message}`,
      );
    }
  }

  async renameJunctionCollection(
    oldName: string,
    newName: string,
  ): Promise<void> {
    const db = this.mongoService.getDb();
    const existing = await db.listCollections({ name: oldName }).toArray();
    if (existing.length > 0) {
      await db.collection(oldName).rename(newName);
    }
  }

  async dropJunctionCollection(junctionName: string): Promise<void> {
    const db = this.mongoService.getDb();
    try {
      const existing = await db
        .listCollections({ name: junctionName })
        .toArray();
      if (existing.length === 0) return;
      await db.collection(junctionName).drop();
    } catch (error: any) {
      this.logger.warn(
        `Failed to drop junction collection ${junctionName}: ${error.message}`,
      );
    }
  }

  async ensureJunctionCollection(
    junctionName: string,
    sourceColumn: string,
    targetColumn: string,
  ): Promise<void> {
    const db = this.mongoService.getDb();
    const existing = await db.listCollections({ name: junctionName }).toArray();
    if (existing.length === 0) {
      try {
        await db.createCollection(junctionName);
      } catch (error: any) {
        const nowExisting = await db
          .listCollections({ name: junctionName })
          .toArray();
        if (nowExisting.length === 0) throw error;
      }
    }

    const collection = db.collection(junctionName);

    try {
      await collection.createIndex(
        { [sourceColumn]: 1, [targetColumn]: 1 },
        { unique: true, name: `${junctionName}_src_tgt_uq` },
      );
    } catch (error: any) {
      if (error.code !== 85 && error.code !== 86) throw error;
    }

    try {
      await collection.createIndex(
        { [targetColumn]: 1 },
        { name: `${junctionName}_tgt_idx` },
      );
    } catch (error: any) {
      if (error.code !== 85 && error.code !== 86) throw error;
    }
  }
}
