import { Injectable, Logger, Inject, forwardRef } from '@nestjs/common';
import { MongoService } from './mongo.service';
import { MetadataCacheService } from '../../cache/services/metadata-cache.service';
import { QueryBuilderService } from '../../query-builder/query-builder.service';
type BsonType = 'string' | 'int' | 'long' | 'double' | 'bool' | 'date' | 'objectId' | 'object' | 'array';
@Injectable()
export class MongoSchemaMigrationService {
  private readonly logger = new Logger(MongoSchemaMigrationService.name);
  constructor(
    private readonly mongoService: MongoService,
    @Inject(forwardRef(() => MetadataCacheService))
    private readonly metadataCacheService: MetadataCacheService,
    @Inject(forwardRef(() => QueryBuilderService))
    private readonly queryBuilderService: QueryBuilderService,
  ) {}
  private sqlTypeToBsonType(type: string): BsonType {
    const typeMap: Record<string, BsonType> = {
      'string': 'string',
      'text': 'string',
      'varchar': 'string',
      'char': 'string',
      'uuid': 'string',
      'richtext': 'string',
      'int': 'int',
      'integer': 'int',
      'smallint': 'int',
      'tinyint': 'int',
      'bigint': 'long',
      'float': 'double',
      'double': 'double',
      'decimal': 'double',
      'numeric': 'double',
      'real': 'double',
      'boolean': 'bool',
      'bool': 'bool',
      'date': 'date',
      'datetime': 'date',
      'timestamp': 'date',
      'json': 'object',
      'simple-json': 'object',
      'array': 'array',
      'enum': 'string',
    };
    return typeMap[type] || 'string';
  }
  private createValidationSchema(columns: any[]): any {
    const properties: any = {};
    const required: string[] = [];
    for (const col of columns) {
      if (col.name === '_id' || col.name === 'createdAt' || col.name === 'updatedAt') {
        continue;
      }
      const bsonType = this.sqlTypeToBsonType(col.type);
      properties[col.name] = {
        bsonType: col.isNullable ? [bsonType, 'null'] : bsonType,
        description: col.description || col.name,
      };
      if (!col.isNullable && !col.defaultValue && !col.isGenerated) {
        required.push(col.name);
      }
    }
    const schema: any = {
      bsonType: 'object',
      properties,
    };
    if (required.length > 0) {
      schema.required = required;
    }
    return schema;
  }
  private createPartialFilterForUnique(fields: string[]): any {
    const filter: any = {};
    for (const field of fields) {
      filter[field] = { $exists: true, $ne: null };
    }
    return filter;
  }
  async createCollection(tableMetadata: any): Promise<void> {
    const db = this.mongoService.getDb();
    const collectionName = tableMetadata.name;
    try {
      const collections = await db.listCollections({ name: collectionName }).toArray();
      if (collections.length > 0) {
        this.logger.warn(` Collection ${collectionName} already exists, skipping creation`);
        return;
      }
      this.logger.log(`Creating collection: ${collectionName}`);
      const validationSchema = this.createValidationSchema(tableMetadata.columns || []);
      await db.createCollection(collectionName, {
        validator: { $jsonSchema: validationSchema },
        validationLevel: 'moderate',
        validationAction: 'error',
      });
      this.logger.log(`Created collection with validation: ${collectionName}`);
      const autoGeneratedIndexes = await this.createIndexes(
        collectionName,
        tableMetadata.columns || [],
        tableMetadata.uniques || [],
        tableMetadata.indexes || [],
        tableMetadata.relations || []
      );
      await this.updateMetadataIndexes(
        collectionName,
        tableMetadata.indexes || [],
        autoGeneratedIndexes
      );
      this.logger.log(`Collection creation complete: ${collectionName}`);
    } catch (error) {
      this.logger.error(`Failed to create collection ${collectionName}: ${error.message}`);
      throw error;
    }
  }
  async updateCollection(
    collectionName: string,
    oldMetadata: any,
    newMetadata: any,
  ): Promise<void> {
    const db = this.mongoService.getDb();
    try {
      this.logger.log(`🔧 Updating collection: ${collectionName}`);
      const validationSchema = this.createValidationSchema(newMetadata.columns || []);
      await db.command({
        collMod: collectionName,
        validator: { $jsonSchema: validationSchema },
        validationLevel: 'moderate',
        validationAction: 'error',
      });
      this.logger.log(`Updated validation schema for: ${collectionName}`);
      const collection = db.collection(collectionName);
      try {
        await collection.dropIndexes();
        this.logger.log(` Dropped all indexes for ${collectionName}`);
      } catch (error) {
        this.logger.warn(`Failed to drop indexes: ${error.message}`);
      }

      // Detect column/propertyName renames and update metadata
      await this.handleMetadataUpdates(collectionName, oldMetadata, newMetadata);

      const autoGeneratedIndexes = await this.createIndexes(
        collectionName,
        newMetadata.columns || [],
        newMetadata.uniques || [],
        newMetadata.indexes || [],
        newMetadata.relations || []
      );
      await this.updateMetadataIndexes(
        collectionName,
        newMetadata.indexes || [],
        autoGeneratedIndexes
      );
      this.logger.log(`Collection update complete: ${collectionName}`);
    } catch (error) {
      this.logger.error(`Failed to update collection ${collectionName}: ${error.message}`);
      throw error;
    }
  }

  private async handleMetadataUpdates(
    collectionName: string,
    oldMetadata: any,
    newMetadata: any,
  ): Promise<void> {
    const columnRenames: Map<string, string> = new Map();
    const propertyNameRenames: Map<string, string> = new Map();

    // Detect column renames
    const oldColMap = new Map<number, any>((oldMetadata.columns || []).map((c: any) => [c.id, c]));
    const newColMap = new Map<number, any>((newMetadata.columns || []).map((c: any) => [c.id, c]));

    for (const [colId, newCol] of newColMap) {
      const oldCol = oldColMap.get(colId as number);
      if (oldCol && oldCol.name !== newCol.name) {
        columnRenames.set(oldCol.name, newCol.name);
        this.logger.log(`  Detected column rename: ${oldCol.name} → ${newCol.name}`);
      }
    }

    // Detect relation propertyName renames
    const oldRelMap = new Map<number, any>((oldMetadata.relations || []).map((r: any) => [r.id, r]));
    const newRelMap = new Map<number, any>((newMetadata.relations || []).map((r: any) => [r.id, r]));

    for (const [relId, newRel] of newRelMap) {
      const oldRel = oldRelMap.get(relId as number);
      if (oldRel && oldRel.propertyName !== newRel.propertyName) {
        propertyNameRenames.set(oldRel.propertyName, newRel.propertyName);
        this.logger.log(`  Detected relation propertyName rename: ${oldRel.propertyName} → ${newRel.propertyName}`);
      }
    }

    // Update uniques and indexes if there are renames
    if (columnRenames.size > 0 || propertyNameRenames.size > 0) {
      let updatedUniques = this.updateConstraintColumns(oldMetadata.uniques || [], columnRenames);
      updatedUniques = this.updateConstraintColumns(updatedUniques, propertyNameRenames);

      let updatedIndexes = this.updateConstraintColumns(oldMetadata.indexes || [], columnRenames);
      updatedIndexes = this.updateConstraintColumns(updatedIndexes, propertyNameRenames);

      const metadataUpdate: any = {};
      if (JSON.stringify(updatedUniques) !== JSON.stringify(oldMetadata.uniques || [])) {
        metadataUpdate.uniques = updatedUniques;
        this.logger.log(`  🔧 Uniques updated: ${JSON.stringify(oldMetadata.uniques)} → ${JSON.stringify(updatedUniques)}`);
      }
      if (JSON.stringify(updatedIndexes) !== JSON.stringify(oldMetadata.indexes || [])) {
        metadataUpdate.indexes = updatedIndexes;
        this.logger.log(`  🔧 Indexes updated: ${JSON.stringify(oldMetadata.indexes)} → ${JSON.stringify(updatedIndexes)}`);
      }

      if (Object.keys(metadataUpdate).length > 0) {
        await this.persistMetadataUpdates(collectionName, metadataUpdate);
      }
    }
  }

  private updateConstraintColumns(constraints: any[], renames: Map<string, string>): any[] {
    if (!constraints || constraints.length === 0 || renames.size === 0) return constraints;

    return constraints.map(constraint => {
      if (Array.isArray(constraint)) {
        return constraint.map(col => renames.get(col) || col);
      }
      return constraint;
    });
  }

  private async persistMetadataUpdates(collectionName: string, updates: any): Promise<void> {
    try {
      const updateData: any = {};
      if (updates.uniques !== undefined) {
        updateData.uniques = JSON.stringify(updates.uniques);
      }
      if (updates.indexes !== undefined) {
        updateData.indexes = JSON.stringify(updates.indexes);
      }

      if (Object.keys(updateData).length === 0) return;

      await this.queryBuilderService.update({
        table: 'table_definition',
        where: [{ field: 'name', operator: '=', value: collectionName }],
        data: updateData,
      });

      this.logger.log(`  ✅ Updated metadata fields for ${collectionName}: ${Object.keys(updateData).join(', ')}`);

      await this.metadataCacheService.reload();
    } catch (error) {
      this.logger.error(`  Failed to update metadata for ${collectionName}: ${error.message}`);
    }
  }

  private indexKey(index: string[]): string {
    return [...index].sort().join(',');
  }

  private async updateMetadataIndexes(
    collectionName: string,
    userDefinedIndexes: string[][],
    autoGeneratedIndexes: string[][],
  ): Promise<void> {
    if (autoGeneratedIndexes.length === 0) return;

    const existingIndexKeys = new Set(
      userDefinedIndexes.map(idx => this.indexKey(idx))
    );

    const newIndexes: string[][] = [];
    for (const autoIdx of autoGeneratedIndexes) {
      if (!existingIndexKeys.has(this.indexKey(autoIdx))) {
        newIndexes.push(autoIdx);
      }
    }

    if (newIndexes.length === 0) return;

    const mergedIndexes = [...userDefinedIndexes, ...newIndexes];

    try {
      await this.queryBuilderService.update({
        table: 'table_definition',
        where: [{ field: 'name', operator: '=', value: collectionName }],
        data: { indexes: JSON.stringify(mergedIndexes) },
      });

      this.logger.log(`  📝 Updated indexes metadata for ${collectionName}: added ${newIndexes.length} auto-generated indexes`);
      await this.metadataCacheService.reload();
    } catch (error) {
      this.logger.error(`  Failed to update indexes metadata for ${collectionName}: ${error.message}`);
    }
  }
  async dropCollection(collectionName: string): Promise<void> {
    const db = this.mongoService.getDb();
    try {
      const collections = await db.listCollections({ name: collectionName }).toArray();
      if (collections.length === 0) {
        this.logger.warn(` Collection ${collectionName} does not exist, skipping drop`);
        return;
      }
      this.logger.log(` Dropping collection: ${collectionName}`);
      await db.collection(collectionName).drop();
      this.logger.log(`Collection dropped: ${collectionName}`);
    } catch (error) {
      this.logger.error(`Failed to drop collection ${collectionName}: ${error.message}`);
      throw error;
    }
  }
  private async createIndexes(
    collectionName: string,
    columns: any[],
    uniques: any[] = [],
    indexes: any[] = [],
    relations: any[] = []
  ): Promise<string[][]> {
    const db = this.mongoService.getDb();
    const collection = db.collection(collectionName);
    const autoGeneratedIndexes: string[][] = [];
    const indexedFields = new Set<string>();

    for (const index of indexes) {
      for (const field of index) {
        indexedFields.add(field);
      }
    }

    try {
      for (const col of columns) {
        if (col.name === '_id') {
          continue;
        }
        if (col.isPrimary || col.name === 'id') {
          await collection.createIndex(
            { [col.name]: 1 },
            {
              unique: true,
              name: `${collectionName}_${col.name}_unique`,
            }
          );
          this.logger.log(`Created unique index on ${collectionName}.${col.name}`);
        }
      }
      for (const unique of uniques) {
        const indexSpec: any = {};
        for (const field of unique) {
          indexSpec[field] = 1;
        }
        await collection.createIndex(indexSpec, {
          unique: true,
          name: `${collectionName}_${unique.join('_')}_unique`,
          partialFilterExpression: this.createPartialFilterForUnique(unique),
        });
        this.logger.log(`Created unique index on ${collectionName}: ${unique.join(', ')}`);
      }
      for (const index of indexes) {
        const indexSpec: any = {};
        for (const field of index) {
          indexSpec[field] = 1;
        }
        await collection.createIndex(indexSpec, {
          name: `${collectionName}_${index.join('_')}_idx`,
        });
        this.logger.log(`Created index on ${collectionName}: ${index.join(', ')}`);
      }
      for (const relation of relations) {
        if (relation.type === 'many-to-one' || relation.type === 'one-to-one') {
          const fieldName = relation.propertyName;
          if (!indexedFields.has(fieldName)) {
            await collection.createIndex(
              { [fieldName]: 1 },
              { name: `${collectionName}_${fieldName}_fk_idx` }
            );
            autoGeneratedIndexes.push([fieldName]);
            indexedFields.add(fieldName);
            this.logger.log(`Created FK index on ${collectionName}.${fieldName}`);
          }
        }
        if (relation.type === 'many-to-many' && !relation.mappedBy) {
          const fieldName = relation.propertyName;
          if (!indexedFields.has(fieldName)) {
            await collection.createIndex(
              { [fieldName]: 1 },
              { name: `${collectionName}_${fieldName}_fk_idx` }
            );
            autoGeneratedIndexes.push([fieldName]);
            indexedFields.add(fieldName);
            this.logger.log(`Created M2M FK index on ${collectionName}.${fieldName}`);
          }
        }
      }
      if (!indexedFields.has('createdAt')) {
        await collection.createIndex(
          { createdAt: -1 },
          { name: `${collectionName}_createdAt_idx` }
        );
        autoGeneratedIndexes.push(['createdAt']);
        indexedFields.add('createdAt');
        this.logger.log(`Created timestamp index on ${collectionName}.createdAt`);
      }
      if (!indexedFields.has('updatedAt')) {
        await collection.createIndex(
          { updatedAt: -1 },
          { name: `${collectionName}_updatedAt_idx` }
        );
        autoGeneratedIndexes.push(['updatedAt']);
        indexedFields.add('updatedAt');
        this.logger.log(`Created timestamp index on ${collectionName}.updatedAt`);
      }
      const timestampFields = columns.filter(col =>
        col.type === 'datetime' || col.type === 'timestamp' || col.type === 'date'
      );
      for (const field of timestampFields) {
        if (!indexedFields.has(field.name)) {
          await collection.createIndex(
            { [field.name]: -1 },
            { name: `${collectionName}_${field.name}_idx` }
          );
          autoGeneratedIndexes.push([field.name]);
          indexedFields.add(field.name);
          this.logger.log(`Created timestamp index on ${collectionName}.${field.name}`);
        }
      }
    } catch (error) {
      this.logger.warn(`Failed to create some indexes for ${collectionName}: ${error.message}`);
    }

    return autoGeneratedIndexes;
  }
}