import { Injectable, Logger, Inject, forwardRef } from '@nestjs/common';
import { MongoService } from './mongo.service';
import { MetadataCacheService } from '../../cache/services/metadata-cache.service';
import { QueryBuilderService } from '../../query-builder/query-builder.service';
import { MongoMigrationJournalService } from './mongo-migration-journal.service';
type BsonType =
  | 'string'
  | 'int'
  | 'long'
  | 'double'
  | 'bool'
  | 'date'
  | 'objectId'
  | 'object'
  | 'array';
@Injectable()
export class MongoSchemaMigrationService {
  private readonly logger = new Logger(MongoSchemaMigrationService.name);
  constructor(
    private readonly mongoService: MongoService,
    @Inject(forwardRef(() => MetadataCacheService))
    private readonly metadataCacheService: MetadataCacheService,
    @Inject(forwardRef(() => QueryBuilderService))
    private readonly queryBuilderService: QueryBuilderService,
    @Inject(forwardRef(() => MongoMigrationJournalService))
    private readonly journalService: MongoMigrationJournalService,
  ) {}
  private sqlTypeToBsonType(type: string): BsonType {
    const typeMap: Record<string, BsonType> = {
      string: 'string',
      text: 'string',
      varchar: 'string',
      char: 'string',
      uuid: 'string',
      richtext: 'string',
      int: 'int',
      integer: 'int',
      smallint: 'int',
      tinyint: 'int',
      bigint: 'long',
      float: 'double',
      double: 'double',
      decimal: 'double',
      numeric: 'double',
      real: 'double',
      boolean: 'bool',
      bool: 'bool',
      date: 'date',
      datetime: 'date',
      timestamp: 'date',
      json: 'object',
      'simple-json': 'object',
      array: 'array',
      enum: 'string',
    };
    return typeMap[type] || 'string';
  }
  private createValidationSchema(columns: any[]): any {
    const properties: any = {};
    const required: string[] = [];
    for (const col of columns) {
      if (
        col.name === '_id' ||
        col.name === 'createdAt' ||
        col.name === 'updatedAt'
      ) {
        continue;
      }
      const bsonType = this.sqlTypeToBsonType(col.type);
      properties[col.name] = {
        bsonType: col.isNullable ? [bsonType, 'null'] : bsonType,
        description: col.description || col.name,
      };
      if (!col.isNullable && !col.defaultValue && !col.isGenerated) {
        required.push(col.name);
      }
    }
    const schema: any = {
      bsonType: 'object',
      properties,
    };
    if (required.length > 0) {
      schema.required = required;
    }
    return schema;
  }
  private createPartialFilterForUnique(fields: string[]): any {
    const filter: any = {};
    for (const field of fields) {
      filter[field] = { $exists: true, $ne: null };
    }
    return filter;
  }
  async createCollection(tableMetadata: any): Promise<void> {
    const db = this.mongoService.getDb();
    const collectionName = tableMetadata.name;
    try {
      const collections = await db
        .listCollections({ name: collectionName })
        .toArray();
      if (collections.length > 0) {
        this.logger.warn(
          ` Collection ${collectionName} already exists, skipping creation`,
        );
        return;
      }
      const validationSchema = this.createValidationSchema(
        tableMetadata.columns || [],
      );
      await db.createCollection(collectionName, {
        validator: { $jsonSchema: validationSchema },
        validationLevel: 'moderate',
        validationAction: 'error',
      });
      const autoGeneratedIndexes = await this.createIndexes(
        collectionName,
        tableMetadata.columns || [],
        tableMetadata.uniques || [],
        tableMetadata.indexes || [],
        tableMetadata.relations || [],
      );
      await this.updateMetadataIndexes(
        collectionName,
        tableMetadata.indexes || [],
        autoGeneratedIndexes,
      );
    } catch (error) {
      this.logger.error(
        `Failed to create collection ${collectionName}: ${error.message}`,
      );
      throw error;
    }
  }
  async updateCollection(
    collectionName: string,
    oldMetadata: any,
    newMetadata: any,
    rawBeforeSnapshot?: any,
  ): Promise<void> {
    try {
      const diff = this.generateMongoSchemaDiff(oldMetadata, newMetadata);
      const downDiff = this.generateMongoSchemaDiff(newMetadata, oldMetadata);
      this.logger.log(
        `Diff for ${collectionName}: ` +
          `columns(+${diff.columns.create.length}/-${diff.columns.delete.length}/~${diff.columns.update.length}/ren:${diff.columns.rename.length}), ` +
          `validation=${diff.validation.changed}, ` +
          `indexes(+${diff.indexes.create.length}/-${diff.indexes.delete.length}/=${diff.indexes.unchanged.length}), ` +
          `junctions(+${diff.junctionCollections.create.length}/-${diff.junctionCollections.drop.length}/ren:${diff.junctionCollections.rename.length})`,
      );

      // Record in journal
      let journalUuid: string | undefined;
      try {
        journalUuid = await this.journalService.record({
          tableName: collectionName,
          operation: 'update',
          upDiff: diff,
          downDiff,
          beforeSnapshot: oldMetadata,
          rawBeforeSnapshot: rawBeforeSnapshot || null,
        });
        await this.journalService.markRunning(journalUuid);
      } catch (journalErr: any) {
        this.logger.warn(`Journal record failed (non-fatal): ${journalErr.message}`);
      }

      try {
        await this.executeMongoSchemaDiff(collectionName, diff, oldMetadata, newMetadata);
        if (journalUuid) {
          await this.journalService.markCompleted(journalUuid).catch(() => {});
        }
      } catch (execError) {
        if (journalUuid) {
          this.logger.warn(`Migration failed, executing rollback for ${journalUuid}`);
          await this.journalService.executeRolldown(
            journalUuid,
            (downDiffInner) =>
              this.executeMongoSchemaDiff(collectionName, downDiffInner, newMetadata, oldMetadata),
          ).catch(() => {});
        }
        throw execError;
      }
    } catch (error) {
      this.logger.error(
        `Failed to update collection ${collectionName}: ${error.message}`,
      );
      throw error;
    }
  }

  private async handleMetadataUpdates(
    collectionName: string,
    oldMetadata: any,
    newMetadata: any,
  ): Promise<void> {
    const columnRenames: Map<string, string> = new Map();
    const propertyNameRenames: Map<string, string> = new Map();

    // Detect column renames
    const oldColMap = new Map<number, any>(
      (oldMetadata.columns || []).map((c: any) => [c.id, c]),
    );
    const newColMap = new Map<number, any>(
      (newMetadata.columns || []).map((c: any) => [c.id, c]),
    );

    for (const [colId, newCol] of newColMap) {
      const oldCol = oldColMap.get(colId as number);
      if (oldCol && oldCol.name !== newCol.name) {
        columnRenames.set(oldCol.name, newCol.name);
      }
    }

    // Detect relation propertyName renames
    const oldRelMap = new Map<number, any>(
      (oldMetadata.relations || []).map((r: any) => [r.id, r]),
    );
    const newRelMap = new Map<number, any>(
      (newMetadata.relations || []).map((r: any) => [r.id, r]),
    );

    for (const [relId, newRel] of newRelMap) {
      const oldRel = oldRelMap.get(relId as number);
      if (oldRel && oldRel.propertyName !== newRel.propertyName) {
        propertyNameRenames.set(oldRel.propertyName, newRel.propertyName);
      }
    }

    // Update uniques and indexes if there are renames
    if (columnRenames.size > 0 || propertyNameRenames.size > 0) {
      let updatedUniques = this.updateConstraintColumns(
        oldMetadata.uniques || [],
        columnRenames,
      );
      updatedUniques = this.updateConstraintColumns(
        updatedUniques,
        propertyNameRenames,
      );

      let updatedIndexes = this.updateConstraintColumns(
        oldMetadata.indexes || [],
        columnRenames,
      );
      updatedIndexes = this.updateConstraintColumns(
        updatedIndexes,
        propertyNameRenames,
      );

      const metadataUpdate: any = {};
      if (
        JSON.stringify(updatedUniques) !==
        JSON.stringify(oldMetadata.uniques || [])
      ) {
        metadataUpdate.uniques = updatedUniques;
      }
      if (
        JSON.stringify(updatedIndexes) !==
        JSON.stringify(oldMetadata.indexes || [])
      ) {
        metadataUpdate.indexes = updatedIndexes;
      }

      if (Object.keys(metadataUpdate).length > 0) {
        await this.persistMetadataUpdates(collectionName, metadataUpdate);
      }
    }
  }

  private updateConstraintColumns(
    constraints: any[],
    renames: Map<string, string>,
  ): any[] {
    if (!constraints || constraints.length === 0 || renames.size === 0)
      return constraints;

    return constraints.map((constraint) => {
      if (Array.isArray(constraint)) {
        return constraint.map((col) => renames.get(col) || col);
      }
      return constraint;
    });
  }

  private async persistMetadataUpdates(
    collectionName: string,
    updates: any,
  ): Promise<void> {
    try {
      const updateData: any = {};
      if (updates.uniques !== undefined) {
        updateData.uniques = updates.uniques;
      }
      if (updates.indexes !== undefined) {
        updateData.indexes = updates.indexes;
      }

      if (Object.keys(updateData).length === 0) return;

      await this.queryBuilderService.update('table_definition', { where: [{ field: 'name', operator: '=', value: collectionName }] }, updateData);

    } catch (error) {
      this.logger.error(
        `  Failed to update metadata for ${collectionName}: ${error.message}`,
      );
    }
  }

  private indexKey(index: string[]): string {
    return [...index].sort().join(',');
  }

  private async updateMetadataIndexes(
    collectionName: string,
    userDefinedIndexes: string[][],
    autoGeneratedIndexes: string[][],
  ): Promise<void> {
    if (autoGeneratedIndexes.length === 0) return;

    const existingIndexKeys = new Set(
      userDefinedIndexes.map((idx) => this.indexKey(idx)),
    );

    const newIndexes: string[][] = [];
    for (const autoIdx of autoGeneratedIndexes) {
      if (!existingIndexKeys.has(this.indexKey(autoIdx))) {
        newIndexes.push(autoIdx);
      }
    }

    if (newIndexes.length === 0) return;

    const mergedIndexes = [...userDefinedIndexes, ...newIndexes];

    try {
      await this.queryBuilderService.update('table_definition', { where: [{ field: 'name', operator: '=', value: collectionName }] }, { indexes: mergedIndexes });

    } catch (error) {
      this.logger.error(
        `  Failed to update indexes metadata for ${collectionName}: ${error.message}`,
      );
    }
  }
  // ─── Diff Engine ───────────────────────────────────────────────

  private buildFullIndexSpecs(
    collectionName: string,
    columns: any[],
    uniques: any[] = [],
    indexes: any[] = [],
    relations: any[] = [],
  ): { keys: Record<string, number>; options: any; name: string }[] {
    const specs: { keys: Record<string, number>; options: any; name: string }[] = [];
    const indexedFields = new Set<string>();

    for (const index of indexes) {
      for (const field of index) {
        indexedFields.add(field);
      }
    }

    for (const col of columns) {
      if (col.name === '_id') continue;
      if (col.isPrimary || col.name === 'id') {
        specs.push({
          keys: { [col.name]: 1 },
          options: { unique: true, name: `${collectionName}_${col.name}_unique` },
          name: `${collectionName}_${col.name}_unique`,
        });
      }
    }

    for (const unique of uniques) {
      const indexSpec: Record<string, number> = {};
      for (const field of unique) {
        indexSpec[field] = 1;
      }
      specs.push({
        keys: indexSpec,
        options: {
          unique: true,
          name: `${collectionName}_${unique.join('_')}_unique`,
          partialFilterExpression: this.createPartialFilterForUnique(unique),
        },
        name: `${collectionName}_${unique.join('_')}_unique`,
      });
      if (unique.length > 0) indexedFields.add(unique[0]);
    }

    for (const index of indexes) {
      const indexSpec: Record<string, number> = {};
      for (const field of index) {
        indexSpec[field] = 1;
      }
      specs.push({
        keys: indexSpec,
        options: { name: `${collectionName}_${index.join('_')}_idx` },
        name: `${collectionName}_${index.join('_')}_idx`,
      });
    }

    for (const relation of relations) {
      if (relation.type === 'many-to-one' || relation.type === 'one-to-one') {
        const fieldName = relation.propertyName;
        if (!indexedFields.has(fieldName)) {
          specs.push({
            keys: { [fieldName]: 1 },
            options: { name: `${collectionName}_${fieldName}_fk_idx` },
            name: `${collectionName}_${fieldName}_fk_idx`,
          });
          indexedFields.add(fieldName);
        }
      }
    }

    if (!indexedFields.has('createdAt')) {
      specs.push({
        keys: { createdAt: -1 },
        options: { name: `${collectionName}_createdAt_idx` },
        name: `${collectionName}_createdAt_idx`,
      });
    }
    if (!indexedFields.has('updatedAt')) {
      specs.push({
        keys: { updatedAt: -1 },
        options: { name: `${collectionName}_updatedAt_idx` },
        name: `${collectionName}_updatedAt_idx`,
      });
    }

    const timestampFields = columns.filter(
      (col) =>
        col.type === 'datetime' ||
        col.type === 'timestamp' ||
        col.type === 'date',
    );
    for (const field of timestampFields) {
      if (!indexedFields.has(field.name)) {
        specs.push({
          keys: { [field.name]: -1 },
          options: { name: `${collectionName}_${field.name}_idx` },
          name: `${collectionName}_${field.name}_idx`,
        });
        indexedFields.add(field.name);
      }
    }

    return specs;
  }

  private analyzeMongoColumnChanges(
    oldColumns: any[],
    newColumns: any[],
  ): {
    create: any[];
    delete: any[];
    rename: { oldName: string; newName: string; column: any }[];
    update: { oldColumn: any; newColumn: any }[];
  } {
    const result = {
      create: [] as any[],
      delete: [] as any[],
      rename: [] as { oldName: string; newName: string; column: any }[],
      update: [] as { oldColumn: any; newColumn: any }[],
    };

    const oldColMap = new Map(
      oldColumns.filter((c) => c.id != null).map((c) => [c.id, c]),
    );
    const newColMap = new Map(
      newColumns.filter((c) => c.id != null).map((c) => [c.id, c]),
    );
    const oldColNameMap = new Map(oldColumns.map((c) => [c.name, c]));

    for (const newCol of newColumns) {
      if (newCol.id == null) {
        if (!oldColNameMap.has(newCol.name)) {
          result.create.push(newCol);
        }
        continue;
      }
      const oldCol = oldColMap.get(newCol.id);
      if (!oldCol) {
        if (oldColNameMap.has(newCol.name)) continue;
        result.create.push(newCol);
      }
    }

    for (const oldCol of oldColumns) {
      if (oldCol.id == null) continue;
      const newCol = newColMap.get(oldCol.id);
      if (!newCol) {
        if (['id', 'createdAt', 'updatedAt', '_id'].includes(oldCol.name)) {
          // skip system columns
        } else {
          result.delete.push(oldCol);
        }
      } else {
        if (oldCol.name !== newCol.name) {
          result.rename.push({ oldName: oldCol.name, newName: newCol.name, column: newCol });
        } else if (this.hasMongoColumnChanged(oldCol, newCol)) {
          result.update.push({ oldColumn: oldCol, newColumn: newCol });
        }
      }
    }

    return result;
  }

  private hasMongoColumnChanged(oldCol: any, newCol: any): boolean {
    return (
      oldCol.type !== newCol.type ||
      oldCol.isNullable !== newCol.isNullable ||
      oldCol.isGenerated !== newCol.isGenerated ||
      JSON.stringify(oldCol.defaultValue) !== JSON.stringify(newCol.defaultValue)
    );
  }

  private analyzeMongoIndexChanges(
    oldMetadata: any,
    newMetadata: any,
  ): {
    create: { keys: Record<string, number>; options: any; name: string }[];
    delete: string[];
    unchanged: string[];
  } {
    const oldSpecs = this.buildFullIndexSpecs(
      oldMetadata.name,
      oldMetadata.columns || [],
      oldMetadata.uniques || [],
      oldMetadata.indexes || [],
      oldMetadata.relations || [],
    );
    const newSpecs = this.buildFullIndexSpecs(
      newMetadata.name,
      newMetadata.columns || [],
      newMetadata.uniques || [],
      newMetadata.indexes || [],
      newMetadata.relations || [],
    );

    const oldIndexNames = new Map(oldSpecs.map((s) => [s.name, s]));
    const newIndexNames = new Map(newSpecs.map((s) => [s.name, s]));

    const toCreate = newSpecs.filter((s) => !oldIndexNames.has(s.name));
    const toDelete = oldSpecs
      .filter((s) => !newIndexNames.has(s.name))
      .map((s) => s.name);
    const unchanged = newSpecs
      .filter((s) => oldIndexNames.has(s.name))
      .map((s) => s.name);

    return { create: toCreate, delete: toDelete, unchanged };
  }

  private generateMongoSchemaDiff(
    oldMetadata: any,
    newMetadata: any,
  ): {
    columns: {
      create: any[];
      delete: any[];
      rename: { oldName: string; newName: string; column: any }[];
      update: { oldColumn: any; newColumn: any }[];
    };
    validation: { changed: boolean; newSchema: any };
    indexes: {
      create: { keys: Record<string, number>; options: any; name: string }[];
      delete: string[];
      unchanged: string[];
    };
    junctionCollections: {
      create: { name: string; sourceColumn: string; targetColumn: string }[];
      drop: string[];
      rename: { oldName: string; newName: string }[];
    };
  } {
    const columnDiff = this.analyzeMongoColumnChanges(
      oldMetadata.columns || [],
      newMetadata.columns || [],
    );

    const oldSchema = this.createValidationSchema(oldMetadata.columns || []);
    const newSchema = this.createValidationSchema(newMetadata.columns || []);
    const validationChanged = JSON.stringify(oldSchema) !== JSON.stringify(newSchema);

    const indexDiff = this.analyzeMongoIndexChanges(oldMetadata, newMetadata);

    const junctionDiff = {
      create: [] as { name: string; sourceColumn: string; targetColumn: string }[],
      drop: [] as string[],
      rename: [] as { oldName: string; newName: string }[],
    };

    const oldM2m = new Map<string, any>(
      (oldMetadata.relations || [])
        .filter((r: any) => r.type === 'many-to-many' && r.junctionTableName)
        .map((r: any) => [r.junctionTableName, r] as [string, any]),
    );
    const newM2m = new Map<string, any>(
      (newMetadata.relations || [])
        .filter((r: any) => r.type === 'many-to-many' && r.junctionTableName)
        .map((r: any) => [r.junctionTableName, r] as [string, any]),
    );

    for (const [name, rel] of newM2m) {
      if (!oldM2m.has(name)) {
        const oldRel = (oldMetadata.relations || []).find(
          (r: any) => r.id === rel.id && r.type === 'many-to-many',
        );
        if (oldRel?.junctionTableName && oldRel.junctionTableName !== name) {
          junctionDiff.rename.push({ oldName: oldRel.junctionTableName, newName: name });
        } else {
          junctionDiff.create.push({
            name,
            sourceColumn: rel.junctionSourceColumn,
            targetColumn: rel.junctionTargetColumn,
          });
        }
      }
    }
    for (const [name] of oldM2m) {
      if (!newM2m.has(name)) {
        const alreadyRenamed = junctionDiff.rename.some((r) => r.oldName === name);
        if (!alreadyRenamed) {
          junctionDiff.drop.push(name);
        }
      }
    }

    return {
      columns: columnDiff,
      validation: { changed: validationChanged, newSchema },
      indexes: indexDiff,
      junctionCollections: junctionDiff,
    };
  }

  private async executeMongoSchemaDiff(
    collectionName: string,
    diff: ReturnType<typeof this.generateMongoSchemaDiff>,
    oldMetadata: any,
    newMetadata: any,
  ): Promise<void> {
    const db = this.mongoService.getDb();

    // 1. Junction renames
    for (const { oldName, newName } of diff.junctionCollections.rename) {
      this.logger.log(`Renaming junction collection: ${oldName} → ${newName}`);
      await this.renameJunctionCollection(oldName, newName);
    }

    // 2. Junction drops
    for (const name of diff.junctionCollections.drop) {
      this.logger.log(`Dropping junction collection: ${name}`);
      await this.dropJunctionCollection(name);
    }

    // 3. Junction creates
    for (const { name, sourceColumn, targetColumn } of diff.junctionCollections.create) {
      this.logger.log(`Creating junction collection: ${name}`);
      await this.ensureJunctionCollection(name, sourceColumn, targetColumn);
    }

    // 4. Column renames on existing documents
    if (diff.columns.rename.length > 0) {
      this.logger.log(
        `Renaming fields in ${collectionName}: ${diff.columns.rename.map((r) => `${r.oldName}→${r.newName}`).join(', ')}`,
      );
      await this.renameFieldsInDocuments(collectionName, diff.columns.rename);
    }

    // 5. Index drops
    if (diff.indexes.delete.length > 0) {
      const collection = db.collection(collectionName);
      for (const indexName of diff.indexes.delete) {
        this.logger.log(`Dropping index: ${indexName}`);
        try {
          await collection.dropIndex(indexName);
        } catch (error: any) {
          this.logger.warn(`Failed to drop index ${indexName}: ${error.message}`);
        }
      }
    }

    // 6. Validation schema update (collMod)
    if (diff.validation.changed || diff.columns.create.length > 0 || diff.columns.delete.length > 0 || diff.columns.update.length > 0) {
      this.logger.log(`Updating validation schema for ${collectionName}`);
      try {
        await db.command({
          collMod: collectionName,
          validator: { $jsonSchema: diff.validation.newSchema },
          validationLevel: 'moderate',
          validationAction: 'error',
        });
      } catch (error: any) {
        this.logger.warn(`Failed to update validation for ${collectionName}: ${error.message}`);
      }
    }

    // 7. Index creates
    if (diff.indexes.create.length > 0) {
      const collection = db.collection(collectionName);
      for (const spec of diff.indexes.create) {
        this.logger.log(`Creating index: ${spec.name}`);
        try {
          await collection.createIndex(spec.keys, spec.options);
        } catch (error: any) {
          this.logger.warn(`Failed to create index ${spec.name}: ${error.message}`);
        }
      }
    }

    // 8. Metadata updates (uniques/indexes renames + auto-generated indexes)
    const autoGeneratedIndexNames = diff.indexes.create.map((s) => {
      const keyArr = Object.keys(s.keys);
      return keyArr;
    });
    if (autoGeneratedIndexNames.length > 0) {
      await this.updateMetadataIndexes(
        collectionName,
        newMetadata.indexes || [],
        autoGeneratedIndexNames,
      );
    }

    // Handle constraint renames (uniques/indexes metadata)
    await this.handleMetadataUpdates(collectionName, oldMetadata, newMetadata);
  }

  private async renameFieldsInDocuments(
    collectionName: string,
    renames: { oldName: string; newName: string }[],
  ): Promise<void> {
    if (renames.length === 0) return;
    const collection = this.mongoService.getDb().collection(collectionName);
    const renameMap: Record<string, string> = {};
    for (const { oldName, newName } of renames) {
      renameMap[oldName] = newName;
    }
    try {
      await collection.updateMany({}, { $rename: renameMap });
    } catch (error: any) {
      this.logger.warn(
        `Failed to rename fields in ${collectionName}: ${error.message}`,
      );
    }
  }

  async dropCollection(collectionName: string): Promise<void> {
    const db = this.mongoService.getDb();
    try {
      const collections = await db
        .listCollections({ name: collectionName })
        .toArray();
      if (collections.length === 0) {
        this.logger.warn(
          ` Collection ${collectionName} does not exist, skipping drop`,
        );
        return;
      }
      await db.collection(collectionName).drop();
    } catch (error) {
      this.logger.error(
        `Failed to drop collection ${collectionName}: ${error.message}`,
      );
      throw error;
    }
  }

  async ensureJunctionCollection(
    junctionName: string,
    sourceColumn: string,
    targetColumn: string,
  ): Promise<void> {
    const db = this.mongoService.getDb();
    const existing = await db.listCollections({ name: junctionName }).toArray();
    if (existing.length === 0) {
      try {
        await db.createCollection(junctionName);
      } catch (error: any) {
        const nowExisting = await db
          .listCollections({ name: junctionName })
          .toArray();
        if (nowExisting.length === 0) throw error;
      }
    }

    const collection = db.collection(junctionName);

    try {
      await collection.createIndex(
        { [sourceColumn]: 1, [targetColumn]: 1 },
        { unique: true, name: `${junctionName}_src_tgt_uq` },
      );
    } catch (error: any) {
      if (error.code !== 85 && error.code !== 86) throw error;
    }

    try {
      await collection.createIndex(
        { [targetColumn]: 1 },
        { name: `${junctionName}_tgt_idx` },
      );
    } catch (error: any) {
      if (error.code !== 85 && error.code !== 86) throw error;
    }
  }

  async dropJunctionCollection(junctionName: string): Promise<void> {
    const db = this.mongoService.getDb();
    try {
      const existing = await db
        .listCollections({ name: junctionName })
        .toArray();
      if (existing.length === 0) return;
      await db.collection(junctionName).drop();
    } catch (error: any) {
      this.logger.warn(
        `Failed to drop junction collection ${junctionName}: ${error.message}`,
      );
    }
  }

  async renameJunctionCollection(
    oldName: string,
    newName: string,
  ): Promise<void> {
    const db = this.mongoService.getDb();
    const existing = await db.listCollections({ name: oldName }).toArray();
    if (existing.length > 0) {
      await db.collection(oldName).rename(newName);
    }
  }
  private async createIndexes(
    collectionName: string,
    columns: any[],
    uniques: any[] = [],
    indexes: any[] = [],
    relations: any[] = [],
  ): Promise<string[][]> {
    const db = this.mongoService.getDb();
    const collection = db.collection(collectionName);
    const autoGeneratedIndexes: string[][] = [];
    const indexedFields = new Set<string>();

    for (const index of indexes) {
      for (const field of index) {
        indexedFields.add(field);
      }
    }

    try {
      for (const col of columns) {
        if (col.name === '_id') {
          continue;
        }
        if (col.isPrimary || col.name === 'id') {
          await collection.createIndex(
            { [col.name]: 1 },
            {
              unique: true,
              name: `${collectionName}_${col.name}_unique`,
            },
          );
        }
      }
      for (const unique of uniques) {
        const indexSpec: any = {};
        for (const field of unique) {
          indexSpec[field] = 1;
        }
        await collection.createIndex(indexSpec, {
          unique: true,
          name: `${collectionName}_${unique.join('_')}_unique`,
          partialFilterExpression: this.createPartialFilterForUnique(unique),
        });
        if (unique.length > 0) {
          indexedFields.add(unique[0]);
        }
      }
      for (const index of indexes) {
        const indexSpec: any = {};
        for (const field of index) {
          indexSpec[field] = 1;
        }
        await collection.createIndex(indexSpec, {
          name: `${collectionName}_${index.join('_')}_idx`,
        });
      }
      for (const relation of relations) {
        if (relation.type === 'many-to-one' || relation.type === 'one-to-one') {
          const fieldName = relation.propertyName;
          if (!indexedFields.has(fieldName)) {
            await collection.createIndex(
              { [fieldName]: 1 },
              { name: `${collectionName}_${fieldName}_fk_idx` },
            );
            autoGeneratedIndexes.push([fieldName]);
            indexedFields.add(fieldName);
          }
        }
      }
      if (!indexedFields.has('createdAt')) {
        await collection.createIndex(
          { createdAt: -1 },
          { name: `${collectionName}_createdAt_idx` },
        );
        autoGeneratedIndexes.push(['createdAt']);
        indexedFields.add('createdAt');
      }
      if (!indexedFields.has('updatedAt')) {
        await collection.createIndex(
          { updatedAt: -1 },
          { name: `${collectionName}_updatedAt_idx` },
        );
        autoGeneratedIndexes.push(['updatedAt']);
        indexedFields.add('updatedAt');
      }
      const timestampFields = columns.filter(
        (col) =>
          col.type === 'datetime' ||
          col.type === 'timestamp' ||
          col.type === 'date',
      );
      for (const field of timestampFields) {
        if (!indexedFields.has(field.name)) {
          await collection.createIndex(
            { [field.name]: -1 },
            { name: `${collectionName}_${field.name}_idx` },
          );
          autoGeneratedIndexes.push([field.name]);
          indexedFields.add(field.name);
        }
      }
    } catch (error) {
      this.logger.warn(
        `Failed to create some indexes for ${collectionName}: ${error.message}`,
      );
    }

    return autoGeneratedIndexes;
  }

  async restoreMetadataFromRawSnapshot(entry: any): Promise<void> {
    const snapshot = entry.rawBeforeSnapshot;
    if (!snapshot || !snapshot.table) {
      this.logger.warn(
        `No rawBeforeSnapshot in journal ${entry.uuid}, skipping metadata restore`,
      );
      return;
    }

    const { ObjectId } = require('mongodb');
    const db = this.mongoService.getDb();
    const tableId = snapshot.table._id;
    const oid = typeof tableId === 'string' ? new ObjectId(tableId) : tableId;

    this.logger.warn(
      `Restoring metadata from raw snapshot for table ${snapshot.table.name} (${oid})`,
    );

    // 1. Restore table document
    await db
      .collection('table_definition')
      .replaceOne({ _id: oid }, snapshot.table, { upsert: true });

    // 2. Restore columns (delete current, insert from snapshot)
    await db.collection('column_definition').deleteMany({ table: oid });
    if (snapshot.columns && snapshot.columns.length > 0) {
      await db.collection('column_definition').insertMany(snapshot.columns);
    }

    // 3. Restore source relations (delete current, insert from snapshot)
    await db
      .collection('relation_definition')
      .deleteMany({ sourceTable: oid });
    if (snapshot.relations && snapshot.relations.length > 0) {
      await db
        .collection('relation_definition')
        .insertMany(snapshot.relations);
    }

    // 4. Clean up auto-created inverse relations on other tables
    const currentSourceRels = await db
      .collection('relation_definition')
      .find({ sourceTable: oid })
      .toArray();
    const owningRelIds = currentSourceRels
      .filter((r: any) => !r.mappedBy)
      .map((r: any) => r._id);
    if (owningRelIds.length > 0) {
      const currentInverse = await db
        .collection('relation_definition')
        .find({ mappedBy: { $in: owningRelIds } })
        .toArray();
      const snapshotInverseIds = new Set<string>(
        (snapshot.inverseRelations || []).map((r: any) => String(r._id)),
      );
      for (const inv of currentInverse) {
        if (!snapshotInverseIds.has(String(inv._id))) {
          await db
            .collection('relation_definition')
            .deleteOne({ _id: inv._id });
        }
      }
    }

    // 5. Re-insert snapshot inverse relations (if any were deleted during migration)
    for (const invRel of snapshot.inverseRelations || []) {
      const exists = await db
        .collection('relation_definition')
        .findOne({ _id: invRel._id });
      if (!exists) {
        await db.collection('relation_definition').insertOne(invRel);
      }
    }

    this.logger.warn(
      `Metadata restore completed for table ${snapshot.table.name}`,
    );
  }
}
