import { Logger } from '../../../shared/logger';
import { MongoService } from './mongo.service';
import { QueryBuilderService } from '@enfyra/kernel';
import { getErrorMessage } from '../../../shared/utils/error.util';
import { buildMongoFullIndexSpecs } from '../utils/mongo-physical-schema-contract';
import type { MongoPhysicalIndexSpec } from '../types/mongo-physical-schema-contract.types';
import {
  buildMongoValidationSchema,
  MONGO_VALIDATION_LEVEL,
  MONGO_VALIDATION_ACTION,
} from '../utils/mongo-validation-schema.util';

export class MongoSchemaDiffService {
  private readonly logger = new Logger(MongoSchemaDiffService.name);

  private readonly mongoService: MongoService;
  private readonly queryBuilderService: QueryBuilderService;

  constructor(deps: {
    mongoService: MongoService;
    queryBuilderService: QueryBuilderService;
  }) {
    this.mongoService = deps.mongoService;
    this.queryBuilderService = deps.queryBuilderService;
  }


  indexKey(index: string[]): string {
    return [...index].sort().join(',');
  }

  async updateMetadataIndexes(
    collectionName: string,
    userDefinedIndexes: string[][],
    autoGeneratedIndexes: string[][],
  ): Promise<void> {
    if (autoGeneratedIndexes.length === 0) return;

    const existingIndexKeys = new Set(
      userDefinedIndexes.map((idx) => this.indexKey(idx)),
    );

    const newIndexes: string[][] = [];
    for (const autoIdx of autoGeneratedIndexes) {
      if (!existingIndexKeys.has(this.indexKey(autoIdx))) {
        newIndexes.push(autoIdx);
      }
    }

    if (newIndexes.length === 0) return;

    const mergedIndexes = [...userDefinedIndexes, ...newIndexes];

    await this.queryBuilderService.update(
      'enfyra_table',
      { where: [{ field: 'name', operator: '=', value: collectionName }] },
      { indexes: mergedIndexes },
    );
  }

  updateConstraintColumns(
    constraints: any[],
    renames: Map<string, string>,
  ): any[] {
    if (!constraints || constraints.length === 0 || renames.size === 0)
      return constraints;

    return constraints.map((constraint) => {
      if (Array.isArray(constraint)) {
        return constraint.map((col) => renames.get(col) || col);
      }
      return constraint;
    });
  }

  buildFullIndexSpecs(
    collectionName: string,
    columns: any[],
    uniques: any[] = [],
    indexes: any[] = [],
    relations: any[] = [],
  ): MongoPhysicalIndexSpec[] {
    return buildMongoFullIndexSpecs({
      collectionName,
      columns,
      uniques,
      indexes,
      relations,
    });
  }

  analyzeMongoColumnChanges(
    oldColumns: any[],
    newColumns: any[],
  ): {
    create: any[];
    delete: any[];
    rename: { oldName: string; newName: string; column: any }[];
    update: { oldColumn: any; newColumn: any }[];
  } {
    const result = {
      create: [] as any[],
      delete: [] as any[],
      rename: [] as { oldName: string; newName: string; column: any }[],
      update: [] as { oldColumn: any; newColumn: any }[],
    };

    const oldColMap = new Map(
      oldColumns.filter((c) => c.id != null).map((c) => [c.id, c]),
    );
    const newColMap = new Map(
      newColumns.filter((c) => c.id != null).map((c) => [c.id, c]),
    );
    const oldColNameMap = new Map(oldColumns.map((c) => [c.name, c]));

    for (const newCol of newColumns) {
      if (newCol.id == null) {
        if (!oldColNameMap.has(newCol.name)) {
          result.create.push(newCol);
        }
        continue;
      }
      const oldCol = oldColMap.get(newCol.id);
      if (!oldCol) {
        if (oldColNameMap.has(newCol.name)) continue;
        result.create.push(newCol);
      }
    }

    for (const oldCol of oldColumns) {
      if (oldCol.id == null) continue;
      const newCol = newColMap.get(oldCol.id);
      if (!newCol) {
        if (['id', 'createdAt', 'updatedAt', '_id'].includes(oldCol.name)) {
        } else {
          result.delete.push(oldCol);
        }
      } else {
        if (oldCol.name !== newCol.name) {
          result.rename.push({
            oldName: oldCol.name,
            newName: newCol.name,
            column: newCol,
          });
        } else if (this.hasMongoColumnChanged(oldCol, newCol)) {
          result.update.push({ oldColumn: oldCol, newColumn: newCol });
        }
      }
    }

    return result;
  }

  hasMongoColumnChanged(oldCol: any, newCol: any): boolean {
    return (
      oldCol.type !== newCol.type ||
      oldCol.isNullable !== newCol.isNullable ||
      oldCol.isGenerated !== newCol.isGenerated ||
      JSON.stringify(oldCol.defaultValue) !==
        JSON.stringify(newCol.defaultValue)
    );
  }

  analyzeMongoIndexChanges(
    oldMetadata: any,
    newMetadata: any,
  ): {
    create: MongoPhysicalIndexSpec[];
    delete: string[];
    unchanged: string[];
  } {
    const oldSpecs = this.buildFullIndexSpecs(
      oldMetadata.name,
      oldMetadata.columns || [],
      oldMetadata.uniques || [],
      oldMetadata.indexes || [],
      oldMetadata.relations || [],
    );
    const newSpecs = this.buildFullIndexSpecs(
      newMetadata.name,
      newMetadata.columns || [],
      newMetadata.uniques || [],
      newMetadata.indexes || [],
      newMetadata.relations || [],
    );

    const oldIndexNames = new Map(oldSpecs.map((s) => [s.name, s]));
    const newIndexNames = new Map(newSpecs.map((s) => [s.name, s]));

    const toCreate = newSpecs.filter((s) => !oldIndexNames.has(s.name));
    const toDelete = oldSpecs
      .filter((s) => !newIndexNames.has(s.name))
      .map((s) => s.name);
    const unchanged = newSpecs
      .filter((s) => oldIndexNames.has(s.name))
      .map((s) => s.name);

    return { create: toCreate, delete: toDelete, unchanged };
  }

  generateMongoSchemaDiff(
    oldMetadata: any,
    newMetadata: any,
  ): {
    collection: {
      rename: { oldName: string; newName: string } | null;
    };
    columns: {
      create: any[];
      delete: any[];
      rename: { oldName: string; newName: string; column: any }[];
      update: { oldColumn: any; newColumn: any }[];
    };
    validation: { changed: boolean; newSchema: any };
    indexes: {
      create: MongoPhysicalIndexSpec[];
      delete: string[];
      unchanged: string[];
    };
    junctionCollections: {
      create: { name: string; sourceColumn: string; targetColumn: string }[];
      drop: string[];
      rename: { oldName: string; newName: string }[];
    };
  } {
    const collectionDiff = {
      rename:
        oldMetadata.name && newMetadata.name && oldMetadata.name !== newMetadata.name
          ? { oldName: oldMetadata.name, newName: newMetadata.name }
          : null,
    };
    const columnDiff = this.analyzeMongoColumnChanges(
      oldMetadata.columns || [],
      newMetadata.columns || [],
    );

    const oldSchema = buildMongoValidationSchema(oldMetadata.columns || []);
    const newSchema = buildMongoValidationSchema(newMetadata.columns || []);
    const validationChanged =
      JSON.stringify(oldSchema) !== JSON.stringify(newSchema);

    const indexDiff = this.analyzeMongoIndexChanges(oldMetadata, newMetadata);

    const junctionDiff = {
      create: [] as {
        name: string;
        sourceColumn: string;
        targetColumn: string;
      }[],
      drop: [] as string[],
      rename: [] as { oldName: string; newName: string }[],
    };

    const oldM2m = new Map<string, any>(
      (oldMetadata.relations || [])
        .filter(
          (r: any) =>
            r.type === 'many-to-many' && !r.mappedBy && r.junctionTableName,
        )
        .map((r: any) => [r.junctionTableName, r] as [string, any]),
    );
    const newM2m = new Map<string, any>(
      (newMetadata.relations || [])
        .filter(
          (r: any) =>
            r.type === 'many-to-many' && !r.mappedBy && r.junctionTableName,
        )
        .map((r: any) => [r.junctionTableName, r] as [string, any]),
    );

    for (const [name, rel] of newM2m) {
      if (!oldM2m.has(name)) {
        const relationId = String(rel.id ?? rel._id ?? '');
        const oldRel = (oldMetadata.relations || []).find(
          (r: any) =>
            String(r.id ?? r._id ?? '') === relationId &&
            r.type === 'many-to-many',
        );
        if (oldRel?.junctionTableName && oldRel.junctionTableName !== name) {
          junctionDiff.rename.push({
            oldName: oldRel.junctionTableName,
            newName: name,
          });
        } else {
          junctionDiff.create.push({
            name,
            sourceColumn: rel.junctionSourceColumn,
            targetColumn: rel.junctionTargetColumn,
          });
        }
      }
    }
    for (const [name] of oldM2m) {
      if (!newM2m.has(name)) {
        const alreadyRenamed = junctionDiff.rename.some(
          (r) => r.oldName === name,
        );
        if (!alreadyRenamed) {
          junctionDiff.drop.push(name);
        }
      }
    }

    return {
      collection: collectionDiff,
      columns: columnDiff,
      validation: { changed: validationChanged, newSchema },
      indexes: indexDiff,
      junctionCollections: junctionDiff,
    };
  }

  async executeMongoSchemaDiff(
    collectionName: string,
    diff: ReturnType<typeof this.generateMongoSchemaDiff>,
    oldMetadata: any,
    newMetadata: any,
  ): Promise<void> {
    const db = this.mongoService.getDb();
    let activeCollectionName = collectionName;

    if (diff.collection.rename) {
      const { oldName, newName } = diff.collection.rename;
      this.logger.log(`Renaming collection: ${oldName} → ${newName}`);
      const oldExists = await db.listCollections({ name: oldName }).toArray();
      const newExists = await db.listCollections({ name: newName }).toArray();
      if (oldExists.length > 0 && newExists.length === 0) {
        await db.collection(oldName).rename(newName);
      }
      activeCollectionName = newName;
    }

    for (const { oldName, newName } of diff.junctionCollections.rename) {
      this.logger.log(`Renaming junction collection: ${oldName} → ${newName}`);
      await this.renameJunctionCollection(oldName, newName);
    }

    for (const name of diff.junctionCollections.drop) {
      this.logger.log(`Dropping junction collection: ${name}`);
      await this.dropJunctionCollection(name);
    }

    for (const { name, sourceColumn, targetColumn } of diff.junctionCollections
      .create) {
      this.logger.log(`Creating junction collection: ${name}`);
      await this.ensureJunctionCollection(name, sourceColumn, targetColumn);
    }

    if (diff.indexes.delete.length > 0) {
      const collection = db.collection(activeCollectionName);
      for (const indexName of diff.indexes.delete) {
        this.logger.log(`Dropping index: ${indexName}`);
        try {
          await collection.dropIndex(indexName);
        } catch (error: any) {
          if (error?.code === 27) {
            this.logger.log(`Index ${indexName} already absent, skipping drop`);
          } else {
            throw new Error(`Failed to drop index ${indexName}: ${error.message}`);
          }
        }
      }
    }

    if (
      diff.validation.changed ||
      diff.columns.create.length > 0 ||
      diff.columns.delete.length > 0 ||
      diff.columns.update.length > 0
    ) {
      this.logger.log(`Updating validation schema for ${activeCollectionName}`);
      try {
        await db.command({
          collMod: activeCollectionName,
          validator: { $jsonSchema: diff.validation.newSchema },
          validationLevel: MONGO_VALIDATION_LEVEL,
          validationAction: MONGO_VALIDATION_ACTION,
        });
      } catch (error: any) {
        throw new Error(
          `Failed to update validation for ${collectionName}: ${error.message}`,
        );
      }
    }

    if (diff.indexes.create.length > 0) {
      const collection = db.collection(activeCollectionName);
      for (const spec of diff.indexes.create) {
        this.logger.log(`Creating index: ${spec.name}`);
        try {
          await collection.createIndex(spec.keys, spec.options);
        } catch (error: any) {
          throw new Error(`Failed to create index ${spec.name}: ${error.message}`);
        }
      }
    }

    const autoGeneratedIndexes = diff.indexes.create
      .filter((spec) => spec.autoGenerated)
      .map((spec) => spec.logicalFields);
    if (autoGeneratedIndexes.length > 0) {
      await this.updateMetadataIndexes(
        activeCollectionName,
        newMetadata.indexes || [],
        autoGeneratedIndexes,
      );
    }
  }

  async renameJunctionCollection(
    oldName: string,
    newName: string,
  ): Promise<void> {
    const db = this.mongoService.getDb();
    const existing = await db.listCollections({ name: oldName }).toArray();
    if (existing.length > 0) {
      await db.collection(oldName).rename(newName);
    }
  }

  async dropJunctionCollection(junctionName: string): Promise<void> {
    const db = this.mongoService.getDb();
    try {
      const existing = await db
        .listCollections({ name: junctionName })
        .toArray();
      if (existing.length === 0) return;
      await db.collection(junctionName).drop();
    } catch (error: any) {
      if (error?.code === 26 || String(error?.message ?? '').includes('ns not found')) {
        return;
      }
      throw new Error(
        `Failed to drop junction collection ${junctionName}: ${error.message}`,
      );
    }
  }

  async ensureJunctionCollection(
    junctionName: string,
    sourceColumn: string,
    targetColumn: string,
  ): Promise<void> {
    const db = this.mongoService.getDb();
    const existing = await db.listCollections({ name: junctionName }).toArray();
    if (existing.length === 0) {
      try {
        await db.createCollection(junctionName);
      } catch (error: any) {
        const nowExisting = await db
          .listCollections({ name: junctionName })
          .toArray();
        if (nowExisting.length === 0) throw error;
      }
    }

    const collection = db.collection(junctionName);

    try {
      await collection.createIndex(
        { [sourceColumn]: 1, [targetColumn]: 1 },
        { unique: true, name: `${junctionName}_src_tgt_uq` },
      );
    } catch (error: any) {
      throw new Error(`Failed to create junction index ${junctionName}_src_tgt_uq: ${error.message}`);
    }

    try {
      await collection.createIndex(
        { [targetColumn]: 1 },
        { name: `${junctionName}_tgt_idx` },
      );
    } catch (error: any) {
      throw new Error(`Failed to create junction index ${junctionName}_tgt_idx: ${error.message}`);
    }
  }
}
