import { Logger } from '../../../shared/logger';
import { ObjectId } from 'mongodb';
import { MongoService } from './mongo.service';
import { MetadataCacheService } from '../../cache';
import { getErrorMessage } from '../../../shared/utils/error.util';
import { QueryBuilderService } from '@enfyra/kernel';
import { MongoMigrationJournalService } from './mongo-migration-journal.service';
import { MongoSchemaDiffService } from './mongo-schema-diff.service';
import { buildMongoFullIndexSpecs } from '../utils/mongo-physical-schema-contract';
import {
  buildMongoValidationSchema,
  MONGO_VALIDATION_LEVEL,
  MONGO_VALIDATION_ACTION,
} from '../utils/mongo-validation-schema.util';
import { MongoSchemaMigrationLockService } from './mongo-schema-migration-lock.service';
export class MongoSchemaMigrationService {
  private readonly logger = new Logger(MongoSchemaMigrationService.name);
  private readonly mongoService: MongoService;
  private readonly metadataCacheService: MetadataCacheService;
  private readonly queryBuilderService: QueryBuilderService;
  private readonly migrationJournalService: MongoMigrationJournalService;
  private readonly schemaDiffService: MongoSchemaDiffService;
  private readonly schemaMigrationLockService: MongoSchemaMigrationLockService;
  constructor(deps: {
    mongoService: MongoService;
    metadataCacheService: MetadataCacheService;
    queryBuilderService: QueryBuilderService;
    mongoMigrationJournalService: MongoMigrationJournalService;
    mongoSchemaDiffService: MongoSchemaDiffService;
    mongoSchemaMigrationLockService: MongoSchemaMigrationLockService;
  }) {
    this.mongoService = deps.mongoService;
    this.metadataCacheService = deps.metadataCacheService;
    this.queryBuilderService = deps.queryBuilderService;
    this.migrationJournalService = deps.mongoMigrationJournalService;
    this.schemaDiffService = deps.mongoSchemaDiffService;
    this.schemaMigrationLockService = deps.mongoSchemaMigrationLockService;
  }
  async createCollection(tableMetadata: any): Promise<void> {
    const db = this.mongoService.getDb();
    const collectionName = tableMetadata.name;
    try {
      const collections = await db
        .listCollections({ name: collectionName })
        .toArray();
      if (collections.length > 0) {
        this.logger.warn(
          ` Collection ${collectionName} already exists, skipping creation`,
        );
        return;
      }
      const validationSchema = buildMongoValidationSchema(
        tableMetadata.columns || [],
      );
      await db.createCollection(collectionName, {
        validator: { $jsonSchema: validationSchema },
        validationLevel: MONGO_VALIDATION_LEVEL,
        validationAction: MONGO_VALIDATION_ACTION,
      });
      const autoGeneratedIndexes = await this.createIndexes(
        collectionName,
        tableMetadata.columns || [],
        tableMetadata.uniques || [],
        tableMetadata.indexes || [],
        tableMetadata.relations || [],
      );
      await this.schemaDiffService.updateMetadataIndexes(
        collectionName,
        tableMetadata.indexes || [],
        autoGeneratedIndexes,
      );
    } catch (error) {
      this.logger.error(
        `Failed to create collection ${collectionName}: ${getErrorMessage(error)}`,
      );
      throw error;
    }
  }
  async updateCollection(
    collectionName: string,
    oldMetadata: any,
    newMetadata: any,
    rawBeforeSnapshot?: any,
    precompiled?: { upDiff: any; downDiff: any },
  ): Promise<void> {
    try {
      if (!rawBeforeSnapshot) {
        throw new Error(
          `Mongo migration saga for ${collectionName} requires rawBeforeSnapshot`,
        );
      }
      const diff =
        precompiled?.upDiff ??
        this.schemaDiffService.generateMongoSchemaDiff(
          oldMetadata,
          newMetadata,
        );
      const downDiff =
        precompiled?.downDiff ??
        this.schemaDiffService.generateMongoSchemaDiff(
          newMetadata,
          oldMetadata,
        );
      this.logger.log(
        `Diff for ${collectionName}: ` +
          `columns(+${diff.columns.create.length}/-${diff.columns.delete.length}/~${diff.columns.update.length}/ren:${diff.columns.rename.length}), ` +
          `validation=${diff.validation.changed}, ` +
          `indexes(+${diff.indexes.create.length}/-${diff.indexes.delete.length}/=${diff.indexes.unchanged.length}), ` +
          `junctions(+${diff.junctionCollections.create.length}/-${diff.junctionCollections.drop.length}/ren:${diff.junctionCollections.rename.length})`,
      );
      const journalUuid = await this.migrationJournalService.record({
        tableName: collectionName,
        operation: 'update',
        upDiff: diff,
        downDiff,
        beforeSnapshot: oldMetadata,
        afterSnapshot: newMetadata,
        rawBeforeSnapshot,
      });
      await this.migrationJournalService.markRunning(journalUuid);

      try {
        await this.schemaDiffService.executeMongoSchemaDiff(
          collectionName,
          diff,
          oldMetadata,
          newMetadata,
        );
        await this.handleMetadataUpdates(
          diff.collection.rename?.newName || collectionName,
          oldMetadata,
          newMetadata,
        );
        await this.migrationJournalService.markCompleted(journalUuid);
      } catch (execError) {
        this.logger.warn(
          `Migration failed, executing rollback for ${journalUuid}`,
        );
        await this.migrationJournalService.executeRolldown(
          journalUuid,
          (downDiffInner) =>
            this.schemaDiffService.executeMongoSchemaDiff(
              collectionName,
              downDiffInner,
              newMetadata,
              oldMetadata,
            ),
          (entry) => this.restoreMetadataFromRawSnapshot(entry),
        );
        throw execError;
      }
    } catch (error) {
      this.logger.error(
        `Failed to update collection ${collectionName}: ${getErrorMessage(error)}`,
      );
      throw error;
    }
  }

  async recoverPendingMigrationSagas(): Promise<void> {
    const lock = await this.schemaMigrationLockService.acquireForRecovery(
      'mongo:migration-recovery',
    );
    let lockLost = false;
    const heartbeat = setInterval(() => {
      void this.schemaMigrationLockService
        .refreshHeartbeat(lock)
        .then((renewed) => {
          if (!renewed) lockLost = true;
        })
        .catch(() => {
          lockLost = true;
        });
    }, 5_000);
    try {
      await this.migrationJournalService.recoverPending(
        (diff, entry) =>
          this.schemaDiffService.executeMongoSchemaDiff(
            entry.tableName,
            diff,
            entry.afterSnapshot,
            entry.beforeSnapshot,
          ),
        (entry) => this.restoreMetadataFromRawSnapshot(entry),
      );
      if (
        lockLost ||
        !(await this.schemaMigrationLockService.isStillHeld(lock))
      ) {
        throw new Error('Mongo schema recovery lock lease was lost');
      }
    } finally {
      clearInterval(heartbeat);
      await this.schemaMigrationLockService.release(lock);
    }
  }
  private async handleMetadataUpdates(
    collectionName: string,
    oldMetadata: any,
    newMetadata: any,
  ): Promise<void> {
    const columnRenames: Map<string, string> = new Map();
    const propertyNameRenames: Map<string, string> = new Map();
    const oldColMap = new Map<string, any>(
      (oldMetadata.columns || []).map((c: any) => [String(c.id ?? c._id), c]),
    );
    const newColMap = new Map<string, any>(
      (newMetadata.columns || []).map((c: any) => [String(c.id ?? c._id), c]),
    );
    for (const [colId, newCol] of newColMap) {
      const oldCol = oldColMap.get(colId);
      if (oldCol && oldCol.name !== newCol.name) {
        columnRenames.set(oldCol.name, newCol.name);
      }
    }
    const oldRelMap = new Map<string, any>(
      (oldMetadata.relations || []).map((r: any) => [String(r.id ?? r._id), r]),
    );
    const newRelMap = new Map<string, any>(
      (newMetadata.relations || []).map((r: any) => [String(r.id ?? r._id), r]),
    );
    for (const [relId, newRel] of newRelMap) {
      const oldRel = oldRelMap.get(relId);
      if (oldRel && oldRel.propertyName !== newRel.propertyName) {
        propertyNameRenames.set(oldRel.propertyName, newRel.propertyName);
      }
    }
    if (columnRenames.size > 0 || propertyNameRenames.size > 0) {
      let updatedUniques = this.schemaDiffService.updateConstraintColumns(
        oldMetadata.uniques || [],
        columnRenames,
      );
      updatedUniques = this.schemaDiffService.updateConstraintColumns(
        updatedUniques,
        propertyNameRenames,
      );
      let updatedIndexes = this.schemaDiffService.updateConstraintColumns(
        oldMetadata.indexes || [],
        columnRenames,
      );
      updatedIndexes = this.schemaDiffService.updateConstraintColumns(
        updatedIndexes,
        propertyNameRenames,
      );
      const metadataUpdate: any = {};
      if (
        JSON.stringify(updatedUniques) !==
        JSON.stringify(oldMetadata.uniques || [])
      ) {
        metadataUpdate.uniques = updatedUniques;
      }
      if (
        JSON.stringify(updatedIndexes) !==
        JSON.stringify(oldMetadata.indexes || [])
      ) {
        metadataUpdate.indexes = updatedIndexes;
      }
      if (Object.keys(metadataUpdate).length > 0) {
        await this.persistMetadataUpdates(collectionName, metadataUpdate);
      }
    }
  }
  private async persistMetadataUpdates(
    collectionName: string,
    updates: any,
  ): Promise<void> {
    const updateData: any = {};
    if (updates.uniques !== undefined) {
      updateData.uniques = updates.uniques;
    }
    if (updates.indexes !== undefined) {
      updateData.indexes = updates.indexes;
    }
    if (Object.keys(updateData).length === 0) return;
    await this.queryBuilderService.update(
      'enfyra_table',
      { where: [{ field: 'name', operator: '=', value: collectionName }] },
      updateData,
    );
  }
  async dropCollection(collectionName: string): Promise<void> {
    const db = this.mongoService.getDb();
    try {
      const collections = await db
        .listCollections({ name: collectionName })
        .toArray();
      if (collections.length === 0) {
        this.logger.warn(
          ` Collection ${collectionName} does not exist, skipping drop`,
        );
        return;
      }
      await db.collection(collectionName).drop();
    } catch (error) {
      this.logger.error(
        `Failed to drop collection ${collectionName}: ${getErrorMessage(error)}`,
      );
      throw error;
    }
  }
  async ensureJunctionCollection(
    junctionName: string,
    sourceColumn: string,
    targetColumn: string,
  ): Promise<void> {
    return this.schemaDiffService.ensureJunctionCollection(
      junctionName,
      sourceColumn,
      targetColumn,
    );
  }
  async dropJunctionCollection(junctionName: string): Promise<void> {
    return this.schemaDiffService.dropJunctionCollection(junctionName);
  }
  async renameJunctionCollection(
    oldName: string,
    newName: string,
  ): Promise<void> {
    return this.schemaDiffService.renameJunctionCollection(oldName, newName);
  }
  private async createIndexes(
    collectionName: string,
    columns: any[],
    uniques: any[] = [],
    indexes: any[] = [],
    relations: any[] = [],
  ): Promise<string[][]> {
    const db = this.mongoService.getDb();
    const collection = db.collection(collectionName);
    const autoGeneratedIndexes: string[][] = [];
    const specs = buildMongoFullIndexSpecs({
      collectionName,
      columns,
      uniques,
      indexes,
      relations,
    });
    try {
      for (const spec of specs) {
        await collection.createIndex(spec.keys, spec.options);
        if (spec.autoGenerated) {
          autoGeneratedIndexes.push(spec.logicalFields);
        }
      }
    } catch (error) {
      this.logger.error(
        `Failed to create indexes for ${collectionName}: ${getErrorMessage(error)}`,
      );
      throw error;
    }
    return autoGeneratedIndexes;
  }
  async restoreMetadataFromRawSnapshot(entry: any): Promise<void> {
    const snapshot = entry.rawBeforeSnapshot;
    if (!snapshot || !snapshot.table) {
      this.logger.warn(
        `No rawBeforeSnapshot in journal ${entry.uuid}, skipping metadata restore`,
      );
      return;
    }
    const db = this.mongoService.getDb();
    const tableId = snapshot.table._id;
    const oid = typeof tableId === 'string' ? new ObjectId(tableId) : tableId;
    this.logger.warn(
      `Restoring metadata from raw snapshot for table ${snapshot.table.name} (${oid})`,
    );
    await db
      .collection('enfyra_table')
      .replaceOne({ _id: oid }, snapshot.table, { upsert: true });
    await db.collection('enfyra_column').deleteMany({ table: oid });
    if (snapshot.columns && snapshot.columns.length > 0) {
      await db.collection('enfyra_column').insertMany(snapshot.columns);
    }
    const preRestoreSourceRels = await db
      .collection('enfyra_relation')
      .find({ sourceTable: oid })
      .toArray();
    const preRestoreOwningIds = preRestoreSourceRels
      .filter((r: any) => !r.mappedBy)
      .map((r: any) => r._id);
    await db.collection('enfyra_relation').deleteMany({ sourceTable: oid });
    if (snapshot.relations && snapshot.relations.length > 0) {
      await db.collection('enfyra_relation').insertMany(snapshot.relations);
    }
    const snapshotOwningIds = (snapshot.relations || [])
      .filter((r: any) => !r.mappedBy)
      .map((r: any) => r._id);
    const allOwningIds = [...new Set([
      ...preRestoreOwningIds.map(String),
      ...snapshotOwningIds.map(String),
    ])].map((id) => new ObjectId(id));
    if (allOwningIds.length > 0) {
      const currentInverse = await db
        .collection('enfyra_relation')
        .find({ mappedBy: { $in: allOwningIds } })
        .toArray();
      const snapshotInverseIds = new Set<string>(
        (snapshot.inverseRelations || []).map((r: any) => String(r._id)),
      );
      for (const inv of currentInverse) {
        if (!snapshotInverseIds.has(String(inv._id))) {
          await db
            .collection('enfyra_relation')
            .deleteOne({ _id: inv._id });
        }
      }
    }
    for (const invRel of snapshot.inverseRelations || []) {
      const exists = await db
        .collection('enfyra_relation')
        .findOne({ _id: invRel._id });
      if (!exists) {
        await db.collection('enfyra_relation').insertOne(invRel);
      }
    }
    this.logger.warn(
      `Metadata restore completed for table ${snapshot.table.name}`,
    );
  }
}
