import { describe, expect, it } from 'vitest';
import {
  buildMongoFullIndexSpecs,
  buildMongoStoredRelationContracts,
  buildMongoWritableFieldSet,
  getMongoInverseRelationForeignField,
  getMongoStoredRelationField,
  isMongoInverseRelation,
  isMongoOwningReferenceRelation,
} from '../../src/engines/mongo';

describe('Mongo physical schema contract', () => {
  it('stores owning reference relations on foreignKeyColumn or propertyName', () => {
    expect(
      getMongoStoredRelationField({
        propertyName: 'author',
        type: 'many-to-one',
        foreignKeyColumn: 'authorId',
      }),
    ).toBe('authorId');

    expect(
      getMongoStoredRelationField({
        propertyName: 'parent',
        type: 'many-to-one',
      }),
    ).toBe('parent');
  });

  it('does not store inverse or junction relations on the document', () => {
    expect(
      isMongoInverseRelation({
        propertyName: 'children',
        type: 'one-to-many',
        mappedBy: 'parent',
      }),
    ).toBe(true);

    expect(
      isMongoOwningReferenceRelation({
        propertyName: 'children',
        type: 'one-to-many',
        mappedBy: 'parent',
      }),
    ).toBe(false);

    expect(
      getMongoStoredRelationField({
        propertyName: 'tags',
        type: 'many-to-many',
      }),
    ).toBeNull();
  });

  it('resolves inverse relation foreign fields through mappedBy first', () => {
    expect(
      getMongoInverseRelationForeignField({
        propertyName: 'children',
        type: 'one-to-many',
        mappedBy: 'parent',
      }),
    ).toBe('parent');
  });

  it('builds writable fields from columns plus stored owning relations', () => {
    const contracts = buildMongoStoredRelationContracts([
      { propertyName: 'parent', type: 'many-to-one' },
      { propertyName: 'children', type: 'one-to-many', mappedBy: 'parent' },
      { propertyName: 'tags', type: 'many-to-many' },
    ]);

    expect(contracts).toEqual([
      {
        propertyName: 'parent',
        type: 'many-to-one',
        storedField: 'parent',
        targetTable: undefined,
      },
    ]);

    expect(
      Array.from(
        buildMongoWritableFieldSet({
          columns: [{ name: 'label' }],
          relations: [
            { propertyName: 'parent', type: 'many-to-one' },
            {
              propertyName: 'children',
              type: 'one-to-many',
              mappedBy: 'parent',
            },
          ],
        }),
      ).sort(),
    ).toEqual(['label', 'parent']);
  });

  it('builds physical index specs with unique fields and stable non-unique tie breakers', () => {
    const specs = buildMongoFullIndexSpecs({
      collectionName: 'post',
      columns: [
        { name: '_id', isPrimary: true },
        { name: 'slug', type: 'varchar' },
        { name: 'createdAt', type: 'datetime' },
      ],
      uniques: [['slug']],
      indexes: [['title']],
      relations: [{ propertyName: 'author', type: 'many-to-one' }],
    });

    expect(specs).toContainEqual({
      keys: { slug: 1 },
      options: {
        unique: true,
        name: 'post_slug_unique',
        partialFilterExpression: {
          slug: { $type: 'string' },
        },
      },
      name: 'post_slug_unique',
      logicalFields: ['slug'],
    });
    expect(specs).toContainEqual({
      keys: { title: 1, _id: 1 },
      options: { name: 'post_title_idx' },
      name: 'post_title_idx',
      logicalFields: ['title'],
    });
    expect(specs).toContainEqual({
      keys: { author: 1, _id: 1 },
      options: { name: 'post_author_fk_idx' },
      name: 'post_author_fk_idx',
      autoGenerated: true,
      logicalFields: ['author'],
    });
  });
});
