import { describe, expect, it } from 'vitest';
import {
  buildMongoFullIndexSpecs,
  buildMongoStoredRelationContracts,
  buildMongoWritableFieldSet,
  getMongoCanonicalConstraintGroups,
  getRemovedMongoStoredFields,
  getMongoInverseRelationForeignField,
  getMongoStoredRelationField,
  isMongoInverseRelation,
  isMongoOwningReferenceRelation,
} from '../../src/engines/mongo';

describe('Mongo physical schema contract', () => {
  it('stores owning reference relations on foreignKeyColumn or propertyName', () => {
    expect(
      getMongoStoredRelationField({
        propertyName: 'author',
        type: 'many-to-one',
        foreignKeyColumn: 'authorId',
      }),
    ).toBe('authorId');

    expect(
      getMongoStoredRelationField({
        propertyName: 'parent',
        type: 'many-to-one',
      }),
    ).toBe('parent');
  });

  it('does not store inverse or junction relations on the document', () => {
    expect(
      isMongoInverseRelation({
        propertyName: 'children',
        type: 'one-to-many',
        mappedBy: 'parent',
      }),
    ).toBe(true);

    expect(
      isMongoOwningReferenceRelation({
        propertyName: 'children',
        type: 'one-to-many',
        mappedBy: 'parent',
      }),
    ).toBe(false);

    expect(
      getMongoStoredRelationField({
        propertyName: 'tags',
        type: 'many-to-many',
      }),
    ).toBeNull();
  });

  it('resolves inverse relation foreign fields through mappedBy first', () => {
    expect(
      getMongoInverseRelationForeignField({
        propertyName: 'children',
        type: 'one-to-many',
        mappedBy: 'parent',
      }),
    ).toBe('parent');
  });

  it('builds writable fields from columns plus stored owning relations', () => {
    const contracts = buildMongoStoredRelationContracts([
      { propertyName: 'parent', type: 'many-to-one' },
      { propertyName: 'children', type: 'one-to-many', mappedBy: 'parent' },
      { propertyName: 'tags', type: 'many-to-many' },
    ]);

    expect(contracts).toEqual([
      {
        propertyName: 'parent',
        type: 'many-to-one',
        storedField: 'parent',
        targetTable: undefined,
      },
    ]);

    expect(
      Array.from(
        buildMongoWritableFieldSet({
          columns: [{ name: 'label' }],
          relations: [
            { propertyName: 'parent', type: 'many-to-one' },
            {
              propertyName: 'children',
              type: 'one-to-many',
              mappedBy: 'parent',
            },
          ],
        }),
      ).sort(),
    ).toEqual(['label', 'parent']);
  });

  it('builds physical index specs with unique fields and stable non-unique tie breakers', () => {
    const specs = buildMongoFullIndexSpecs({
      collectionName: 'post',
      columns: [
        { name: '_id', isPrimary: true },
        { name: 'slug', type: 'varchar' },
        { name: 'createdAt', type: 'datetime' },
      ],
      uniques: [['slug']],
      indexes: [['title']],
      relations: [{ propertyName: 'author', type: 'many-to-one' }],
    });

    expect(specs).toContainEqual({
      keys: { slug: 1 },
      options: {
        unique: true,
        name: 'post_slug_unique',
        partialFilterExpression: {
          slug: { $type: 'string' },
        },
      },
      name: 'post_slug_unique',
      logicalFields: ['slug'],
    });
    expect(specs).toContainEqual({
      keys: { title: 1, _id: 1 },
      options: { name: 'post_title_idx' },
      name: 'post_title_idx',
      logicalFields: ['title'],
    });
    expect(specs).toContainEqual({
      keys: { author: 1, _id: 1 },
      options: { name: 'post_author_fk_idx' },
      name: 'post_author_fk_idx',
      autoGenerated: true,
      logicalFields: ['author'],
    });
  });

  it('builds a unique index from a column-level isUnique intent', () => {
    const specs = buildMongoFullIndexSpecs({
      collectionName: 'gateway_models',
      columns: [{ name: 'as', type: 'varchar', isUnique: true }],
    });

    expect(specs).toContainEqual(
      expect.objectContaining({
        keys: { as: 1 },
        name: 'gateway_models_as_unique',
        logicalFields: ['as'],
      }),
    );
  });

  it('materializes unique scalar and owning one-to-one constraints before Mongo DDL', () => {
    expect(
      getMongoCanonicalConstraintGroups({
        collectionName: 'payment_order',
        columns: [{ name: 'providerOrderId', type: 'varchar' }],
        uniques: [['providerOrderId']],
        indexes: [['providerOrderId'], ['user']],
        relations: [
          {
            propertyName: 'user',
            type: 'one-to-one',
            foreignKeyColumn: 'user',
          },
        ],
      }),
    ).toEqual({
      uniques: [['providerOrderId'], ['user']],
      indexes: [['createdAt'], ['updatedAt']],
    });
  });

  it('keeps persisted temporal index metadata on the canonical descending direction', () => {
    const specs = buildMongoFullIndexSpecs({
      collectionName: 'post',
      indexes: [['createdAt'], ['updatedAt']],
    });

    expect(specs).toContainEqual({
      keys: { createdAt: -1, _id: 1 },
      options: { name: 'post_createdAt_idx' },
      name: 'post_createdAt_idx',
      logicalFields: ['createdAt'],
    });
    expect(specs).toContainEqual({
      keys: { updatedAt: -1, _id: 1 },
      options: { name: 'post_updatedAt_idx' },
      name: 'post_updatedAt_idx',
      logicalFields: ['updatedAt'],
    });
  });

  it('keeps a persisted single-relation index on the canonical FK index name', () => {
    const specs = buildMongoFullIndexSpecs({
      collectionName: 'post',
      indexes: [['author']],
      relations: [{ propertyName: 'author', type: 'many-to-one' }],
    });
    const authorSpecs = specs.filter(
      (spec) =>
        spec.logicalFields.length === 1 && spec.logicalFields[0] === 'author',
    );

    expect(authorSpecs).toEqual([
      {
        keys: { author: 1, _id: 1 },
        options: { name: 'post_author_fk_idx' },
        name: 'post_author_fk_idx',
        logicalFields: ['author'],
      },
    ]);
  });

  it('removes stored relation fields only when the physical mapping disappears', () => {
    const source = {
      columns: [{ name: '_id' }],
      relations: [
        {
          propertyName: 'teacher',
          type: 'many-to-one',
          foreignKeyColumn: 'teacher',
        },
      ],
    };

    expect(
      getRemovedMongoStoredFields(source, {
        columns: [{ name: '_id' }],
        relations: [
          {
            propertyName: 'mentor',
            type: 'many-to-one',
            foreignKeyColumn: 'teacher',
          },
        ],
      }),
    ).toEqual([]);
    expect(
      getRemovedMongoStoredFields(source, {
        columns: [{ name: '_id' }],
        relations: [],
      }),
    ).toEqual(['teacher']);
  });
});
