interface ToolDefinition {
  name: string;
  description: string;
  parameters: {
    type: string;
    properties: Record<string, any>;
    required?: string[];
  };
}

export const COMMON_TOOLS: ToolDefinition[] = [
  {
    name: 'get_table_details',
    description: `Purpose → load the full schema (columns, relations, indexes, constraints, table ID) for one or multiple tables.

CRITICAL - Call ONCE per table, reuse schema for subsequent operations.

CRITICAL - NEVER query all tables. ALWAYS filter first using find_records on table_definition, then call get_table_details only for filtered subset. Max 5 tables per call.

Use when:
- Preparing create/update payloads that must match schema exactly (call ONCE, then reuse)
- Investigating relation structure or constraints (call ONCE, then reuse)
- Need to compare multiple tables' schemas (call once with array of all table names, but filter first if user specified criteria)
- Need to check if tables have relations (call ONCE, then reuse)
- Need to get table ID (e.g., for relations, updates) - the metadata includes the table ID field

Skip when:
- You already called get_table_details for this table earlier in this response - reuse the previous result
- User asks for "non-system tables" but you haven't filtered yet → call find_records({"table":"table_definition","fields":"name,isSystem","filter":{"isSystem":{"_eq":false}},"limit":0}) first to filter

Inputs:
- tableName (required) → array of table names (case-sensitive). For single table, use array with 1 element: ["user_definition"]
- forceRefresh (optional) true to reload metadata

Response format:
{
  [tableName: string]: {
    name: string;
    description?: string;
    isSingleRecord?: boolean;
    id?: number;
    isSystem?: boolean;
    uniques?: any[];
    indexes?: any[];
    columns: {
      fields: ["name", "type", "isNullable", "isPrimary", "isGenerated", "defaultValue", "options", "description"];
      data: [
        ["id", "int", false, true, true, null, null, null],
        ["name", "varchar", false, false, false, null, null, "Product name"],
        ...
      ]
    };
    relations: {
      fields: ["propertyName", "type", "targetTableName", "isNullable", "inversePropertyName", "foreignKeyColumn", "description"];
      data: [
        ["category", "many-to-one", "categories", true, null, "categoryId", null],
        ...
      ]
    };
  };
}

**How to parse compact format:**
- columns.data[i][j] = value of columns.fields[j] for column i
- Example: columns.data[0][0] = "id" (name), columns.data[0][1] = "int" (type)
- relations.data[i][j] = value of relations.fields[j] for relation i
- Example: relations.data[0][0] = "category" (propertyName), relations.data[0][2] = "categories" (targetTableName)
- Use fields array to map indices: fields[0]=name, fields[1]=type, etc.

**Important Field Definitions:**

**Table-level fields:**
- isSystem (boolean): If true, this is a system table (e.g., table_definition, column_definition, relation_definition). System tables are critical for system operation and should NOT be deleted or heavily modified. If false, this is a user-created table that can be safely deleted.
- isSingleRecord (boolean): If true, this table is designed to store only ONE record (singleton pattern). Examples: system settings, global configuration. If false or missing, table can store multiple records.

**Column-level fields:**
- isPrimary (boolean): If true, this column is the primary key (unique identifier for each record). Each table MUST have exactly one column with isPrimary=true. Primary key values are unique and cannot be null.
- isNullable (boolean): If true, this column can contain NULL values. If false, this column is REQUIRED and cannot be null (NOT NULL constraint).
- isGenerated (boolean): If true, this column value is auto-generated by the database (e.g., auto-increment ID, UUID, timestamp). You should NOT provide values for generated columns when creating records.
- isUnique (boolean): If true, this column has a unique constraint.
- defaultValue (any): Default applied automatically. Do NOT include in create payload - especially isSystem, isRootAdmin (server-controlled, never from client).

**Relation-level fields:**
- isNullable (boolean): If true, the foreign key column can be NULL (relation is optional). If false, the foreign key is REQUIRED (relation is mandatory).
- type: Relation type - "many-to-one" (many records in this table reference one record in target), "one-to-many" (one record in this table has many in target), "one-to-one" (one-to-one relationship), "many-to-many" (many-to-many via junction table).

CRITICAL - Relations Format for Create/Update:
- ALWAYS use propertyName from relations[].propertyName (e.g. "role", "category"). NEVER use foreignKeyColumn (roleId, categoryId)
- Format for SQL: {[propertyName]: {id: value}} - Example: {"role": {id: 1}}, {"category": {id: 19}}
- Format for MongoDB: {[propertyName]: {_id: value}}
- foreignKeyColumn in relations is for reference ONLY - NEVER use it in create/update payloads
- For many-to-many relations, use array format: {[propertyName]: [{id: 1}, {id: 2}]} or {[propertyName]: [{_id: "..."}, {_id: "..."}]}
- Example: If relations array shows {propertyName: "customer", type: "many-to-one", targetTableName: "customers"}, use {"customer": {id: 1}} NOT {"customer_id": 1} or {"customerId": 1} or {"customer": 1}

Note: To check if a table has relations, check if relations array is empty [] or missing → no relations; if has items → has relations.
CRITICAL: Always check relations array to see available propertyName values before creating/updating records with relations.

Examples:
Single: {"tableName":["user_definition"]}
Multiple: {"tableName":["product","category","order"]}`,
    parameters: {
      type: 'object',
      properties: {
        tableName: {
          type: 'array',
          items: {
            type: 'string',
          },
          description: 'REQUIRED. Array of table names. For single table, use array with 1 element: ["user_definition"]. For multiple tables: ["product", "category", "order"].',
        },
        forceRefresh: {
          type: 'boolean',
          description: 'Optional. Set to true to reload metadata from database. Default: false.',
          default: false,
        },
      },
      required: ['tableName'],
    },
  },
  {
    name: 'get_hint',
    description: `Purpose → Get workflow guidance. Call FIRST before acting when task involves something you might need to guess.

CRITICAL – Call get_hint BEFORE writing/saving:
- Handler or hook code (handler_operations, hook_operations) – syntax like @USER, @QUERY, workflow
- Table schema, relations, CASCADE (table_schema_operations)
- Route, endpoint, API setup (routes_endpoints)
- CRUD with relations, batching (crud_write_operations)
- Bootstrap, WebSocket (bootstrap_operations, websocket_operations)
- Menu, navigation, sidebar (menu_operations)
- Extension, custom page, widget, Vue SFC (extension_operations, ui_vibe)

Do NOT guess – check categories, call get_hint first, then execute.

Available categories:
- database_type, field_optimization, table_schema_operations, table_deletion
- handler_operations, hook_operations, bootstrap_operations, websocket_operations
- menu_operations, extension_operations, ui_vibe
- crud_write_operations, crud_delete_operations, crud_query_operations
- metadata_operations, natural_language_discovery, system_workflows, error_handling, routes_endpoints

Input: category (string) or categories (array) or omit for all
Example: {"category":"handler_operations"} or {"category":["handler_operations","routes_endpoints"]}

Returns:
{
  dbType: string;
  idField: string;
  hints: Array<{category: string; title: string; content: string}>;
  availableCategories: string[];
}`,
    parameters: {
      type: 'object',
      properties: {
        category: {
          oneOf: [
            { type: 'string', description: 'Single hint category' },
            {
              type: 'array',
              items: { type: 'string' },
              description: 'Multiple hint categories',
            },
          ],
          description:
            'Hint category or array. Available: database_type, field_optimization, table_schema_operations, table_deletion, handler_operations, hook_operations, bootstrap_operations, websocket_operations, menu_operations, extension_operations, ui_vibe, crud_write_operations, crud_delete_operations, crud_query_operations, metadata_operations, natural_language_discovery, system_workflows, error_handling, routes_endpoints. Omit for all.',
        },
      },
    },
  },
  {
    name: 'create_tables',
    description: `Purpose → Create one or multiple tables. Processes tables sequentially internally to avoid deadlocks.

AUTO-CREATES ROUTE: When create_tables succeeds, route /{table_name} is AUTO-CREATED. Do NOT create route_definition separately - it already exists. Add handler/hook via pre_hook_definition, route_handler_definition.

SCHEMA LOCK - ONE TABLE PER CALL:
- Pass exactly 1 table per call, wait for result, then call again for next table
- Passing multiple tables causes "Schema is being updated" and most will fail

Inputs:
- tables (required): Array of table definition objects. For single table, use array with 1 element.

Each table object:
- description (optional): Table description
- columns (required): Array of column definition objects. MUST include id column with isPrimary=true. For SQL databases, use type="int". For MongoDB, use type="uuid". Do NOT include createdAt/updatedAt (auto-generated). Do NOT include FK columns (use relations instead).

Column Schema:
{
  name: string; 
  type: "int" | "varchar" | "boolean" | "text" | "date" | "float" | "simple-json" | "enum" | "uuid"; 
  isPrimary?: boolean; 
  isGenerated?: boolean; 
  isNullable?: boolean; 
  default?: any; 
  isUnique?: boolean; 
  description?: string; 
  isHidden?: boolean; 
  isUpdatable?: boolean; 
  isSystem?: boolean; 
  values?: string[]; 
  index?: boolean; 
}

- relations (optional): Array of relation definition objects. Include relations here, not in separate update_tables call.

Relation Schema:
{
  propertyName: string; 
  type: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many"; 
  targetTable: {id: number}; 
  inversePropertyName?: string; 
  isNullable?: boolean; 
  description?: string; 
  onDelete?: "CASCADE" | "RESTRICT" | "SET NULL"; 
  isEager?: boolean; 
  index?: boolean; 
}

- uniques (optional): Array of unique constraints (e.g., [["slug"], ["email", "username"]])
- indexes (optional): Array of index definitions

Output:
{
  success: boolean;
  total: number;
  succeeded: number;
  failed: number;
  results: Array<{success: boolean; tableName: string; tableId?: number; error?: string; message?: string}>;
  errors?: Array<{index: number; tableName: string; error: string; message: string}>;
  reloadAdminUI: boolean;
  summary: string;
  message: string;
}

Examples:
create_tables({"tables":[{"name":"products","columns":[{"name":"id","type":"int","isPrimary":true,"isGenerated":true},{"name":"name","type":"varchar"}]}]})

Detailed workflows, step-by-step instructions, and validation rules are provided in the "RELEVANT WORKFLOWS & RULES" section of your system prompt if available.`,
    parameters: {
      type: 'object',
      properties: {
        tables: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              description: { type: 'string' },
              columns: { type: 'array', items: { type: 'object' } },
              relations: { type: 'array', items: { type: 'object' } },
              uniques: { type: 'array', items: { type: 'array', items: { type: 'string' } } },
              indexes: { type: 'array', items: { type: 'object' } },
            },
            required: ['name', 'columns'],
          },
        },
      },
      required: ['tables'],
    },
  },
  {
    name: 'update_tables',
    description: `Purpose → Update one or multiple existing tables. Processes tables sequentially internally to avoid deadlocks.

SCHEMA LOCK - ONE TABLE PER CALL:
- Pass exactly 1 table per call, wait for result, then call again for next table
- Passing multiple tables causes "Schema is being updated" and most will fail

Inputs:
- tables (required): Array of table update objects. For single table, use array with 1 element.

Each table object:
- tableName (required): Table name to update (must exist)
- tableId (optional): Table ID for faster lookup
- description (optional): New table description
- columns (optional): Array of column definition objects to add/update. Merged by name. Schema same as create_tables.
- relations (optional): Array of relation definition objects to add/update. Merged by propertyName. Schema same as create_tables.

**CRITICAL - Relation Update Limitations:**
- You CAN update relation properties: propertyName, targetTable, isNullable, description
- You CANNOT update relation type (many-to-one, one-to-many, one-to-one, many-to-many)
- Relation type is IMMUTABLE - to change type, you MUST delete the existing relation first, then create a new one
- Workflow to change relation type: delete existing relation → create new relation with different type

- uniques (optional): Array of unique constraints (replaces existing)
- indexes (optional): Array of index definitions (replaces existing)

Output:
{
  success: boolean;
  total: number;
  succeeded: number;
  failed: number;
  results: Array<{success: boolean; tableName: string; tableId?: number; updated?: string; error?: string; message?: string}>;
  errors?: Array<{index: number; tableName?: string; tableId?: number; error: string; message: string}>;
  reloadAdminUI: boolean;
  summary: string;
  message: string;
}

Examples:
update_tables({"tables":[{"tableName":"products","columns":[{"name":"stock","type":"int"}]}]})

Detailed workflows and step-by-step instructions are provided in the "RELEVANT WORKFLOWS & RULES" section of your system prompt if available.`,
    parameters: {
      type: 'object',
      properties: {
        tables: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              tableId: { type: 'number' },
              tableName: { type: 'string' },
              description: { type: 'string' },
              columns: { type: 'array', items: { type: 'object' } },
              relations: { type: 'array', items: { type: 'object' } },
              uniques: { type: 'array', items: { type: 'array', items: { type: 'string' } } },
              indexes: { type: 'array', items: { type: 'object' } },
            },
            required: ['tableName'],
          },
        },
      },
      required: ['tables'],
    },
  },
  {
    name: 'delete_tables',
    description: `Purpose → Delete one or multiple tables by their IDs. This tool permanently removes the table structure and all its data. Processes tables sequentially internally.

SCHEMA LOCK - ONE TABLE PER CALL:
- Pass exactly 1 id per call, wait for result, then call again for next table
- Passing multiple ids causes "Schema is being updated" and most deletes will fail
- Example: 10 tables → delete_tables({"ids":[1]}), wait → delete_tables({"ids":[2]}), etc.

CRITICAL - Find Table IDs First:
- This tool ONLY accepts table IDs (array of numbers), NOT table names
- BEFORE calling this tool, you MUST find the table IDs first using find_records or get_table_details
- Extract the id(s) (number) from the result and use them in this tool
- NEVER use table name as id - this tool only accepts numeric ids

Inputs:
- ids (required): Array of table IDs (numbers) from table_definition. Must be found first using find_records or get_table_details. For single table, use array with 1 element: [123].

Output:
{
  success: boolean;
  total: number;
  succeeded: number;
  failed: number;
  results: Array<{success: boolean; id: number; name?: string; error?: string; message?: string}>;
  errors?: Array<{index: number; id: number; error: string; message: string}>;
  summary: string;
  message: string;
  reloadAdminUI: boolean;
}

Basic example:
- delete_tables({"ids":[123]})

Detailed workflows and step-by-step instructions are provided in the "RELEVANT WORKFLOWS & RULES" section of your system prompt if available.`,
    parameters: {
      type: 'object',
      properties: {
        ids: {
          type: 'array',
          items: { type: 'number' },
          description: 'Array of table IDs (numbers) from table_definition. Must be found first using find_records({"table":"table_definition","filter":{"name":{"_eq":"table_name"}},"fields":"id,name","limit":1}) or get_table_details. For single table, use array with 1 element: [123].',
        },
      },
      required: ['ids'],
    },
  },
  {
    name: 'update_task',
    description: `Purpose → manage task state in conversation.

Use when:
- Starting a new task (create task with status='pending' or 'in_progress')
- Updating task progress (status='in_progress', add data/result)
- Completing task (status='completed' with result)
- Cancelling task (status='cancelled')
- Task failed (status='failed' with error)

CRITICAL - Task Conflict Detection:
- Before creating a new task, check if conversation already has a task with status='pending' or 'in_progress'
- If new task type conflicts with existing task (e.g., create vs delete), cancel existing task first (status='cancelled')
- If new task is continuation of existing task, update existing task instead of creating new one

Task types:
- create_tables: Creating new tables
- update_tables: Updating existing tables
- delete_tables: Deleting tables
- custom: Other custom tasks

Task status flow:
- pending → in_progress → completed/failed/cancelled

Inputs:
- conversationId (required): Current conversation ID
- type (required): Task type (create_tables|update_tables|delete_tables|custom)
- status (required): Task status (pending|in_progress|completed|cancelled|failed)
- data (optional): Task-specific data (e.g., table names, operations)
- result (optional): Task result when completed
- error (optional): Error message when failed
- priority (optional): Task priority (default: 0, higher = more priority)

Returns:
{
  success: boolean;
  task: {
    id: number | string;
    conversationId: number | string;
    type: "create_tables" | "update_tables" | "delete_tables" | "custom";
    status: "pending" | "in_progress" | "completed" | "cancelled" | "failed";
    data?: any;
    result?: any;
    error?: string;
    priority?: number;
    createdAt?: string;
    updatedAt?: string;
  };
}`,
    parameters: {
      type: 'object',
      properties: {
        conversationId: {
          oneOf: [{ type: 'string' }, { type: 'number' }],
        },
        type: {
          type: 'string',
          enum: ['create_tables', 'update_tables', 'delete_tables', 'custom'],
        },
        status: {
          type: 'string',
          enum: ['pending', 'in_progress', 'completed', 'cancelled', 'failed'],
        },
        data: {
          type: 'object',
        },
        result: {
          type: 'object',
        },
        error: {
          type: 'string',
        },
        priority: {
          type: 'number',
          default: 0,
        },
      },
      required: ['conversationId', 'type', 'status'],
    },
  },
  {
    name: 'get_task',
    description: `Purpose → Check current task status of the conversation.

Use when:
- Before creating new task, check if there is a pending/in_progress task
- Display or remind user of current task progress
- Decide to cancel/update task based on current status

Inputs:
- conversationId (optional): Conversation ID. If omitted, tool uses context.$params.conversationId

Output:
{
  success: boolean;
  task: {
    type?: string;
    status?: string;
    priority?: number;
    data?: any;
    result?: any;
    error?: string;
    createdAt?: string;
    updatedAt?: string;
  } | null;
  message?: string;
  error?: boolean;
  errorCode?: string;
}
`,
    parameters: {
      type: 'object',
      properties: {
        conversationId: {
          oneOf: [{ type: 'string' }, { type: 'number' }],
          description: 'Conversation ID. If omitted, taken from context.$params.conversationId.',
        },
      },
    },
  },
  {
    name: 'find_records',
    description: `Purpose → Find/query records in a table, or count records using meta parameter.

CRITICAL - NEVER Select All, ALWAYS Filter and Specify Fields:
- NEVER use "*" or omit fields parameter - ALWAYS specify minimal fields needed (e.g., "id", "id,name")
- NEVER query all records without filter - ALWAYS use filter parameter (same as @QUERY.filter in pre-hook)

Permission: Auto-checked for business tables. Fails with clear error if denied.

CRITICAL - Field Names Check:
- BEFORE using fields parameter: You MUST call get_table_details FIRST to verify field names
- Field names must match exactly (snake_case vs camelCase)

CRITICAL - COUNT Queries (Counting Records):
- To count TOTAL number of records: fields="id", limit=1, meta="totalCount" (omit where or set to null)
- To count records WITH a filter: fields="id", limit=1, filter={filter conditions}, meta="filterCount"
- Read the totalCount or filterCount value from the response metadata
- NEVER use limit=0 just to count - always use limit=1 with appropriate meta parameter

Examples:
- Find: find_records({"table":"product","filter":{"price":{"_gt":100}},"fields":"id,name","limit":10})
- Count: find_records({"table":"product","fields":"id","limit":1,"meta":"totalCount"})

Detailed workflows, filtering strategies, and best practices are provided in the "RELEVANT WORKFLOWS & RULES" section of your system prompt if available.`,
    parameters: {
      type: 'object',
      properties: {
        table: {
          type: 'string',
          description: 'Name of the table to query.',
        },
        filter: {
          type: 'object',
          description:
            'Filter conditions (same as @QUERY.filter in pre-hook). Operators: _eq,_neq,_gt,_gte,_lt,_lte,_contains,_starts_with,_ends_with,_between,_in,_not_in,_is_null,_is_not_null. Logical: _and,_or,_not. Use _contains for case-insensitive partial match (NOT _icontains).',
        },
        fields: {
          type: 'string',
          description:
            'REQUIRED. Fields to return. Use get_table_details for available fields, then specify ONLY needed fields (e.g., "id" for count, "id,name" for list). Supports wildcards like "columns.*", "relations.*". CRITICAL: NEVER use "*" or omit fields parameter - this returns all fields and wastes tokens. ALWAYS specify minimal fields needed.',
        },
        limit: {
          type: 'number',
          description:
            'Max records to return. 0 = no limit (fetch all), > 0 = specified number. Default: 10. For counting, use limit=1 with meta parameter.',
        },
        sort: {
          type: 'string',
          description:
            'Sort field(s). Format: "fieldName" (ascending) or "-fieldName" (descending). Multi-field: comma-separated, e.g., "name,-createdAt". Examples: "createdAt", "-createdAt", "name,-price". Default: "id".',
        },
        meta: {
          type: 'string',
          enum: ['totalCount', 'filterCount'],
          description:
            'Optional. For counting records: "totalCount" to count all records (no filter), "filterCount" to count records matching filter. MUST use with limit=1 and fields="id". The count will be returned in response metadata.',
        },
      },
      required: ['table', 'fields'],
    },
  },
  {
    name: 'create_records',
    description: `Purpose → Create one or multiple records in a table. Processes records sequentially internally.

Permission: Auto-checked for business tables. Fails with clear error if denied.

CRITICAL - Schema Check Required:
- BEFORE create operations: You MUST call get_table_details FIRST to check the table schema
- Schema check ensures: all required fields included, column names match, relations format correct, data types match

CRITICAL - Check Unique Constraints Before Create:
- BEFORE create operations: You MUST check if records with unique field values already exist using find_records
- If record exists, skip creation or use update_records instead - duplicate unique values will cause errors

CRITICAL - Relations Format:
- Use propertyName from relations[].propertyName (e.g. "role", "category"). NEVER use foreignKeyColumn (roleId, categoryId)
- Format: {"propertyName": {id: value}} - Example: {"role": {id: 1}}, {"category": {id: 19}}
- NEVER include isSystem, isRootAdmin in dataArray - they have defaults; for registration/signup, set server-side in handler logic

CRITICAL - route_definition: NEVER include mainTable in dataArray. mainTable is system-managed, agent MUST NOT set it. Example: { path: "/register", isEnabled: true }.

CRITICAL - DO NOT Include ID in Create Operations:
- NEVER include "id" field in data - including id will cause errors

Inputs:
- table (required): Name of the table to create records in
- dataArray (required): Array of data objects. For single record, use array with 1 element. DO NOT include "id" field in any data object.
- fields (optional): Fields to return. ALWAYS specify minimal fields (e.g., "id" or "id,name") to save tokens.

Output:
{
  success: boolean;
  total: number;
  succeeded: number;
  failed: number;
  results: Array<{success: boolean; index: number; id?: number; error?: string; message?: string}>;
  errors?: Array<{index: number; error: string; message: string; data?: any}>;
  summary: string;
  message: string;
}

Examples:
create_records({"table":"product","dataArray":[{"name":"Laptop","price":999.99}],"fields":"id"})

Detailed workflows, step-by-step instructions, and best practices are provided in the "RELEVANT WORKFLOWS & RULES" section of your system prompt if available.`,
    parameters: {
      type: 'object',
      properties: {
        table: {
          type: 'string',
          description: 'Name of the table to create records in.',
        },
        dataArray: {
          type: 'array',
          items: {
            type: 'object',
          },
          description: 'Array of data objects for new records. CRITICAL: DO NOT include "id" field in any data object.',
        },
        fields: {
          type: 'string',
          description:
            'Fields to return. ALWAYS specify minimal fields (e.g., "id" or "id,name") to save tokens. Do NOT use "*" or omit fields parameter - this returns all fields and wastes tokens.',
        },
      },
      required: ['table', 'dataArray'],
    },
  },
  {
    name: 'update_records',
    description: `Purpose → Update one or multiple records by ID. Processes records sequentially internally.

Permission: Auto-checked for business tables. Fails with clear error if denied.

CRITICAL - Schema Check Required:
- BEFORE update operations: You MUST call get_table_details FIRST to check the table schema
- Schema check ensures: column names match, relations format correct, data types match

CRITICAL - Check Record Exists Before Update:
- BEFORE update operations: You MUST check if the record exists using find_records
- If record does not exist, skip update or report error

CRITICAL - Relations Format:
- Use propertyName from relations[].propertyName (e.g. "role", "category"). NEVER use foreignKeyColumn (roleId, categoryId)
- Format: {"propertyName": {id: value}} - Example: {"role": {id: 1}}

CRITICAL - route_definition: NEVER include mainTable in updates. mainTable is system-managed, agent MUST NOT set it.

Inputs:
- table (required): Name of the table to update records in
- updates (required): Array of update objects. For single record, use array with 1 element. Each object: {id: number|string, data: object}
- fields (optional): Fields to return. ALWAYS specify minimal fields (e.g., "id" or "id,name") to save tokens.

Output:
{
  success: boolean;
  total: number;
  succeeded: number;
  failed: number;
  results: Array<{success: boolean; index: number; id?: number|string; error?: string; message?: string}>;
  errors?: Array<{index: number; id?: number|string; error: string; message: string}>;
  summary: string;
  message: string;
}

Examples:
update_records({"table":"product","updates":[{"id":1,"data":{"price":899.99}}],"fields":"id"})

Detailed workflows, step-by-step instructions, and best practices are provided in the "RELEVANT WORKFLOWS & RULES" section of your system prompt if available.`,
    parameters: {
      type: 'object',
      properties: {
        table: {
          type: 'string',
          description: 'Name of the table to update records in.',
        },
        updates: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                oneOf: [{ type: 'string' }, { type: 'number' }],
              },
              data: {
                type: 'object',
              },
            },
            required: ['id', 'data'],
          },
          description: 'Array of update objects. Each object: {id: number|string, data: object}',
        },
        fields: {
          type: 'string',
          description:
            'Fields to return. ALWAYS specify minimal fields (e.g., "id" or "id,name") to save tokens. Do NOT use "*" or omit fields parameter - this returns all fields and wastes tokens.',
        },
      },
      required: ['table', 'updates'],
    },
  },
  {
    name: 'delete_records',
    description: `Purpose → Delete one or multiple records by ID. Processes records sequentially internally.

Permission: Auto-checked for business tables. Fails with clear error if denied.

CRITICAL - Check Record Exists Before Delete:
- BEFORE delete operations: You MUST check if the record exists using find_records
- If record does not exist, skip delete or report error

CRITICAL - Deleting Tables (NOT Data):
- To DELETE/DROP/REMOVE a TABLE (not data records), you MUST use the delete_tables tool
- NEVER use delete_records to delete tables - use delete_tables tool instead
- NEVER use delete_records on data tables to delete tables - this only deletes data records, not the table itself

Inputs:
- table (required): Name of the table to delete records from
- ids (required): Array of record IDs. For single record, use array with 1 element.

Output:
{
  success: boolean;
  total: number;
  succeeded: number;
  failed: number;
  results: Array<{success: boolean; index: number; id?: number|string; error?: string; message?: string}>;
  errors?: Array<{index: number; id?: number|string; error: string; message: string}>;
  summary: string;
  message: string;
}

Examples:
delete_records({"table":"product","ids":[1]})

Detailed workflows and best practices are provided in the "RELEVANT WORKFLOWS & RULES" section of your system prompt if available.`,
    parameters: {
      type: 'object',
      properties: {
        table: {
          type: 'string',
          description: 'Name of the table to delete records from.',
        },
        ids: {
          type: 'array',
          items: {
            oneOf: [{ type: 'string' }, { type: 'number' }],
          },
          description: 'Array of record IDs to delete.',
        },
      },
      required: ['table', 'ids'],
    },
  },
  {
    name: 'run_handler_test',
    description: `Purpose → Run custom handler logic in a sandboxed test environment. Use to verify handler code before saving to route_handler_definition.

CRITICAL - When to use:
- User wants to "test" or "try" handler logic before deploying
- MANDATORY: must run_handler_test before create/update route_handler_definition. After test: cleanup (delete test records).
- For update/delete handlers: create new record first, test on that record, then delete_records to cleanup. NEVER test on existing records.


Context in test:
- #<table_name>: DynamicRepository for the table (use #products for table "products")
- .find() → { data: [...] }; .create() → { data: [record], count?: 1 }; .update() → { data: [record] }. To get single record: created?.data?.[0], updated?.data?.[0]
- @BODY: request body (pass via body param)
- @PARAMS: route params (pass via params param)
- @HELPERS.$bcrypt: available for password hash/compare

Inputs:
- table (required): Table name for #<table_name> repo
- handlerCode (required): Handler code string. Must use return statement. Example: "return await #products.find({ limit: 5 });"
- body (optional): Simulated request body for @BODY
- params (optional): Simulated route params for @PARAMS (e.g. {"id": 1})
- query (optional): Simulated query for @QUERY. Use filter key (e.g. query: { filter: {} }). @QUERY.filter NOT @QUERY.where
- timeoutMs (optional): Max execution time in ms (default 10000)

Output when success: { success: true; result; logs? }

Output when error: { success: false; error; errorCode; errorKind; fixGuidance; nextSteps[]; location?; codeContext?; logs? }
- errorKind: SYNTAX_ERROR | REFERENCE_ERROR | TYPE_ERROR | SCRIPT_TIMEOUT | BUSINESS_LOGIC | RESOURCE_NOT_FOUND | VALIDATION_ERROR | DATABASE_QUERY | HELPER_NOT_FOUND | TABLE_NOT_FOUND | ...
- ALWAYS read fixGuidance and nextSteps when success=false. Fix the code per guidance, then retry run_handler_test.

Example:
run_handler_test({"table":"products","handlerCode":"return await #products.find({ limit: 3 });"})
run_handler_test({"table":"user_definition","handlerCode":"return await #user_definition.find({ filter: { email: { _eq: @BODY.email } }, limit: 1 });","body":{"email":"test@example.com"}})`,
    parameters: {
      type: 'object',
      properties: {
        table: {
          type: 'string',
          description: 'Table name for the DynamicRepository (#table_name in handler).',
        },
        handlerCode: {
          type: 'string',
          description: 'Handler code to execute. Use #<table_name>, @BODY, @PARAMS. Must return a value.',
        },
        body: {
          type: 'object',
          description: 'Optional. Simulated request body for @BODY in handler.',
        },
        params: {
          type: 'object',
          description: 'Optional. Simulated route params for @PARAMS (e.g. { id: 1 }).',
        },
        query: {
          type: 'object',
          description: 'Optional. Simulated @QUERY. Use filter, fields, limit, sort, page. CRITICAL: use filter NOT where (e.g. { filter: {} }).',
        },
        timeoutMs: {
          type: 'number',
          description: 'Optional. Max execution time in ms. Default 10000.',
        },
      },
      required: ['table', 'handlerCode'],
    },
  },
];

export type { ToolDefinition };

