import type {
  RuntimeSchemaColumnContract,
  RuntimeSchemaConstraintConflict,
  RuntimeSchemaNormalizationOptions,
  RuntimeSchemaRelationContract,
  RuntimeTableSchemaContract,
} from '../types/runtime-schema-mutation.types';
import { getSqlAutoGeneratedIndexLogicalGroups } from '../../../engines/knex/utils/sql-physical-schema-contract';
import { buildMongoFullIndexSpecs } from '../../../engines/mongo';
import { getForeignKeyColumnName } from '@enfyra/kernel';
import { getSqlJunctionPhysicalNames } from './sql-junction-naming.util';

export interface KeyedRuntimeSchemaColumn extends RuntimeSchemaColumnContract {
  key: string;
}

export interface NormalizedRuntimeTableSchema {
  contract: RuntimeTableSchemaContract;
  keyedColumns: readonly KeyedRuntimeSchemaColumn[];
}

export function normalizeRuntimeTableSchema(
  metadata: unknown,
  options: RuntimeSchemaNormalizationOptions = {},
): NormalizedRuntimeTableSchema | null {
  if (!metadata || typeof metadata !== 'object') return null;
  const value = metadata as Record<string, any>;
  const tableName = stringValue(value.name);
  const keyedColumns = (Array.isArray(value.columns) ? value.columns : [])
    .map((column: any) => {
      const isMongoPrimary =
        options.backend === 'mongodb' &&
        column?.isPrimary === true &&
        (column?.name === 'id' || column?.name === '_id');
      return {
        key: stringValue(column?.id ?? column?._id ?? column?.name),
        name: isMongoPrimary ? '_id' : stringValue(column?.name),
        type: isMongoPrimary ? 'ObjectId' : stringValue(column?.type),
        isNullable: column?.isNullable ?? true,
        isPrimary: !!column?.isPrimary,
        isGenerated: !!column?.isGenerated,
        defaultValue: normalizeJsonValue(column?.defaultValue ?? null),
        description: stringValue(column?.description),
        values: normalizeJsonValue(column?.values ?? null),
        isUnique: !!column?.isUnique,
        isPublished: column?.isPublished ?? true,
        isUpdatable: column?.isUpdatable ?? true,
        isEncrypted: !!column?.isEncrypted,
        isIndex: !!column?.isIndex,
        options: normalizeJsonValue(column?.options ?? null),
        metadata: normalizeJsonValue(column?.metadata ?? null),
        placeholder: stringValue(column?.placeholder),
      };
    })
    .sort((left, right) =>
      `${left.key}|${left.name}`.localeCompare(`${right.key}|${right.name}`),
    );
  const columns = keyedColumns
    .map(({ key: _key, ...column }) => column)
    .sort((left, right) => left.name.localeCompare(right.name));
  const relations = normalizeRelations(value.relations, tableName, options);
  const indexes = normalizeEffectiveIndexes(
    value.indexes,
    options,
    tableName,
    columns,
    relations,
  );
  return {
    contract: {
      name: tableName,
      description: stringValue(value.description),
      alias: stringValue(value.alias),
      isSingleRecord: !!value.isSingleRecord,
      graphqlEnabled: value.graphqlEnabled ?? true,
      validateBody: value.validateBody ?? true,
      columns,
      relations,
      uniques: normalizeConstraintValue(value.uniques),
      indexes,
    },
    keyedColumns,
  };
}

function normalizeEffectiveIndexes(
  value: unknown,
  options: RuntimeSchemaNormalizationOptions,
  tableName: string,
  columns: readonly RuntimeSchemaColumnContract[],
  relations: readonly RuntimeSchemaRelationContract[],
): unknown {
  const normalized = normalizeConstraintValue(value);
  if (!options.backend) {
    return normalized;
  }
  const explicit = Array.isArray(normalized) ? normalized : [];
  const constraints = parseConstraintGroups(explicit);
  const generated =
    options.backend === 'mongodb'
      ? buildMongoFullIndexSpecs({
          collectionName: tableName,
          indexes: constraints,
          columns: columns as any[],
          relations: relations as any[],
        })
          .filter((spec) => spec.autoGenerated)
          .map((spec) => spec.logicalFields)
      : getSqlAutoGeneratedIndexLogicalGroups(tableName, {
          indexes: constraints,
          columns: columns as any[],
          relations: relations as any[],
        });
  const seen = new Set(
    explicit.map((group) => JSON.stringify(normalizeJsonValue(group))),
  );
  return normalizeConstraintValue([
    ...explicit,
    ...generated.filter((group) => {
      const key = JSON.stringify(normalizeJsonValue(group));
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    }),
  ]);
}

export function runtimeRelationDiffKey(
  relation: RuntimeSchemaRelationContract,
): string {
  return `${relation.propertyName}|${relation.type}|${relation.targetTableName}|${relation.mappedBy}|${relation.foreignKeyColumn}|${relation.junctionTableName}|${relation.inversePropertyName}`;
}

export function findRuntimeSchemaConstraintConflicts(
  metadata: unknown,
): RuntimeSchemaConstraintConflict[] {
  if (!metadata || typeof metadata !== 'object') return [];
  const value = metadata as Record<string, unknown>;
  const uniqueGroups = parseConstraintGroups(value.uniques);
  if (uniqueGroups.length === 0) return [];
  return parseConstraintGroups(value.indexes)
    .map((index) => {
      const uniqueConstraints = uniqueGroups
        .map((fields) => ({
          fields,
          matchingFields: index.filter((field) => fields.includes(field)),
        }))
        .filter(({ matchingFields }) => matchingFields.length > 0);
      return {
        index,
        uniqueFields: [
          ...new Set(
            uniqueConstraints.flatMap(({ matchingFields }) => matchingFields),
          ),
        ],
        uniqueConstraints,
      };
    })
    .filter((conflict) => conflict.uniqueFields.length > 0);
}

function normalizeRelations(
  relations: unknown,
  tableName: string,
  options: RuntimeSchemaNormalizationOptions,
): RuntimeSchemaRelationContract[] {
  return (Array.isArray(relations) ? relations : [])
    .map((relation: any) => {
      const propertyName = stringValue(relation?.propertyName);
      const type = stringValue(relation?.type);
      const targetTableName = stringValue(
        relation?.targetTableName ??
          relation?.targetTable?.name ??
          relation?.targetTable,
      );
      const mappedBy = relationReferenceValue(
        relation?.mappedBy ??
          relation?.mappedById ??
          relation?.mappedByRelationId,
      );
      const ownsForeignKey =
        (type === 'many-to-one' || type === 'one-to-one') && !mappedBy;
      const generatedJunction =
        type === 'many-to-many' &&
        !mappedBy &&
        tableName &&
        propertyName &&
        targetTableName
          ? getSqlJunctionPhysicalNames({
              sourceTable: tableName,
              propertyName,
              targetTable: targetTableName,
            }).junctionTableName
          : '';
      return {
        propertyName,
        type,
        targetTableName,
        mappedBy,
        foreignKeyColumn:
          stringValue(relation?.foreignKeyColumn) ||
          (ownsForeignKey
            ? options.backend === 'mongodb'
              ? propertyName
              : getForeignKeyColumnName(propertyName)
            : ''),
        junctionTableName:
          stringValue(relation?.junctionTableName) || generatedJunction,
        isNullable: relation?.isNullable ?? true,
        onDelete: stringValue(relation?.onDelete) || 'SET NULL',
        inversePropertyName:
          options.mode === 'persisted'
            ? ''
            : stringValue(relation?.inversePropertyName),
        description: stringValue(relation?.description),
        isEager: !!relation?.isEager,
        isInverseEager: !!relation?.isInverseEager,
        isPublished: relation?.isPublished ?? true,
        isUpdatable: relation?.isUpdatable ?? true,
      };
    })
    .sort((left, right) =>
      runtimeRelationDiffKey(left).localeCompare(runtimeRelationDiffKey(right)),
    );
}

function normalizeConstraintValue(value: unknown): unknown {
  if (value == null) return [];
  const parsed = parseJson(value);
  if (!Array.isArray(parsed)) return normalizeJsonValue(parsed);
  return parsed
    .map((entry) => normalizeJsonValue(entry))
    .sort((left, right) =>
      JSON.stringify(left).localeCompare(JSON.stringify(right)),
    );
}

function parseConstraintGroups(value: unknown): string[][] {
  const parsed = parseJson(value);
  if (!Array.isArray(parsed)) return [];
  return parsed
    .map((group: any) => {
      const fields = Array.isArray(group) ? group : group?.value;
      if (!Array.isArray(fields)) return null;
      const normalized = fields
        .map((field: unknown) => stringValue(field).trim())
        .filter(Boolean);
      return normalized.length > 0 ? normalized : null;
    })
    .filter((group: string[] | null): group is string[] => group !== null);
}

function parseJson(value: unknown): unknown {
  if (typeof value !== 'string') return value;
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

function normalizeJsonValue(value: unknown): unknown {
  if (value == null || typeof value !== 'object') return value;
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(normalizeJsonValue);
  if (typeof (value as { toHexString?: unknown }).toHexString === 'function') {
    return String(value);
  }
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, nested]) => [key, normalizeJsonValue(nested)]),
  );
}

function relationReferenceValue(value: unknown): string {
  if (value == null) return '';
  if (typeof value !== 'object') return String(value);
  const reference = value as Record<string, unknown>;
  return stringValue(
    reference.propertyName ??
      reference.name ??
      reference.id ??
      reference._id,
  );
}

function stringValue(value: unknown): string {
  return value == null ? '' : String(value);
}
