import type { Queue } from 'bullmq';
import type { EventEmitter2 } from 'eventemitter2';
import type { Request, Response } from 'express';
import type Redis from 'ioredis';
import type { ConfigService } from '../shared/interfaces/config-service.interface';
import type { RequestWithRouteData, TDynamicContext } from '../shared/types/dynamic-context.types';
import type { EnvService, DatabaseConfigService, InstanceService, DynamicContextFactory, RuntimeMetricsCollectorService, ClusterTelemetryService } from '../shared/services';
import type { CommonService } from '../shared/common';
import type { UploadFileHelper } from '../shared/helpers';
import type { BcryptService, AuthService, ApiTokenService, PatVerifierService, JwtVerifierService, AuthenticationService, OAuthService, OAuthExchangeCodeService, SessionCleanupService, UserRevocationService } from '../domain/auth';
import type { LoggingService } from '../domain/exceptions';
import type { PolicyService, SchemaMigrationValidatorService, SystemSafetyAuditorService } from '../domain/policy';
import type { EnfyraKernel, QueryBuilderService, IsolatedExecutorService, ExecutorEngineService as KernelExecutorEngineService } from '@enfyra/kernel';
import type { KnexService, KnexHookManagerService, MigrationJournalService, MySqlRuntimeWriteBarrierService, ReplicationManager, SchemaMigrationLockService, SqlPoolClusterCoordinatorService, SqlSchemaDiffService, SqlSchemaMigrationService } from '../engines/knex';
import type { MongoMigrationJournalService, MongoPhysicalMigrationService, MongoSagaSnapshotService, MongoHookManagerService, MongoRelationManagerService, MongoSagaCoordinator, MongoSagaLockService, MongoSchemaDiffService, MongoSchemaMigrationLockService, MongoSchemaMigrationService, MongoService } from '../engines/mongo';
import type { SqlFunctionService } from '../engines/sql';
import type { AuthHeaderCacheBuilder, CacheOrchestratorService, FieldPermissionCacheBuilder, ColumnRuleCacheBuilder, FlowCacheBuilder, FolderTreeCacheService, GqlDefinitionCacheService, GuardAlertService, GuardCacheBuilder, GuardEvaluatorService, MetadataCacheService, OAuthConfigCacheBuilder, PackageCacheService, PackageCdnLoaderService, PackageRuntimeService, RateLimitService, RedisPubSubService, RedisRuntimeCacheStore, RedisCacheService, RepoRegistryService, RouteCacheService, RuntimeNamespaceLifecycleService, RuntimeRegistryService, RuntimeReloadAuditService, RuntimeScriptRepairService, SettingCacheService, StorageConfigCacheBuilder, WebsocketCacheBuilder } from '../engines/cache';
import type { RuntimeScriptExecutorService } from '../engines/cache';
import type { DynamicRepositoryFactory, DynamicService, DynamicApiTableValidationService, GuardValidationService } from '../modules/dynamic-api';
import type { TableHandlerService, SqlTableCreateService, SqlTableUpdateService, SqlTableDeleteService, SqlTableHandlerService, MongoTableCreateService, MongoTableUpdateService, MongoTableDeleteService, MongoTableHandlerService, TableManagementValidationService, MongoMetadataSnapshotService, SqlTableMetadataBuilderService, SqlTableMetadataWriterService, RuntimeSchemaContractCompilerService, RuntimeSchemaPhysicalPlannerService, RuntimeMetadataSchemaRouterService, RuntimeSchemaExecutorService, RuntimeSchemaTargetAttestorService, RuntimeSchemaUnitOfWorkService, RuntimeSchemaJournalService, RuntimeSchemaActivationGateService } from '../modules/table-management';
import type { FileManagementService, FileAssetsService, GCSStorageService, LocalStorageService, R2StorageService, S3StorageService, StorageFactoryService } from '../modules/file-management';
import type { RuntimeLogWriterService, RuntimeMonitorService, RuntimeDbMetricsService, RuntimeProcessMetricsService, RuntimeQueueMetricsService, RedisAdminService } from '../modules/admin';
import type { MeService } from '../modules/me';
import type { GraphqlService, DynamicResolver } from '../modules/graphql';
import type { FlowExecutionQueueService, FlowQueueMaintenanceService, FlowRuntimeService, FlowSchedulerService, FlowTriggerDispatcherService, FlowService } from '../modules/flow';
import type { DynamicWebSocketGateway, BuiltInSocketRegistry, WebsocketEmitService, WebsocketContextFactory, WebsocketRuntimeService } from '../modules/websocket';
import type { BootstrapScriptService, BootstrapScriptDefinitionProcessor, ExtensionDefinitionProcessor, FlowDefinitionProcessor, FlowExecutionDefinitionProcessor, FlowStepDefinitionProcessor, FolderDefinitionProcessor, GraphQLDefinitionProcessor, GraphQLOperationDefinitionProcessor, MenuDefinitionProcessor, MethodDefinitionProcessor, PostHookDefinitionProcessor, PreHookDefinitionProcessor, FieldPermissionDefinitionProcessor, RouteDefinitionProcessor, RouteHandlerDefinitionProcessor, RoutePermissionDefinitionProcessor, SettingDefinitionProcessor, UserDefinitionProcessor, WebsocketDefinitionProcessor, WebsocketEventDefinitionProcessor } from '../domain/bootstrap';
import type { BootstrapDefinitionService, BootstrapUnitOfWorkService, DataMigrationService, DataProvisionService, FirstRunInitializer, MetadataMigrationService, MySqlBootstrapSnapshotService, MetadataProvisionMongoService, MetadataProvisionSqlService, MetadataProvisionService, ProvisionService, SchemaHealingService, SnapshotTargetVerifierService, SystemCoreTableResolver, LegacyStoreInventoryService, LegacyAssessmentService } from '../engines/bootstrap';

export interface Cradle {
  envService: EnvService;
  eventEmitter: EventEmitter2;
  redis: Redis;

  commonService: CommonService;
  databaseConfigService: DatabaseConfigService;
  instanceService: InstanceService;
  dynamicContextFactory: DynamicContextFactory;
  runtimeMetricsCollectorService: RuntimeMetricsCollectorService;
  clusterTelemetryService: ClusterTelemetryService;
  configService: ConfigService;
  lazyRef: Cradle;
  bcryptService: BcryptService;
  authService: AuthService;
  apiTokenService: ApiTokenService;
  patVerifierService: PatVerifierService;
  jwtVerifierService: JwtVerifierService;
  authenticationService: AuthenticationService;
  oauthService: OAuthService;
  oauthExchangeCodeService: OAuthExchangeCodeService;
  sessionCleanupService: SessionCleanupService;
  userRevocationService: UserRevocationService;
  loggingService: LoggingService;
  policyService: PolicyService;
  schemaMigrationValidatorService: SchemaMigrationValidatorService;
  runtimeSchemaContractCompilerService: RuntimeSchemaContractCompilerService;
  runtimeSchemaPhysicalPlannerService: RuntimeSchemaPhysicalPlannerService;
  runtimeMetadataSchemaRouterService: RuntimeMetadataSchemaRouterService;
  runtimeSchemaExecutorService: RuntimeSchemaExecutorService;
  runtimeSchemaTargetAttestorService: RuntimeSchemaTargetAttestorService;
  runtimeSchemaUnitOfWorkService: RuntimeSchemaUnitOfWorkService;
  runtimeSchemaJournalService: RuntimeSchemaJournalService;
  runtimeSchemaActivationGateService: RuntimeSchemaActivationGateService;
  systemSafetyAuditorService: SystemSafetyAuditorService;

  mongoService: MongoService;
  mongoSchemaMigrationService: MongoSchemaMigrationService;
  mongoSchemaMigrationLockService: MongoSchemaMigrationLockService;
  mongoSagaLockService: MongoSagaLockService;
  mongoSagaCoordinator: MongoSagaCoordinator;
  mongoSagaSnapshotService: MongoSagaSnapshotService;
  mongoMigrationJournalService: MongoMigrationJournalService;
  mongoPhysicalMigrationService: MongoPhysicalMigrationService;
  mongoSchemaDiffService: MongoSchemaDiffService;
  mongoHookManagerService: MongoHookManagerService;
  mongoRelationManagerService: MongoRelationManagerService;

  knexService: KnexService;
  knexHookManagerService: KnexHookManagerService;
  replicationManager: ReplicationManager;
  sqlSchemaMigrationService: SqlSchemaMigrationService;
  sqlSchemaDiffService: SqlSchemaDiffService;
  migrationJournalService: MigrationJournalService;
  mySqlRuntimeWriteBarrierService: MySqlRuntimeWriteBarrierService;
  schemaMigrationLockService: SchemaMigrationLockService;
  sqlPoolClusterCoordinatorService: SqlPoolClusterCoordinatorService;
  sqlFunctionService: SqlFunctionService;

  enfyraKernel: EnfyraKernel;
  queryBuilderService: QueryBuilderService;

  isolatedExecutorService: IsolatedExecutorService;
  kernelExecutorEngineService: KernelExecutorEngineService;
  executorEngineService: RuntimeScriptExecutorService;

  cacheService: RedisCacheService;
  userCacheService: RedisCacheService;
  redisPubSubService: RedisPubSubService;
  runtimeNamespaceLifecycleService: RuntimeNamespaceLifecycleService;
  redisRuntimeCacheStore: RedisRuntimeCacheStore;
  metadataCacheService: MetadataCacheService;
  routeCacheService: RouteCacheService;
  packageCacheService: PackageCacheService;
  packageRuntimeService: PackageRuntimeService;
  storageConfigCacheBuilder: StorageConfigCacheBuilder;
  websocketCacheBuilder: WebsocketCacheBuilder;
  oauthConfigCacheBuilder: OAuthConfigCacheBuilder;
  rateLimitService: RateLimitService;
  folderTreeCacheService: FolderTreeCacheService;
  flowCacheBuilder: FlowCacheBuilder;
  packageCdnLoaderService: PackageCdnLoaderService;
  guardCacheBuilder: GuardCacheBuilder;
  guardEvaluatorService: GuardEvaluatorService;
  guardAlertService: GuardAlertService;
  settingCacheService: SettingCacheService;
  authHeaderCacheBuilder: AuthHeaderCacheBuilder;
  fieldPermissionCacheBuilder: FieldPermissionCacheBuilder;
  columnRuleCacheBuilder: ColumnRuleCacheBuilder;
  gqlDefinitionCacheService: GqlDefinitionCacheService;
  repoRegistryService: RepoRegistryService;
  runtimeRegistryService: RuntimeRegistryService;
  runtimeReloadAuditService: RuntimeReloadAuditService;
  runtimeScriptRepairService: RuntimeScriptRepairService;
  dynamicRepositoryFactory: DynamicRepositoryFactory;
  cacheOrchestratorService: CacheOrchestratorService;

  tableHandlerService: TableHandlerService;
  sqlTableCreateService: SqlTableCreateService;
  sqlTableUpdateService: SqlTableUpdateService;
  sqlTableDeleteService: SqlTableDeleteService;
  sqlTableHandlerService: SqlTableHandlerService;
  mongoTableCreateService: MongoTableCreateService;
  mongoTableUpdateService: MongoTableUpdateService;
  mongoTableDeleteService: MongoTableDeleteService;
  mongoTableHandlerService: MongoTableHandlerService;
  tableValidationService: DynamicApiTableValidationService;
  guardValidationService: GuardValidationService;
  tableManagementValidationService: TableManagementValidationService;
  mongoMetadataSnapshotService: MongoMetadataSnapshotService;
  sqlTableMetadataBuilderService: SqlTableMetadataBuilderService;
  sqlTableMetadataWriterService: SqlTableMetadataWriterService;

  dynamicService: DynamicService;

  fileManagementService: FileManagementService;
  fileAssetsService: FileAssetsService;
  localStorageService: LocalStorageService;
  gcsStorageService: GCSStorageService;
  r2StorageService: R2StorageService;
  s3StorageService: S3StorageService;
  storageFactoryService: StorageFactoryService;
  uploadFileHelper: UploadFileHelper;

  runtimeLogWriterService: RuntimeLogWriterService;
  runtimeMonitorService: RuntimeMonitorService;
  runtimeDbMetricsService: RuntimeDbMetricsService;
  runtimeProcessMetricsService: RuntimeProcessMetricsService;
  runtimeQueueMetricsService: RuntimeQueueMetricsService;
  redisAdminService: RedisAdminService;
  meService: MeService;
  graphqlService: GraphqlService;
  dynamicResolver: DynamicResolver;

  flowService: FlowService;
  flowQueueMaintenanceService: FlowQueueMaintenanceService;
  flowRuntimeService: FlowRuntimeService;
  flowSchedulerService: FlowSchedulerService;
  flowTriggerDispatcherService: FlowTriggerDispatcherService;
  flowExecutionQueueService: FlowExecutionQueueService;
  mongoPhysicalMigrationQueue: Queue;

  dynamicWebSocketGateway: DynamicWebSocketGateway;
  websocketRuntimeService: WebsocketRuntimeService;
  builtInSocketRegistry: BuiltInSocketRegistry;
  websocketEmitService: WebsocketEmitService;
  websocketContextFactory: WebsocketContextFactory;

  provisionService: ProvisionService;
  firstRunInitializer: FirstRunInitializer;
  schemaHealingService: SchemaHealingService;
  systemCoreTableResolver: SystemCoreTableResolver;
  legacyStoreInventoryService: LegacyStoreInventoryService;
  legacyAssessmentService: LegacyAssessmentService;
  metadataProvisionService: MetadataProvisionService;
  metadataProvisionSqlService: MetadataProvisionSqlService;
  metadataProvisionMongoService: MetadataProvisionMongoService;
  dataProvisionService: DataProvisionService;
  dataMigrationService: DataMigrationService;
  metadataMigrationService: MetadataMigrationService;
  snapshotTargetVerifierService: SnapshotTargetVerifierService;
  bootstrapDefinitionService: BootstrapDefinitionService;
  bootstrapUnitOfWorkService: BootstrapUnitOfWorkService;
  mySqlBootstrapSnapshotService: MySqlBootstrapSnapshotService;
  bootstrapScriptService: BootstrapScriptService;

  userDefinitionProcessor: UserDefinitionProcessor;
  menuDefinitionProcessor: MenuDefinitionProcessor;
  routeDefinitionProcessor: RouteDefinitionProcessor;
  routeHandlerDefinitionProcessor: RouteHandlerDefinitionProcessor;
  methodDefinitionProcessor: MethodDefinitionProcessor;
  preHookDefinitionProcessor: PreHookDefinitionProcessor;
  postHookDefinitionProcessor: PostHookDefinitionProcessor;
  fieldPermissionDefinitionProcessor: FieldPermissionDefinitionProcessor;
  settingDefinitionProcessor: SettingDefinitionProcessor;
  extensionDefinitionProcessor: ExtensionDefinitionProcessor;
  folderDefinitionProcessor: FolderDefinitionProcessor;
  bootstrapScriptDefinitionProcessor: BootstrapScriptDefinitionProcessor;
  routePermissionDefinitionProcessor: RoutePermissionDefinitionProcessor;
  websocketDefinitionProcessor: WebsocketDefinitionProcessor;
  websocketEventDefinitionProcessor: WebsocketEventDefinitionProcessor;
  flowDefinitionProcessor: FlowDefinitionProcessor;
  flowStepDefinitionProcessor: FlowStepDefinitionProcessor;
  flowExecutionDefinitionProcessor: FlowExecutionDefinitionProcessor;
  graphqlDefinitionProcessor: GraphQLDefinitionProcessor;
  graphqlOperationDefinitionProcessor: GraphQLOperationDefinitionProcessor;

  $req: RequestWithRouteData;
  $res: Response;
  $body: unknown;
  $query: Request['query'];
  $params: Request['params'];
  $user: unknown;
  $ctx: TDynamicContext | null;
}
