export interface MongoRelationLike {
  propertyName?: string;
  type?: string;
  targetTable?: string;
  targetTableName?: string;
  foreignKeyColumn?: string;
  mappedBy?: string;
  isInverse?: boolean;
}

export interface MongoStoredRelationContract {
  propertyName: string;
  type: string;
  storedField: string;
  targetTable?: string;
}

export interface MongoColumnLike {
  name?: string;
  type?: string;
  isPrimary?: boolean;
}

export interface MongoPhysicalIndexSpec {
  keys: Record<string, 1 | -1>;
  options: Record<string, any>;
  name: string;
  autoGenerated?: boolean;
  logicalFields: string[];
}
