export const API_TOKEN_TABLE = 'enfyra_api_token';
export const API_TOKEN_CACHE_PREFIX = 'auth:api-token';
export const API_TOKEN_REVOKED_CHANNEL = 'api-token:revoked';
export const API_TOKEN_STATE_TTL_MS = 60_000;
export const API_TOKEN_ACCESS_TTL_MS = API_TOKEN_STATE_TTL_MS;
export const API_TOKEN_STATE_REFRESH_WINDOW_MS = 15_000;
export const API_TOKEN_HARD_REVALIDATION_MS = 15 * 60_000;
export const API_TOKEN_REVOCATION_TOMBSTONE_TTL_MS =
  API_TOKEN_HARD_REVALIDATION_MS;
export const API_TOKEN_STATE_REVALIDATION_LOCK_TTL_MS = 5_000;
export const API_TOKEN_STATE_REVALIDATION_WAIT_MS = 1_000;
export const API_TOKEN_STATE_REVALIDATION_POLL_MS = 25;
export const API_TOKEN_LAST_USED_FLUSH_MS = 60_000;
export const API_TOKEN_LAST_USED_WRITE_INTERVAL_MS = 15 * 60_000;
export const API_TOKEN_LAST_USED_FLUSH_BATCH_SIZE = 1_000;
