import { asClass } from 'awilix';
import {
  BootstrapScriptDefinitionProcessor,
  ExtensionDefinitionProcessor,
  FlowDefinitionProcessor,
  FlowExecutionDefinitionProcessor,
  FlowStepDefinitionProcessor,
  FolderDefinitionProcessor,
  GraphQLDefinitionProcessor,
  GraphQLOperationDefinitionProcessor,
  MenuDefinitionProcessor,
  MethodDefinitionProcessor,
  PostHookDefinitionProcessor,
  PreHookDefinitionProcessor,
  FieldPermissionDefinitionProcessor,
  RouteDefinitionProcessor,
  RouteHandlerDefinitionProcessor,
  RoutePermissionDefinitionProcessor,
  SettingDefinitionProcessor,
  UserDefinitionProcessor,
  WebsocketDefinitionProcessor,
  WebsocketEventDefinitionProcessor,
  BootstrapScriptService,
} from '../../domain/bootstrap';
import {
  BootstrapDefinitionService,
  BootstrapUnitOfWorkService,
  DataMigrationService,
  DataProvisionService,
  FirstRunInitializer,
  MetadataMigrationService,
  MySqlBootstrapSnapshotService,
  MetadataProvisionMongoService,
  MetadataProvisionSqlService,
  MetadataProvisionService,
  ProvisionService,
  SchemaHealingService,
  SnapshotTargetVerifierService,
  SystemCoreTableResolver,
  LegacyStoreInventoryService,
  LegacyAssessmentService,
} from '../../engines/bootstrap';

export const bootstrapInfraRegisters = {
  provisionService: asClass(ProvisionService).singleton(),
  bootstrapDefinitionService: asClass(BootstrapDefinitionService).singleton(),
  bootstrapUnitOfWorkService: asClass(BootstrapUnitOfWorkService).singleton(),
  mySqlBootstrapSnapshotService: asClass(MySqlBootstrapSnapshotService).singleton(),
  firstRunInitializer: asClass(FirstRunInitializer).singleton(),
  schemaHealingService: asClass(SchemaHealingService).singleton(),
  systemCoreTableResolver: asClass(SystemCoreTableResolver).singleton(),
  legacyStoreInventoryService: asClass(LegacyStoreInventoryService).singleton(),
  legacyAssessmentService: asClass(LegacyAssessmentService).singleton(),
  metadataProvisionService: asClass(MetadataProvisionService).singleton(),
  metadataProvisionSqlService: asClass(MetadataProvisionSqlService).singleton(),
  metadataProvisionMongoService: asClass(MetadataProvisionMongoService).singleton(),
  dataProvisionService: asClass(DataProvisionService).singleton(),
  dataMigrationService: asClass(DataMigrationService).singleton(),
  metadataMigrationService: asClass(MetadataMigrationService).singleton(),
  snapshotTargetVerifierService: asClass(SnapshotTargetVerifierService).singleton(),
  bootstrapScriptService: asClass(BootstrapScriptService).singleton(),
} as const;

export const bootstrapProcessorRegisters = {
  userDefinitionProcessor: asClass(UserDefinitionProcessor).singleton(),
  menuDefinitionProcessor: asClass(MenuDefinitionProcessor).singleton(),
  routeDefinitionProcessor: asClass(RouteDefinitionProcessor).singleton(),
  routeHandlerDefinitionProcessor: asClass(RouteHandlerDefinitionProcessor).singleton(),
  methodDefinitionProcessor: asClass(MethodDefinitionProcessor).singleton(),
  preHookDefinitionProcessor: asClass(PreHookDefinitionProcessor).singleton(),
  postHookDefinitionProcessor: asClass(PostHookDefinitionProcessor).singleton(),
  fieldPermissionDefinitionProcessor: asClass(FieldPermissionDefinitionProcessor).singleton(),
  settingDefinitionProcessor: asClass(SettingDefinitionProcessor).singleton(),
  extensionDefinitionProcessor: asClass(ExtensionDefinitionProcessor).singleton(),
  folderDefinitionProcessor: asClass(FolderDefinitionProcessor).singleton(),
  bootstrapScriptDefinitionProcessor: asClass(BootstrapScriptDefinitionProcessor).singleton(),
  routePermissionDefinitionProcessor: asClass(RoutePermissionDefinitionProcessor).singleton(),
  websocketDefinitionProcessor: asClass(WebsocketDefinitionProcessor).singleton(),
  websocketEventDefinitionProcessor: asClass(WebsocketEventDefinitionProcessor).singleton(),
  flowDefinitionProcessor: asClass(FlowDefinitionProcessor).singleton(),
  flowStepDefinitionProcessor: asClass(FlowStepDefinitionProcessor).singleton(),
  flowExecutionDefinitionProcessor: asClass(FlowExecutionDefinitionProcessor).singleton(),
  graphqlDefinitionProcessor: asClass(GraphQLDefinitionProcessor).singleton(),
  graphqlOperationDefinitionProcessor: asClass(GraphQLOperationDefinitionProcessor).singleton(),
} as const;
