import { SnapshotDefinition, col, rel } from '../engines/bootstrap/definitions';

const snapshot = new SnapshotDefinition();

snapshot
  .table('enfyra_column', {
    description: 'Stores column/field definitions for all tables in the system',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('Column name in the database'),
    type: col
      .enum([
        'int',
        'varchar',
        'text',
        'boolean',
        'uuid',
        'ObjectId',
        'bigint',
        'date',
        'datetime',
        'timestamp',
        'enum',
        'simple-json',
        'code',
        'array-select',
        'richtext',
        'float',
      ])
      .notNull()
      .system()
      .description('Data type of the column'),
    isGenerated: col
      .boolean()
      .system()
      .default(false)
      .nullable()
      .description('Whether the value is auto-generated by the system'),
    isPrimary: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this column is a primary key'),
    isNullable: col
      .boolean()
      .system()
      .default(true)
      .description('Whether NULL values are allowed'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined column'),
    defaultValue: col
      .simpleJson()
      .system()
      .nullable()
      .description('Default value for the column when inserting new records'),
    options: col
      .simpleJson()
      .system()
      .nullable()
      .description(
        'Additional options like enum values, array items, or validation rules',
      ),
    isUpdatable: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the column can be updated after creation'),
    isPublished: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description(
        'Whether this column is publicly readable (public routes/anonymous included)',
      ),
    isEncrypted: col
      .boolean()
      .notNull()
      .system()
      .immutable()
      .default(false)
      .description(
        'Whether this column is encrypted at rest by the Enfyra engine',
      ),
    description: col
      .richtext()
      .system()
      .description("Rich text description of the column's purpose"),
    placeholder: col
      .text()
      .system()
      .description('Placeholder text for form inputs'),
    metadata: col
      .simpleJson()
      .system()
      .description('Additional metadata for the column'),
  })
  .relations({
    table: rel
      .manyToOne('enfyra_table')
      .inverse('columns')
      .system()
      .immutable()
      .onDelete('CASCADE')
      .description('The table that this column belongs to'),
  })
  .uniques([['name', 'table']]);

snapshot
  .table('enfyra_column_rule', {
    description:
      'Validation rules attached to columns (min/max/pattern/format/etc.)',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    ruleType: col
      .enum([
        'min',
        'max',
        'minLength',
        'maxLength',
        'pattern',
        'format',
        'minItems',
        'maxItems',
        'custom',
      ])
      .notNull()
      .system()
      .description('Type of validation rule'),
    value: col
      .simpleJson()
      .system()
      .nullable()
      .description(
        "Rule payload — shape depends on ruleType (e.g. {v: 10} for min/max, {v: 'email'} for format)",
      ),
    message: col
      .varchar()
      .system()
      .nullable()
      .description(
        'Custom error message when rule fails (falls back to default if null)',
      ),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this rule is active'),
    description: col.text().system().description('Admin note about this rule'),
  })
  .relations({
    column: rel
      .manyToOne('enfyra_column')
      .inverse('rules')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('The column this rule applies to'),
  });

snapshot
  .table('enfyra_relation', {
    description:
      'Defines relationships between tables (one-to-one, one-to-many, many-to-one, many-to-many)',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    type: col
      .enum(['one-to-one', 'many-to-one', 'one-to-many', 'many-to-many'])
      .notNull()
      .system()
      .description('Type of relationship between tables'),
    propertyName: col
      .varchar()
      .notNull()
      .system()
      .description('Property name for accessing the relation in queries'),
    isNullable: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the relation can be null'),
    onDelete: col
      .enum(['CASCADE', 'RESTRICT', 'SET NULL'])
      .notNull()
      .system()
      .default('SET NULL')
      .description('Action to perform when referenced record is deleted'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined relation'),
    isPublished: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description(
        'Whether this relation is publicly readable (public routes/anonymous included)',
      ),
    description: col
      .text()
      .system()
      .description('Description of the relationship purpose'),
    foreignKeyColumn: col
      .varchar()
      .system()
      .nullable()
      .description('Physical foreign key column used by SQL owning relations'),
    referencedColumn: col
      .varchar()
      .system()
      .nullable()
      .description('Physical target column referenced by SQL foreign keys'),
    constraintName: col
      .varchar()
      .system()
      .nullable()
      .description('Physical foreign key constraint name when known'),
    junctionTableName: col
      .varchar()
      .system()
      .nullable()
      .description('Name of the junction table for many-to-many relations'),
    junctionSourceColumn: col
      .varchar()
      .system()
      .nullable()
      .description('Column name in junction table referencing source table'),
    junctionTargetColumn: col
      .varchar()
      .system()
      .nullable()
      .description('Column name in junction table referencing target table'),
    metadata: col
      .simpleJson()
      .system()
      .description('Additional metadata for the relation'),
    isUpdatable: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description(
        'Whether this relation can be updated. When false, the foreign key column will be protected from updates.',
      ),
  })
  .relations({
    sourceTable: rel
      .manyToOne('enfyra_table')
      .inverse('relations')
      .system()
      .immutable()
      .onDelete('CASCADE')
      .description('The table where this relation is defined'),
    targetTable: rel
      .manyToOne('enfyra_table')
      .system()
      .immutable()
      .nullable()
      .description('The table that this relation points to'),
    mappedBy: rel
      .manyToOne('enfyra_relation')
      .system()
      .onDelete('CASCADE')
      .nullable()
      .description(
        'Owning-side relation that this inverse maps to (self-referencing FK)',
      ),
  })
  .uniques([['propertyName', 'sourceTable'], ['mappedBy']]);

snapshot
  .table('enfyra_table', {
    description: 'Stores metadata for all tables/collections in the database',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('Table name in the database'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system table'),
    isSingleRecord: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description(
        'Whether this table should only have a single record (e.g., enfyra_setting)',
      ),
    uniques: col
      .simpleJson()
      .system()
      .nullable()
      .description(
        "Array of unique constraints (e.g., [['email'], ['name', 'parent']])",
      ),
    indexes: col
      .simpleJson()
      .system()
      .nullable()
      .description('Array of database indexes for performance optimization'),
    alias: col
      .varchar()
      .system()
      .nullable()
      .description('Human-readable alias for the table'),
    description: col
      .text()
      .system()
      .description("Description of the table's purpose"),
    metadata: col
      .simpleJson()
      .system()
      .description('Additional metadata for the table'),
    validateBody: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description(
        'Auto-validate POST/PATCH bodies against column + relation metadata and column rules. Default true (opt-out per table); set false to skip middleware validation for a table',
      ),
  })
  .uniques([['name'], ['alias']]);

snapshot
  .table('enfyra_user', {
    description: 'Stores user accounts and authentication information',
    system: true,
  })
  .columns({
    id: col
      .uuid()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Unique user identifier (UUID)'),
    email: col
      .varchar()
      .notNull()
      .system()
      .default(null)
      .description("User's email address (unique login identifier)"),
    password: col
      .varchar()
      .system()
      .private()
      .nullable()
      .default(null)
      .description(
        'Hashed password for authentication (nullable for OAuth users)',
      ),
    isRootAdmin: col
      .boolean()
      .notNull()
      .system()
      .immutable()
      .default(false)
      .description(
        'Whether user has root admin privileges (cannot be changed)',
      ),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-generated user account'),
  })
  .relations({
    roles: rel.manyToMany('enfyra_role').system().description("User's assigned roles for permissions").junction({ table: 'enfyra_user_roles', source: 'userId', target: 'roleId' }),
  })
  .uniques([['email']]);

snapshot
  .table('enfyra_oauth_config', {
    description:
      'Configures OAuth providers for authentication (Google, Facebook, GitHub, etc.)',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    provider: col
      .enum(['google', 'facebook', 'github'])
      .notNull()
      .system()
      .description('OAuth provider name'),
    clientId: col
      .varchar()
      .notNull()
      .system()
      .private()
      .description('OAuth client ID from the provider'),
    clientSecret: col
      .varchar()
      .notNull()
      .system()
      .private()
      .description('OAuth client secret from the provider'),
    redirectUri: col
      .varchar()
      .notNull()
      .system()
      .description(
        'OAuth provider callback URL registered with the provider (e.g., https://api.enfyra.com/auth/google/callback)',
      ),
    appCallbackUrl: col
      .varchar()
      .system()
      .nullable()
      .description(
        'Client callback URL used when auto cookie handling is disabled. The backend redirects here with token query parameters.',
      ),
    autoSetCookies: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description(
        'When enabled, the backend redirects back to the Enfyra Nuxt app /api/auth/set-cookies endpoint and lets Nitro set auth cookies before redirecting to the requested page.',
      ),
    sourceCode: col
      .code()
      .system()
      .nullable()
      .default(null)
      .description(
        'Optional script that returns an object merged into newly created OAuth users. Existing identity fields take precedence.',
      ),
    scriptLanguage: col
      .enum(['typescript', 'javascript'])
      .notNull()
      .system()
      .default('typescript')
      .description('Language used by sourceCode before server compilation'),
    compiledCode: col
      .code()
      .generated()
      .system()
      .immutable()
      .nullable()
      .description(
        'Server-compiled JavaScript code executed by the OAuth user provisioning runtime',
      ),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this OAuth provider is active'),
    description: col
      .text()
      .system()
      .nullable()
      .description('Description of this OAuth configuration'),
  })
  .relations({})
  .uniques([['provider']]);

snapshot
  .table('enfyra_oauth_account', {
    description: 'Links user accounts to OAuth providers for authentication',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    provider: col
      .enum(['google', 'facebook', 'github'])
      .notNull()
      .system()
      .description('OAuth provider name'),
    providerUserId: col
      .varchar()
      .notNull()
      .system()
      .description('Unique user ID from the OAuth provider'),
  })
  .relations({
    user: rel
      .manyToOne('enfyra_user')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('The user account linked to this OAuth provider'),
  })
  .uniques([['provider', 'providerUserId']])
  .indexes([['user']]);

snapshot
  .table('enfyra_setting', {
    description: 'Stores global system configuration and settings',
    system: true,
    singleRecord: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    isInit: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether the system has been initialized'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether these are system settings'),
    projectName: col
      .varchar()
      .system()
      .description('Name of the project/application'),
    projectDescription: col
      .text()
      .system()
      .description('Description of the project/application'),
    projectFavicon: col
      .varchar()
      .system()
      .description('Favicon URL or path for the project/application'),
    maxQueryDepth: col
      .int()
      .system()
      .default(7)
      .nullable()
      .description(
        'Maximum nesting depth for REST deep-fetch and GraphQL queries (default: 7)',
      ),
    maxUploadFileSize: col
      .int()
      .system()
      .default(10)
      .nullable()
      .description('Maximum upload file size in MB (default: 10)'),
    maxRequestBodySize: col
      .int()
      .system()
      .default(1)
      .nullable()
      .description(
        'Maximum JSON/urlencoded request body size in MB (default: 1)',
      ),
    uniquesIndexesRepaired: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description(
        'Whether user-table uniques/indexes metadata has been repaired (one-time fix for fkColumn leak)',
      ),
  })
  .relations({});

snapshot
  .table('enfyra_auth_header', {
    description: 'Configures request headers accepted for authentication',
    system: true,
  })
  .columns({
    id: col.int().primary().generated().notNull().system().description('Primary key identifier'),
    headerKey: col.varchar().notNull().system().description('Request header name, normalized to lowercase'),
    credentialType: col.enum(['pat', 'jwt']).notNull().system().default('pat').description('Credential verifier used for this header'),
    scheme: col.enum(['raw', 'bearer']).notNull().system().default('raw').description('Whether the header contains a raw token or a Bearer token'),
    priority: col.int().notNull().system().default(0).description('Lower values are checked first when multiple headers are present'),
    isEnabled: col.boolean().notNull().system().default(true).description('Whether this header mapping is active'),
    isSystem: col.boolean().notNull().system().default(false).description('Whether this mapping is built-in and immutable'),
    description: col.text().system().nullable().description('Description of this authentication header mapping'),
  })
  .relations({});

snapshot
  .table('enfyra_cors_origin', {
    description:
      'Allowed CORS origins served by the public /enfyra_cors_origin endpoint',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    value: col
      .varchar()
      .notNull()
      .system()
      .description('Allowed origin URL (e.g., https://app.example.com)'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this origin is currently active'),
    description: col
      .text()
      .system()
      .nullable()
      .description('Optional note for this origin entry'),
  })
  .relations({})
  .uniques([['value']]);

snapshot
  .table('enfyra_route', {
    description: 'Defines API routes/endpoints for the application',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    path: col
      .varchar()
      .notNull()
      .system()
      .default(null)
      .description('URL path for the route (e.g., /api/users)'),
    isEnabled: col
      .boolean()
      .system()
      .default(true)
      .nullable()
      .description('Whether the route is active and accessible'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined route'),
    icon: col
      .varchar()
      .system()
      .default('lucide:route')
      .nullable()
      .description('Icon identifier for UI display'),
    maxUploadFileSize: col
      .int()
      .system()
      .nullable()
      .default(null)
      .description(
        'Optional route-specific maximum upload file size in MB. Overrides enfyra_setting.maxUploadFileSize for multipart requests when set.',
      ),
    description: col
      .text()
      .system()
      .description('Description of what the route does'),
  })
  .relations({
    mainTable: rel
      .manyToOne('enfyra_table')
      .system()
      .onDelete('CASCADE')
      .description('Primary table that this route operates on'),
    availableMethods: rel
      .manyToMany('enfyra_method')
      .inverse('routesWithAvailable')
      .system()
      .description('HTTP methods this route supports'),
    preHooks: rel
      .oneToMany('enfyra_pre_hook')
      .inverse('route')
      .system()
      .description('Pre-hooks that run before route execution'),
    postHooks: rel
      .oneToMany('enfyra_post_hook')
      .inverse('route')
      .system()
      .description('Post-hooks that run after route execution'),
  })
  .uniques([['path']]);

snapshot
  .table('enfyra_role', {
    description: 'Defines user roles for permission management',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .default(null)
      .description('Unique role name (e.g., Admin, Editor, Viewer)'),
    description: col
      .text()
      .system()
      .description("Description of the role's purpose and permissions"),
  })
  .uniques([['name']]);

snapshot
  .table('enfyra_route_permission', {
    description: 'Maps permissions between roles, users, and routes',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this permission rule is active'),
    description: col
      .text()
      .system()
      .description('Description of what this permission allows'),
  })
  .relations({
    role: rel
      .manyToOne('enfyra_role')
      .inverse('routePermissions')
      .system()
      .onDelete('CASCADE')
      .description('Role that this permission applies to'),
    route: rel
      .manyToOne('enfyra_route')
      .inverse('routePermissions')
      .system()
      .onDelete('CASCADE')
      .description('Route that this permission controls access to'),
    allowedUsers: rel
      .manyToMany('enfyra_user')
      .inverse('allowedRoutePermissions')
      .system()
      .description('Specific users who have this permission'),
  });

snapshot
  .table('enfyra_graphql_operation', {
    description:
      'Canonical immutable GraphQL operations used by public access and GraphQL permissions',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('Canonical GraphQL operation name'),
    label: col
      .varchar()
      .notNull()
      .system()
      .description('Human-readable operation label'),
    description: col
      .text()
      .system()
      .nullable()
      .description('Description of the GraphQL operation'),
    order: col
      .int()
      .notNull()
      .system()
      .default(0)
      .description('Stable display order'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Always true for canonical GraphQL operations'),
  })
  .relations({
    publicGraphqlConfigs: rel
      .manyToMany('enfyra_graphql')
      .inverse('publicOperations')
      .system()
      .description('GraphQL configs that expose this operation publicly'),
    graphqlPermissions: rel
      .manyToMany('enfyra_graphql_permission')
      .inverse('operations')
      .system()
      .description('GraphQL permissions that grant this operation'),
  })
  .uniques([['name']]);

snapshot
  .table('enfyra_graphql_permission', {
    description:
      'Grants private GraphQL operations to a role or explicit users',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this GraphQL permission is active'),
    description: col
      .text()
      .system()
      .nullable()
      .description('Description of what this GraphQL permission grants'),
  })
  .relations({
    graphql: rel
      .manyToOne('enfyra_graphql')
      .inverse('permissions')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('GraphQL table configuration controlled by this permission'),
    role: rel
      .manyToOne('enfyra_role')
      .system()
      .onDelete('CASCADE')
      .nullable()
      .description('Role that receives these private GraphQL operations'),
    allowedUsers: rel
      .manyToMany('enfyra_user')
      .system()
      .description(
        'Explicit users that receive these private GraphQL operations',
      ),
    operations: rel
      .manyToMany('enfyra_graphql_operation')
      .inverse('graphqlPermissions')
      .notNull()
      .system()
      .description('Private GraphQL operations granted by this permission'),
  });

snapshot
  .table('enfyra_field_permission', {
    description:
      'Defines per-field permissions (columns and relations) by role and user, with optional conditions',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this rule is active'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined field permission'),
    description: col
      .text()
      .system()
      .nullable()
      .default(null)
      .description('Description of what this rule does'),
    action: col
      .enum(['read', 'create', 'update'])
      .notNull()
      .system()
      .default('read')
      .description('Action this rule applies to'),
    effect: col
      .enum(['allow', 'deny'])
      .notNull()
      .system()
      .default('allow')
      .description('Whether this rule allows or denies access'),
    condition: col
      .simpleJson()
      .system()
      .nullable()
      .default(null)
      .description(
        'Optional filter DSL condition that must match for this rule to apply',
      ),
  })
  .relations({
    role: rel
      .manyToOne('enfyra_role')
      .system()
      .onDelete('CASCADE')
      .description('Role that this rule applies to'),
    column: rel
      .manyToOne('enfyra_column')
      .inverse('fieldPermissions')
      .system()
      .onDelete('CASCADE')
      .nullable()
      .description('Column this rule applies to'),
    relation: rel
      .manyToOne('enfyra_relation')
      .inverse('fieldPermissions')
      .system()
      .onDelete('CASCADE')
      .nullable()
      .description('Relation this rule applies to'),
    allowedUsers: rel
      .manyToMany('enfyra_user')
      .system()
      .description('Specific users this rule applies to'),
  })
  .uniques([
    ['role', 'action', 'column'],
    ['role', 'action', 'relation'],
  ]);

snapshot
  .table('enfyra_route_handler', {
    description: 'Stores custom logic handlers for route endpoints',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    sourceCode: col
      .code()
      .system()
      .nullable()
      .description(
        'Custom JavaScript or TypeScript code to execute for this route',
      ),
    scriptLanguage: col
      .enum(['javascript', 'typescript'])
      .notNull()
      .system()
      .default('typescript')
      .description('Language used by sourceCode before server compilation'),
    compiledCode: col
      .code()
      .generated()
      .system()
      .immutable()
      .nullable()
      .description('Server-compiled JavaScript code executed by the runtime'),
    timeout: col
      .int()
      .system()
      .default(30000)
      .nullable()
      .description('Timeout in milliseconds for this handler execution'),
    description: col
      .text()
      .system()
      .description('Description of what this handler does'),
  })
  .relations({
    route: rel
      .manyToOne('enfyra_route')
      .inverse('handlers')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('The route this handler is attached to'),
    method: rel
      .manyToOne('enfyra_method')
      .inverse('handlers')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('HTTP method (GET, POST, etc.) this handler responds to'),
  })
  .uniques([['route', 'method']]);

snapshot
  .table('enfyra_pre_hook', {
    description: 'Defines lifecycle hooks that run before route execution',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('Descriptive name for the hook'),
    sourceCode: col
      .code()
      .system()
      .nullable()
      .description('Code to execute before the main route handler'),
    scriptLanguage: col
      .enum(['javascript', 'typescript'])
      .notNull()
      .system()
      .default('typescript')
      .description('Language used by sourceCode before server compilation'),
    compiledCode: col
      .code()
      .generated()
      .system()
      .immutable()
      .nullable()
      .description('Server-compiled JavaScript code executed by the runtime'),
    priority: col
      .int()
      .system()
      .default(0)
      .nullable()
      .description('Execution order (lower numbers execute first)'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the hook is active'),
    isGlobal: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this hook applies globally to all routes'),
    description: col
      .text()
      .system()
      .description('Description of what the hook does'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined hook'),
  })
  .relations({
    route: rel
      .manyToOne('enfyra_route')
      .inverse('preHooks')
      .system()
      .onDelete('CASCADE')
      .description(
        'Route this hook is attached to (null when isGlobal is true)',
      ),
    methods: rel
      .manyToMany('enfyra_method')
      .inverse('preHooks')
      .system()
      .description('HTTP methods this hook applies to'),
  });

snapshot
  .table('enfyra_post_hook', {
    description: 'Defines lifecycle hooks that run after route execution',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('Descriptive name for the hook'),
    sourceCode: col
      .code()
      .system()
      .nullable()
      .description('Code to execute after the main route handler'),
    scriptLanguage: col
      .enum(['javascript', 'typescript'])
      .notNull()
      .system()
      .default('typescript')
      .description('Language used by sourceCode before server compilation'),
    compiledCode: col
      .code()
      .generated()
      .system()
      .immutable()
      .nullable()
      .description('Server-compiled JavaScript code executed by the runtime'),
    priority: col
      .int()
      .system()
      .default(0)
      .nullable()
      .description('Execution order (lower numbers execute first)'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the hook is active'),
    isGlobal: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this hook applies globally to all routes'),
    description: col
      .text()
      .system()
      .description('Description of what the hook does'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined hook'),
  })
  .relations({
    route: rel
      .manyToOne('enfyra_route')
      .inverse('postHooks')
      .system()
      .onDelete('CASCADE')
      .description(
        'Route this hook is attached to (null when isGlobal is true)',
      ),
    methods: rel
      .manyToMany('enfyra_method')
      .inverse('postHooks')
      .system()
      .description('HTTP methods this hook applies to'),
  });

snapshot
  .table('enfyra_session', {
    description: 'Stores active user sessions and authentication tokens',
    system: true,
  })
  .columns({
    id: col
      .uuid()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Unique session identifier'),
    expiredAt: col
      .date()
      .notNull()
      .system()
      .default('now')
      .description('When the session expires'),
    remember: col
      .boolean()
      .system()
      .default(false)
      .description("Whether this is a long-lived 'remember me' session"),
    loginProvider: col
      .varchar()
      .system()
      .nullable()
      .description(
        'OAuth provider used to login (google, facebook, github) or null for email/password',
      ),
    refreshTokenHash: col
      .varchar()
      .system()
      .nullable()
      .description('SHA-256 hash of the current valid refresh token'),
  })
  .relations({
    user: rel
      .manyToOne('enfyra_user')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('User who owns this session'),
  });

snapshot
  .table('enfyra_api_token', {
    description: 'Stores user-owned API tokens for programmatic access',
    system: true,
  })
  .columns({
    id: col
      .uuid()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Unique API token identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('User-facing API token name'),
    tokenHash: col
      .varchar()
      .notNull()
      .system()
      .private()
      .description('SHA-256 hash of the API token'),
    prefix: col
      .varchar()
      .notNull()
      .system()
      .description('Safe token prefix for display'),
    last4: col
      .varchar()
      .notNull()
      .system()
      .description('Safe final token characters for display'),
    expiresAt: col
      .date()
      .system()
      .nullable()
      .description('When the API token expires; null means never expires'),
    lastUsedAt: col
      .date()
      .system()
      .nullable()
      .description('When the API token was last exchanged for an access token'),
    lastUsedIp: col
      .varchar()
      .system()
      .nullable()
      .description('Last client IP seen for this API token'),
  })
  .relations({
    user: rel
      .manyToOne('enfyra_user')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('User who owns this API token'),
  })
  .uniques([['tokenHash']]);

snapshot
  .table('enfyra_schema_migration', {
    description:
      'Tracks schema migration operations with up/down scripts for automatic recovery',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key'),
    uuid: col
      .varchar()
      .notNull()
      .system()
      .description('Unique migration version identifier'),
    tableName: col
      .varchar()
      .notNull()
      .system()
      .description('Affected table name'),
    operation: col
      .varchar()
      .notNull()
      .system()
      .description('Operation type: create, update, or delete'),
    status: col
      .varchar()
      .notNull()
      .system()
      .default('pending')
      .description('Status: pending, running, completed, failed, rolled_back'),
    upScript: col
      .text()
      .system()
      .description('DDL statements to apply the migration'),
    downScript: col
      .text()
      .system()
      .description('DDL statements to revert the migration'),
    beforeSnapshot: col
      .simpleJson()
      .system()
      .nullable()
      .description('Table metadata before migration'),
    errorMessage: col
      .text()
      .system()
      .nullable()
      .description('Error details if migration failed'),
    startedAt: col
      .date()
      .system()
      .description('When migration started executing'),
    completedAt: col
      .date()
      .system()
      .nullable()
      .description('When migration completed or was rolled back'),
  })
  .uniques([['uuid']]);

snapshot
  .table('enfyra_method', {
    description:
      'Defines available HTTP methods (GET, POST, PATCH, DELETE, etc.)',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description(
        'HTTP method name (GET, POST, PATCH, DELETE, PUT, HEAD, OPTIONS)',
      ),
    buttonColor: col
      .varchar()
      .notNull()
      .system()
      .default('#f3f4f6')
      .description(
        'Hex background color used when rendering this method in admin UI controls',
      ),
    textColor: col
      .varchar()
      .notNull()
      .system()
      .default('#374151')
      .description(
        'Hex text color used when rendering this method in admin UI controls',
      ),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined method'),
  })
  .relations({
    routePermissions: rel
      .manyToMany('enfyra_route_permission')
      .inverse('methods')
      .system()
      .nullable()
      .description('Permissions associated with this method'),
    routes: rel
      .manyToMany('enfyra_route')
      .inverse('publicMethods')
      .system()
      .description('Routes that allow this method without authentication'),
    routesWithAvailable: rel
      .manyToMany('enfyra_route')
      .inverse('availableMethods')
      .system()
      .description('Routes that have this method available'),
    routesSkipRoleGuard: rel
      .manyToMany('enfyra_route')
      .inverse('skipRoleGuardMethods')
      .system()
      .description(
        'Routes where this method skips RoleGuard (still requires authentication)',
      ),
  })
  .uniques([['name']]);

snapshot
  .table('enfyra_menu', {
    description: 'Defines the navigation menu structure for the application',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    type: col
      .enum(['Dropdown Menu', 'Menu'])
      .notNull()
      .system()
      .description(
        'Type of menu item (Dropdown Menu can have children, Menu is a leaf node)',
      ),
    label: col
      .varchar()
      .notNull()
      .system()
      .description('Display text for the menu item'),
    icon: col
      .varchar()
      .notNull()
      .system()
      .default('lucide:menu')
      .description('Icon identifier for the menu item'),
    path: col
      .varchar()
      .system()
      .nullable()
      .description('URL path the menu item links to'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the menu item is visible'),
    isPublic: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether every role can see this menu item'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined menu item'),
    description: col
      .text()
      .system()
      .description("Description of the menu item's purpose"),
    order: col
      .int()
      .notNull()
      .system()
      .default(0)
      .description('Display order within parent (lower numbers appear first)'),
    permission: col
      .simpleJson()
      .system()
      .nullable()
      .description('Permission rules controlling who can see this menu item'),
  })
  .relations({
    parent: rel
      .manyToOne('enfyra_menu')
      .inverse('children')
      .system()
      .nullable()
      .description('Parent menu item (null for top-level items)'),
    menuPermissions: rel
      .oneToMany('enfyra_menu_permission')
      .inverse('menu')
      .system()
      .description('Role-specific visibility rules for this menu item'),
  })
  .uniques([['type', 'label'], ['path']])
  .indexes([['order']]);

snapshot
  .table('enfyra_menu_permission', {
    description: 'Controls which roles can see a non-public admin menu item',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this menu visibility rule is active'),
  })
  .relations({
    menu: rel
      .manyToOne('enfyra_menu')
      .inverse('menuPermissions')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('Menu item controlled by this visibility rule'),
    role: rel
      .manyToOne('enfyra_role')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('Role allowed to see the menu item'),
  })
  .uniques([['menu', 'role']]);

snapshot
  .table('enfyra_extension', {
    description:
      'Stores custom UI extensions (pages, widgets, and global shell extensions) written in Vue',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    type: col
      .enum(['page', 'widget', 'global'])
      .notNull()
      .system()
      .default('page')
      .description(
        'Type of extension (full page, embeddable widget, or global shell extension)',
      ),
    name: col
      .varchar()
      .generated(false)
      .notNull()
      .system()
      .description('Human-readable name for the extension'),
    extensionId: col
      .varchar()
      .generated()
      .notNull()
      .system()
      .description('Unique identifier for the extension (auto-generated)'),
    version: col
      .varchar()
      .notNull()
      .system()
      .default('1.0.0')
      .description('Version number of the extension'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the extension is active'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined extension'),
    description: col
      .text()
      .system()
      .description('Description of what the extension does'),
    compiledCode: col
      .code()
      .generated()
      .notNull()
      .system()
      .description('Compiled/bundled JavaScript code ready for execution'),
    code: col
      .code()
      .notNull()
      .system()
      .description('Source code for the extension (React/Vue component)'),
  })
  .relations({
    menu: rel
      .oneToOne('enfyra_menu')
      .inverse('extension')
      .system()
      .nullable()
      .description('Menu item that links to this extension'),
    createdBy: rel
      .manyToOne('enfyra_user')
      .system()
      .nullable()
      .description('User who created this extension'),
    updatedBy: rel
      .manyToOne('enfyra_user')
      .system()
      .nullable()
      .description('User who last updated this extension'),
  })
  .uniques([['menu']]);

snapshot
  .table('enfyra_folder', {
    description: 'Organizes files into a hierarchical folder structure',
    system: true,
  })
  .columns({
    id: col
      .uuid()
      .primary()
      .generated()
      .notNull()
      .description('Unique folder identifier'),
    name: col.varchar().notNull().description('Folder display name'),
    slug: col
      .varchar()
      .generated()
      .notNull()
      .description('URL-friendly folder name (auto-generated from name)'),
    order: col
      .int()
      .notNull()
      .default(0)
      .description('Display order within parent folder'),
    icon: col
      .varchar()
      .default('lucide:folder')
      .nullable()
      .description('Icon identifier for the folder'),
    description: col
      .text()
      .nullable()
      .description("Description of the folder's purpose"),
    isSystem: col
      .boolean()
      .notNull()
      .default(false)
      .description('Whether this is a system-defined folder'),
  })
  .relations({
    parent: rel
      .manyToOne('enfyra_folder')
      .inverse('children')
      .nullable()
      .description('Parent folder (null for root folders)'),
    user: rel
      .manyToOne('enfyra_user')
      .nullable()
      .description('User who owns this folder'),
  })
  .uniques([['slug', 'parent']])
  .indexes([['order'], ['parent']]);

snapshot
  .table('enfyra_file', {
    description: 'Stores uploaded files and their metadata',
    system: true,
  })
  .columns({
    id: col
      .uuid()
      .primary()
      .generated()
      .notNull()
      .description('Unique file identifier'),
    filename: col
      .varchar()
      .notNull()
      .description('Original filename including extension'),
    isPublic: col
      .boolean()
      .notNull()
      .default(true)
      .description('Allow public access without authentication'),
    mimetype: col
      .varchar()
      .generated()
      .notNull()
      .description('MIME type of the file (e.g., image/png, application/pdf)'),
    filesize: col
      .bigint()
      .generated()
      .notNull()
      .description('File size in bytes'),
    location: col
      .varchar()
      .generated()
      .notNull()
      .description('Full path or URL to the file'),
    description: col
      .text()
      .nullable()
      .description('Description or notes about the file'),
    status: col
      .enum(['active', 'archived', 'quarantine'])
      .notNull()
      .default('active')
      .description('File status (active, archived, or quarantined)'),
  })
  .relations({
    folder: rel
      .manyToOne('enfyra_folder')
      .inverse('files')
      .nullable()
      .description('Folder containing this file'),
    uploadedBy: rel
      .manyToOne('enfyra_user')
      .generated()
      .nullable()
      .description('User who uploaded the file'),
    storageConfig: rel
      .manyToOne('enfyra_storage_config')
      .nullable()
      .description('Storage configuration (account) used for this file'),
  })
  .uniques([['location']])
  .indexes([['filesize'], ['status'], ['isPublic']]);

snapshot
  .table('enfyra_file_permission', {
    description: 'Controls access permissions for files',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .description('Primary key identifier'),
    actions: col
      .arraySelect(['view', 'edit', 'delete', 'share', 'download'])
      .nullable()
      .description('Allowed actions for this permission'),
    isEnabled: col
      .boolean()
      .notNull()
      .default(true)
      .description('Enable/disable this permission rule'),
    allowedDomains: col
      .simpleJson()
      .nullable()
      .description('List of allowed domains for CORS (null = all domains)'),
    description: col
      .text()
      .nullable()
      .description('Description of what this permission allows'),
  })
  .relations({
    file: rel
      .manyToOne('enfyra_file')
      .inverse('permissions')
      .onDelete('CASCADE')
      .nullable()
      .description('File this permission applies to'),
    role: rel
      .manyToOne('enfyra_role')
      .onDelete('CASCADE')
      .nullable()
      .description('Role that has this permission'),
    allowedUsers: rel
      .manyToMany('enfyra_user')
      .system()
      .nullable()
      .description('Specific users who have this permission')
      .junction({
        table: 'j_8110450610b3',
        source: 'enfyra_file_permissionId',
        target: 'enfyra_userId',
      }),
  })
  .uniques([['file', 'role']]);

snapshot
  .table('enfyra_package', {
    description:
      'Manages npm packages installed in the application (app and server)',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .generated(false)
      .notNull()
      .system()
      .description('NPM package name (e.g., lodash, express)'),
    version: col
      .varchar()
      .notNull()
      .system()
      .default('latest')
      .description('Actual installed version from node_modules'),
    flags: col
      .varchar()
      .system()
      .nullable()
      .description("Install flags like '--ignore-engines --force'"),
    type: col
      .enum(['App', 'Server'])
      .notNull()
      .description(
        'Whether this is a frontend (App) or backend (Server) package',
      ),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the package is currently active'),
    description: col
      .text()
      .system()
      .nullable()
      .description('Short package description'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a core system package'),
    status: col
      .enum(['installing', 'updating', 'uninstalling', 'installed', 'failed'])
      .notNull()
      .system()
      .default('installed')
      .description('Current lifecycle status of the package'),
    installTimeout: col
      .int()
      .notNull()
      .system()
      .default(60)
      .description('Install timeout in seconds'),
    lastError: col
      .text()
      .system()
      .nullable()
      .description(
        'Last error message from install/update/uninstall operation',
      ),
  })
  .relations({
    installedBy: rel
      .manyToOne('enfyra_user')
      .system()
      .nullable()
      .description('User who installed this package'),
  });

snapshot
  .table('enfyra_bootstrap_script', {
    description:
      'Stores custom scripts that run during application initialization',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('Unique name identifier for the bootstrap script'),
    description: col
      .text()
      .system()
      .description('Description of what the script does'),
    sourceCode: col
      .code()
      .notNull()
      .system()
      .description('Source code to execute'),
    scriptLanguage: col
      .enum(['javascript', 'typescript'])
      .notNull()
      .system()
      .default('typescript')
      .description('Language used by sourceCode before server compilation'),
    compiledCode: col
      .code()
      .generated()
      .system()
      .immutable()
      .nullable()
      .description('Server-compiled JavaScript code executed by the runtime'),
    timeout: col
      .int()
      .system()
      .nullable()
      .description(
        'Timeout in milliseconds for script execution. If not set, uses default system timeout.',
      ),
    priority: col
      .int()
      .notNull()
      .system()
      .default(0)
      .description('Execution priority order (lower numbers execute first)'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the script is enabled for execution'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-generated script'),
  })
  .relations({
    createdBy: rel
      .manyToOne('enfyra_user')
      .system()
      .nullable()
      .description('User who created the script'),
    updatedBy: rel
      .manyToOne('enfyra_user')
      .system()
      .nullable()
      .description('User who last updated the script'),
  })
  .uniques([['name']]);

snapshot
  .table('enfyra_storage_config', {
    description:
      'Configures storage backends for file uploads (local, S3, GCS, etc.)',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description(
        "Storage configuration name (e.g., 'AWS S3', 'Google Cloud Storage', 'Local Storage')",
      ),
    type: col
      .enum([
        'Local Storage',
        'Amazon S3',
        'Google Cloud Storage',
        'Cloudflare R2',
      ])
      .notNull()
      .system()
      .description('Storage backend type'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this storage configuration is active'),
    isDefault: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description(
        'Whether this storage configuration is the default target for uploads when no storageConfig is provided',
      ),
    bucket: col
      .varchar()
      .system()
      .nullable()
      .description('Bucket name (used for S3/GCS)'),
    region: col
      .varchar()
      .system()
      .nullable()
      .description(
        "Storage region - Required for S3 (e.g., us-east-1, ap-southeast-1), optional for R2 (use 'auto' or leave empty), not needed for GCS/Local Storage",
      ),
    accessKeyId: col
      .varchar()
      .system()
      .private()
      .nullable()
      .description('S3/R2 access key ID'),
    secretAccessKey: col
      .varchar()
      .system()
      .private()
      .nullable()
      .description('S3/R2 secret access key'),
    accountId: col
      .varchar()
      .system()
      .private()
      .nullable()
      .description(
        'Cloudflare account ID (for R2, used to generate endpoint automatically)',
      ),
    credentials: col
      .simpleJson()
      .system()
      .private()
      .nullable()
      .description('GCS service account JSON credentials'),
    description: col
      .text()
      .system()
      .nullable()
      .description('Description of this storage configuration'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined storage configuration'),
  })
  .relations({
    createdBy: rel
      .manyToOne('enfyra_user')
      .system()
      .nullable()
      .description('User who created this configuration'),
    updatedBy: rel
      .manyToOne('enfyra_user')
      .system()
      .nullable()
      .description('User who last updated this configuration'),
  })
  .uniques([['name']]);

snapshot
  .table('enfyra_websocket', {
    description:
      'Defines WebSocket gateway namespaces for real-time communication',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    path: col
      .varchar()
      .notNull()
      .system()
      .default(null)
      .description(
        'WebSocket namespace path with pattern support (e.g., /chat/: roomId)',
      ),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the gateway is active'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined gateway'),
    description: col
      .text()
      .system()
      .description("Description of the gateway's purpose"),
    requireAuth: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether authentication is required for connections'),
    sourceCode: col
      .code()
      .system()
      .nullable()
      .description('JavaScript or TypeScript source code to execute'),
    scriptLanguage: col
      .enum(['javascript', 'typescript'])
      .notNull()
      .system()
      .default('typescript')
      .description('Language used by sourceCode before server compilation'),
    compiledCode: col
      .code()
      .generated()
      .system()
      .immutable()
      .nullable()
      .description('Server-compiled JavaScript code executed by the runtime'),
    connectionHandlerTimeout: col
      .int()
      .system()
      .nullable()
      .description(
        'Timeout in milliseconds for connection handler execution. If not set, uses default system timeout.',
      ),
  })
  .relations({})
  .uniques([['path']]);

snapshot
  .table('enfyra_websocket_event', {
    description: 'Defines event handlers for WebSocket gateways',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    eventName: col
      .varchar()
      .notNull()
      .system()
      .default(null)
      .description('Event name to listen for (e.g., sendMessage, typing)'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the event handler is active'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined event'),
    description: col
      .text()
      .system()
      .description('Description of what the event does'),
    sourceCode: col
      .code()
      .system()
      .nullable()
      .description('JavaScript or TypeScript source code to execute'),
    scriptLanguage: col
      .enum(['javascript', 'typescript'])
      .notNull()
      .system()
      .default('typescript')
      .description('Language used by sourceCode before server compilation'),
    compiledCode: col
      .code()
      .generated()
      .system()
      .immutable()
      .nullable()
      .description('Server-compiled JavaScript code executed by the runtime'),
    timeout: col
      .int()
      .system()
      .nullable()
      .description(
        'Timeout in milliseconds for event handler execution. If not set, uses default system timeout.',
      ),
  })
  .relations({
    gateway: rel
      .manyToOne('enfyra_websocket')
      .inverse('events')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('Gateway this event belongs to'),
  })
  .uniques([['gateway', 'eventName']]);

snapshot
  .table('enfyra_flow', {
    description:
      'Defines automated workflows with triggers, steps, and execution logic',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('Unique name of the flow'),
    description: col
      .text()
      .system()
      .nullable()
      .description('Description of what the flow does'),
    icon: col
      .varchar()
      .system()
      .default('lucide:workflow')
      .nullable()
      .description('Icon identifier for UI display'),
    timeout: col
      .int()
      .system()
      .default(30000)
      .nullable()
      .description(
        'Maximum execution time in milliseconds for the entire flow',
      ),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the flow is active'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined flow'),
    maxExecutions: col
      .int()
      .system()
      .default(100)
      .nullable()
      .description(
        'Maximum number of execution history records to keep per flow',
      ),
  })
  .relations({
    triggers: rel
      .oneToMany('enfyra_flow_trigger')
      .inverse('flow')
      .system()
      .description('Trigger definitions that activate this flow'),
  })
  .uniques([['name']]);

snapshot
  .table('enfyra_flow_trigger', {
    description:
      'Junction table defining how flows are activated: schedule (cron), event (table mutation), or webhook (route)',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    type: col
      .enum(['schedule', 'event', 'webhook'])
      .notNull()
      .system()
      .description(
        'Trigger type: schedule (cron-based), event (table mutation), webhook (route-based)',
      ),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this trigger is active'),
    config: col
      .simpleJson()
      .system()
      .nullable()
      .description(
        'Type-specific config: schedule={cron,timezone}, event={filter}, webhook={method}',
      ),
    tableEvent: col
      .enum(['create', 'update', 'delete'])
      .system()
      .nullable()
      .description(
        'Which table mutation event activates this trigger (required when type=event)',
      ),
  })
  .relations({
    flow: rel
      .manyToOne('enfyra_flow')
      .inverse('triggers')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('Flow this trigger activates'),
    route: rel
      .manyToOne('enfyra_route')
      .system()
      .nullable()
      .onDelete('CASCADE')
      .description(
        'Route that triggers this flow (required when type=webhook)',
      ),
    table: rel
      .manyToOne('enfyra_table')
      .system()
      .nullable()
      .onDelete('CASCADE')
      .description(
        'Table whose mutations trigger this flow (required when type=event)',
      ),
  });

snapshot
  .table('enfyra_flow_step', {
    description: 'Defines individual steps within a flow',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    key: col
      .varchar()
      .notNull()
      .system()
      .description(
        'Unique key within the flow used to reference this step result in the data chain',
      ),
    stepOrder: col
      .int()
      .notNull()
      .system()
      .default(0)
      .description('Execution order of the step within the flow'),
    type: col
      .enum([
        'script',
        'condition',
        'query',
        'create',
        'update',
        'delete',
        'http',
        'trigger_flow',
        'sleep',
        'log',
      ])
      .notNull()
      .system()
      .description('Type of operation this step performs'),
    config: col
      .simpleJson()
      .system()
      .nullable()
      .description('JSON config for the step (code, URL, table, filter, etc.)'),
    sourceCode: col
      .code()
      .system()
      .nullable()
      .description(
        'JavaScript or TypeScript source code to execute for script and condition steps',
      ),
    scriptLanguage: col
      .enum(['javascript', 'typescript'])
      .notNull()
      .system()
      .default('typescript')
      .description('Language used by sourceCode before server compilation'),
    compiledCode: col
      .code()
      .generated()
      .system()
      .immutable()
      .nullable()
      .description(
        'Server-compiled JavaScript code executed by the flow runtime',
      ),
    timeout: col
      .int()
      .system()
      .default(5000)
      .nullable()
      .description('Maximum execution time in milliseconds for this step'),
    onError: col
      .enum(['stop', 'skip', 'retry'])
      .notNull()
      .system()
      .default('stop')
      .description('Error handling strategy: stop flow, skip step, or retry'),
    retryAttempts: col
      .int()
      .system()
      .default(0)
      .nullable()
      .description('Number of retry attempts when onError is retry'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether the step is active'),
    branch: col
      .enum(['true', 'false'])
      .system()
      .nullable()
      .description('Which branch of the parent condition (true or false)'),
  })
  .relations({
    flow: rel
      .manyToOne('enfyra_flow')
      .inverse('steps')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('Flow this step belongs to'),
    parent: rel
      .manyToOne('enfyra_flow_step')
      .inverse('children')
      .system()
      .nullable()
      .description('Parent condition step (null = root level)'),
  });

snapshot
  .table('enfyra_flow_execution', {
    description: 'Stores execution history and state for flow runs',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    status: col
      .enum(['pending', 'running', 'completed', 'failed', 'cancelled'])
      .notNull()
      .system()
      .default('pending')
      .description('Current execution status'),
    payload: col
      .simpleJson()
      .system()
      .nullable()
      .description('Input data from the trigger'),
    completedSteps: col
      .simpleJson()
      .system()
      .nullable()
      .description('Array of completed step keys for resumability'),
    currentStep: col
      .varchar()
      .system()
      .nullable()
      .description('Key of the currently executing step'),
    error: col
      .simpleJson()
      .system()
      .nullable()
      .description('Error details if execution failed'),
    startedAt: col
      .date()
      .system()
      .nullable()
      .description('When the execution started'),
    completedAt: col
      .date()
      .system()
      .nullable()
      .description('When the execution completed'),
    duration: col
      .int()
      .system()
      .nullable()
      .description('Execution duration in milliseconds'),
  })
  .relations({
    flow: rel
      .manyToOne('enfyra_flow')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('Flow that was executed'),
    triggeredBy: rel
      .manyToOne('enfyra_user')
      .system()
      .nullable()
      .description(
        'User who triggered the execution (null for cron/event triggers)',
      ),
  });

snapshot
  .table('enfyra_guard', {
    description:
      'Defines metadata-driven guards with nestable AND/OR logic tree for rate limiting, IP filtering, etc.',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    name: col
      .varchar()
      .notNull()
      .system()
      .description('Descriptive name for the guard'),
    position: col
      .enum(['pre_auth', 'post_auth'])
      .system()
      .nullable()
      .description(
        'Execution position: pre_auth (before JWT, only IP available) or post_auth (after JWT+Role, user available). Only meaningful for root guards',
      ),
    combinator: col
      .enum(['and', 'or'])
      .notNull()
      .system()
      .default('and')
      .description(
        'How children combine: and (all must pass) or or (any must pass)',
      ),
    priority: col
      .int()
      .system()
      .default(0)
      .nullable()
      .description(
        'Execution order among sibling guards (lower numbers execute first)',
      ),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether the guard is active'),
    isGlobal: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description(
        'Whether this guard applies globally to all routes. Only meaningful for root guards with type=route',
      ),
    type: col
      .enum(['route', 'graphql'])
      .notNull()
      .system()
      .default('route')
      .description(
        'Target type: route targets REST routes via route/methods; graphql targets GraphQL operations via table/gqlOperation matrix',
      ),
    gqlOperation: col
      .enum(['QUERY', 'CREATE', 'UPDATE', 'DELETE'])
      .system()
      .nullable()
      .description(
        'GraphQL operation this guard targets (null = all operations). Only meaningful when type=graphql',
      ),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined guard'),
    description: col
      .text()
      .system()
      .description('Description of what the guard does'),
  })
  .relations({
    parent: rel
      .manyToOne('enfyra_guard')
      .inverse('children')
      .system()
      .onDelete('CASCADE')
      .nullable()
      .description(
        'Parent guard for nested logic (null for root-level guards)',
      ),
    route: rel
      .manyToOne('enfyra_route')
      .inverse('guards')
      .system()
      .onDelete('CASCADE')
      .nullable()
      .description(
        'Route this guard is attached to (null when isGlobal is true). Only meaningful for root guards with type=route',
      ),
    table: rel
      .manyToOne('enfyra_table')
      .inverse('guards')
      .system()
      .onDelete('CASCADE')
      .nullable()
      .description(
        'Table this GraphQL guard targets (null = all tables). Only meaningful when type=graphql',
      ),
    methods: rel
      .manyToMany('enfyra_method')
      .system()
      .description(
        'HTTP methods this guard applies to. Only meaningful for root guards with type=route',
      ),
  });

snapshot
  .table('enfyra_guard_rule', {
    description:
      'Defines individual rules/conditions within a guard (rate limit, IP whitelist/blacklist)',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    type: col
      .enum([
        'rate_limit_by_ip',
        'rate_limit_by_user',
        'rate_limit_by_route',
        'rate_limit_by_operation',
        'ip_whitelist',
        'ip_blacklist',
      ])
      .notNull()
      .system()
      .description(
        'Type of rule to evaluate. rate_limit_by_operation is GraphQL-only (keyed by table:operation)',
      ),
    config: col
      .simpleJson()
      .notNull()
      .system()
      .description(
        'Type-specific configuration (e.g. { maxRequests, perSeconds } for rate limit, { ips: [] } for IP lists)',
      ),
    priority: col
      .int()
      .system()
      .default(0)
      .nullable()
      .description('Evaluation order within the guard (lower numbers first)'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(true)
      .description('Whether this rule is active'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether this is a system-defined rule'),
    description: col
      .text()
      .system()
      .description('Description of what this rule checks'),
  })
  .relations({
    guard: rel
      .manyToOne('enfyra_guard')
      .inverse('rules')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('Guard this rule belongs to'),
    users: rel
      .manyToMany('enfyra_user')
      .system()
      .description('Specific users this rule applies to (empty = all users)'),
  });

snapshot
  .table('enfyra_guard_alert', {
    description:
      'Records guard rejections for admin monitoring in Runtime Monitor',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key identifier'),
    scope: col
      .enum(['ip', 'user', 'route', 'operation'])
      .notNull()
      .system()
      .description(
        'Rate-limit or filter scope that triggered rejection. operation is GraphQL-only (scopeKey = table:operation)',
      ),
    scopeKey: col
      .varchar()
      .notNull()
      .system()
      .description(
        'Subject identifier: client IP, userId, or routePath depending on scope',
      ),
    routePath: col
      .varchar()
      .notNull()
      .system()
      .description('Route path that was rejected'),
    method: col
      .varchar()
      .notNull()
      .system()
      .description('HTTP method of the rejected request'),
    errorCode: col
      .varchar()
      .notNull()
      .system()
      .description(
        'Structured error code: RATE_LIMIT_EXCEEDED, IP_NOT_ALLOWED, IP_BLOCKED',
      ),
    guardName: col
      .varchar()
      .notNull()
      .system()
      .description(
        'Name of the guard that rejected the request (denormalized)',
      ),
  });

snapshot
  .table('enfyra_graphql', {
    description:
      'GraphQL configuration per table with independent public and authenticated operation access',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key'),
    isEnabled: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('Whether GraphQL is enabled for this table'),
    isSystem: col
      .boolean()
      .notNull()
      .system()
      .default(false)
      .description('System-managed flag'),
    description: col
      .text()
      .system()
      .nullable()
      .description('Human-readable description'),
    metadata: col
      .simpleJson()
      .system()
      .nullable()
      .description('Extended configuration (custom handler, timeout, etc.)'),
  })
  .relations({
    table: rel
      .manyToOne('enfyra_table')
      .inverse('gqlConfig')
      .notNull()
      .system()
      .onDelete('CASCADE')
      .description('The table this GraphQL config belongs to'),
    publicOperations: rel
      .manyToMany('enfyra_graphql_operation')
      .inverse('publicGraphqlConfigs')
      .system()
      .description('Operations callable without authentication'),
    permissions: rel
      .oneToMany('enfyra_graphql_permission')
      .inverse('graphql')
      .system()
      .description('Authenticated GraphQL operation permissions'),
  })
  .uniques([['table']]);

snapshot
  .table('enfyra_runtime_reload_log', {
    description:
      'Audits runtime reload transactions and terminal activation status',
    system: true,
  })
  .columns({
    id: col
      .int()
      .primary()
      .generated()
      .notNull()
      .system()
      .description('Primary key'),
    reloadId: col
      .varchar()
      .notNull()
      .system()
      .description('Unique runtime reload transaction id'),
    flow: col
      .varchar()
      .notNull()
      .system()
      .description('Primary reload flow or first affected runtime area'),
    tableName: col
      .varchar()
      .notNull()
      .system()
      .description('Invalidated table or synthetic admin reload target'),
    scope: col
      .enum(['partial', 'full'])
      .notNull()
      .system()
      .default('full')
      .description('Reload scope'),
    action: col
      .varchar()
      .notNull()
      .system()
      .default('reload')
      .description('Invalidation action that triggered the reload'),
    status: col
      .enum(['pending', 'building', 'activated', 'failed'])
      .notNull()
      .system()
      .default('building')
      .description(
        'Runtime reload status; building records must become activated or failed',
      ),
    chain: col
      .simpleJson()
      .system()
      .nullable()
      .description('Ordered reload chain requested by the orchestrator'),
    steps: col
      .simpleJson()
      .system()
      .nullable()
      .description('Step timing and failure details collected during reload'),
    payload: col
      .simpleJson()
      .system()
      .nullable()
      .description('Cache invalidation payload when available'),
    instanceId: col
      .varchar()
      .system()
      .nullable()
      .description('Runtime instance that processed the reload'),
    errorMessage: col
      .text()
      .system()
      .nullable()
      .description('Terminal failure reason'),
    startedAt: col
      .date()
      .notNull()
      .system()
      .description('When reload processing started'),
    completedAt: col
      .date()
      .system()
      .nullable()
      .description('When reload reached activated or failed terminal status'),
    durationMs: col
      .int()
      .system()
      .nullable()
      .description('Total reload duration in milliseconds'),
  })
  .uniques([['reloadId']])
  .indexes([['status'], ['tableName'], ['flow'], ['createdAt']]);

export default snapshot.build();
